ALTER TYPE "PaymentStatus" ADD VALUE 'PENDING_VERIFICATION' BEFORE 'RECEIVED';
ALTER TYPE "PaymentStatus" ADD VALUE 'REJECTED' BEFORE 'CANCELLED';

CREATE TYPE "PaymentPurpose" AS ENUM ('GENERAL', 'CONTRACT_RESERVATION');
