import { createHash } from "node:crypto";
import { buildRequestIdentity, buildResponseHash } from "../../official-exchange-rates/official-exchange-rate.resolver";
import { FacturaEnCrPreparationError, prepareFacturaEnCrSubmission, type FacturaEnCrLineSnapshot, type FacturaEnCrSubmissionAggregate, type FacturaEnCrTaxSnapshot } from "./factura-en-cr-submission";

describe("prepareFacturaEnCrSubmission", () => {
  it("builds a CRC Factura without receiver activity and preserves milliseconds", () => {
    const result=prepareFacturaEnCrSubmission(fixture()); const body=JSON.parse(result.canonicalBody);
    expect(result.endpoint).toBe("/documents/factura"); expect(body.fechaEmision).toBe("2026-08-23T06:34:56.789-06:00");
    expect(body.receptor).toEqual({tipoIdentificacion:"02",numeroIdentificacion:"3101999999",nombre:"Receiver"});
    expect(body).not.toHaveProperty("codigoActividadReceptor"); expect(body).not.toHaveProperty("exchangeRate"); expect(body.situacion).toBe("1");
  });
  it("emits present receiver activity in both documented positions",()=>{const result=prepareFacturaEnCrSubmission(fixture({receiver:{...receiver(),economicActivityCode:"791100"}}));const body=JSON.parse(result.canonicalBody);expect(body.codigoActividadReceptor).toBe("791100");expect(body.receptor.codigoActividad).toBe("791100");});
  it("omits receiver and phone for receiver-less/identified Tiquetes",()=>{const none=JSON.parse(prepareFacturaEnCrSubmission(tiquete({receiver:null})).canonicalBody);expect(none).not.toHaveProperty("receptor");const identified=JSON.parse(prepareFacturaEnCrSubmission(tiquete({receiver:{...receiver(),phone:"506 22220000"}})).canonicalBody);expect(identified.receptor).not.toHaveProperty("telefono");});
  it("maps only complete persisted address fields and omits neighborhood code",()=>{const address={provinceCode:"1",cantonCode:"01",districtCode:"02",neighborhoodCode:"03",otherAddressDetails:"Centro"};const body=JSON.parse(prepareFacturaEnCrSubmission(fixture({receiver:{...receiver(),address}})).canonicalBody);expect(body.receptor.ubicacion).toEqual({provincia:"1",canton:"01",distrito:"02",otrasSenas:"Centro"});});
  it.each([{provinceCode:"1"},{provinceCode:"1",cantonCode:"01",districtCode:"02",otherAddressDetails:""}])("rejects partial addresses",address=>expectCode(()=>prepareFacturaEnCrSubmission(fixture({receiver:{...receiver(),address}})),"FACTURA_EN_CR_RECEIVER_INVALID"));
  it.each(["02","03","05","08","09","10","runtime-value"])("rejects unsupported runtime type %s",documentTypeCode=>expectCode(()=>prepareFacturaEnCrSubmission(fixture({documentTypeCode})),"FACTURA_EN_CR_DOCUMENT_TYPE_UNSUPPORTED"));
  it("rejects receiver-less Factura and partial Tiquete",()=>{expectCode(()=>prepareFacturaEnCrSubmission(fixture({receiver:null})),"FACTURA_EN_CR_RECEIVER_INVALID");expectCode(()=>prepareFacturaEnCrSubmission(tiquete({receiver:{...receiver(),name:null}})),"FACTURA_EN_CR_RECEIVER_INVALID");});

  it("validates allocation identity and lower/upper bases",()=>{expect(JSON.parse(prepareFacturaEnCrSubmission(fixture({allocatedSequenceNumber:"1",fiscalNumber:"00100001010000000001"})).canonicalBody).consecutivoNumero).toBe("0000000001");expect(JSON.parse(prepareFacturaEnCrSubmission(fixture({allocatedSequenceNumber:"9999999999",fiscalNumber:"00100001019999999999"})).canonicalBody).consecutivoNumero).toBe("9999999999");for(const allocatedSequenceNumber of ["0","10000000000",null])expectCode(()=>prepareFacturaEnCrSubmission(fixture({allocatedSequenceNumber})),"FACTURA_EN_CR_ALLOCATION_MISMATCH");expectCode(()=>prepareFacturaEnCrSubmission(fixture({fiscalNumber:"00100001010000000043"})),"FACTURA_EN_CR_ALLOCATION_MISMATCH");});
  it("handles both Costa Rica midnight boundaries",()=>{const before=JSON.parse(prepareFacturaEnCrSubmission(fixture({fiscalEmissionAt:new Date("2026-08-24T05:59:59.999Z")})).canonicalBody);expect(before.fechaEmision).toBe("2026-08-23T23:59:59.999-06:00");const after=JSON.parse(prepareFacturaEnCrSubmission(fixture({fiscalEmissionAt:new Date("2026-08-24T06:00:00.000Z"),fiscalIssueDate:"2026-08-24"})).canonicalBody);expect(after.fechaEmision).toBe("2026-08-24T00:00:00.000-06:00");});
  it.each(["2026-02-30","2026-13-01","2025-02-29"])("rejects invalid date %s",fiscalIssueDate=>expectCode(()=>prepareFacturaEnCrSubmission(fixture({fiscalIssueDate})),"FACTURA_EN_CR_SNAPSHOT_INCOMPLETE"));

  it("verifies and emits a complete exact USD observation",()=>{const body=JSON.parse(prepareFacturaEnCrSubmission(usd()).canonicalBody);expect(body.exchangeRate).toBe(512.123456789012);expect(prepareFacturaEnCrSubmission(usd()).canonicalBody).toContain('"exchangeRate":512.123456789012');});
  it.each(["countryCode","foreignCurrencyCode","localCurrencyCode","rateType","effectiveDate","sourceAuthority","sourceIndicatorCode","requestIdentity","responseHash","value"])("rejects USD observation mismatch: %s",key=>{const o=official();const replacements:Record<string,unknown>={countryCode:"US",foreignCurrencyCode:"EUR",localCurrencyCode:"USD",rateType:"REFERENCE_BUY",effectiveDate:"2026-08-22",sourceAuthority:"OTHER",sourceIndicatorCode:"317",requestIdentity:"wrong",responseHash:"A".repeat(64),value:"513"};(o as unknown as Record<string,unknown>)[key]=replacements[key];expectCode(()=>prepareFacturaEnCrSubmission(usd({officialExchangeRateObservation:o})),"FACTURA_EN_CR_OFFICIAL_RATE_MISMATCH");});
  it("rejects missing USD observation and contradictory CRC observation",()=>{expectCode(()=>prepareFacturaEnCrSubmission(fixture({currencyCode:"USD",exchangeRate:"512"})),"FACTURA_EN_CR_OFFICIAL_RATE_MISMATCH");expectCode(()=>prepareFacturaEnCrSubmission(fixture({officialExchangeRateObservation:official()})),"FACTURA_EN_CR_OFFICIAL_RATE_MISMATCH");});

  it("accepts Decimal(18,4), Decimal(7,4), and Decimal(30,12) boundaries",()=>{const maxLine=line({quantity:"99999999999999.9999",unitPrice:"1",grossAmount:"99999999999999.9999",taxableBase:"99999999999999.9999",lineSubtotal:"99999999999999.9999",taxes:[tax({rateCode:"10",ratePercentage:"0.0000",taxableBase:"99999999999999.9999",taxAmount:"0",netTaxAmount:"0"})],taxAmount:"0",netTaxAmount:"0",lineTotal:"99999999999999.9999"});expect(()=>prepareFacturaEnCrSubmission(fixture({lines:[maxLine]}))).not.toThrow();expect(()=>prepareFacturaEnCrSubmission(usd({exchangeRate:"999999999999999999.999999999999",officialExchangeRateObservation:official("999999999999999999.999999999999")}))).not.toThrow();});
  it.each(["-1","+1","01","1e2","1,000","NaN","Infinity","","1.00001","100000000000000"])("rejects adversarial Decimal(18,4) %s",quantity=>expectCode(()=>prepareFacturaEnCrSubmission(fixture({lines:[line({quantity})]})),"FACTURA_EN_CR_LINE_TAX_INVALID"));
  it("normalizes only insignificant persisted trailing zeroes",()=>expect(prepareFacturaEnCrSubmission(fixture()).canonicalBody).toContain('"cantidad":1'));

  it("maps valid 13% and explicit zero-rate IVA",()=>{expect(JSON.parse(prepareFacturaEnCrSubmission(fixture()).canonicalBody).detalle[0].impuesto[0]).toEqual({codigo:"01",codigoTarifa:"08",tarifa:13});const zero=line({taxes:[tax({rateCode:"10",ratePercentage:"0.0000",taxAmount:"0",netTaxAmount:"0"})],taxAmount:"0",netTaxAmount:"0",lineTotal:"100"});expect(JSON.parse(prepareFacturaEnCrSubmission(fixture({lines:[zero]})).canonicalBody).detalle[0].impuesto[0]).toEqual({codigo:"01",codigoTarifa:"10",tarifa:0});});
  it.each([[[],"missing IVA"],[[tax({taxCode:"02"})],"invalid tax"],[[tax({rateCode:"98"})],"invalid tariff"],[[tax({rateCode:"08",ratePercentage:"0"})],"rate contradiction"]])("rejects %s",(taxes)=>expectCode(()=>prepareFacturaEnCrSubmission(fixture({lines:[line({taxes:taxes as ReturnType<typeof tax>[]})]})),"FACTURA_EN_CR_LINE_TAX_INVALID"));
  it("rejects duplicate line and tax order",()=>{expectCode(()=>prepareFacturaEnCrSubmission(fixture({lines:[line(),line()]})),"FACTURA_EN_CR_LINE_TAX_INVALID");expectCode(()=>prepareFacturaEnCrSubmission(fixture({lines:[line({taxes:[tax(),tax()]})]})),"FACTURA_EN_CR_LINE_TAX_INVALID");});

  it("validates exactly one allowed payment code",()=>{for(const code of ["01","02","03","04","05","06","07","99"])expect(JSON.parse(prepareFacturaEnCrSubmission(fixture({paymentMethods:[payment(code)]})).canonicalBody).medioPago).toEqual([code]);for(const code of ["00","08","98"])expectCode(()=>prepareFacturaEnCrSubmission(fixture({paymentMethods:[payment(code)]})),"FACTURA_EN_CR_PAYMENT_METHODS_UNSUPPORTED");expectCode(()=>prepareFacturaEnCrSubmission(fixture({paymentMethods:[]})),"FACTURA_EN_CR_PAYMENT_METHODS_UNSUPPORTED");expectCode(()=>prepareFacturaEnCrSubmission(fixture({paymentMethods:[payment("01"),{...payment("02"),paymentMethodOrder:2}]})),"FACTURA_EN_CR_PAYMENT_METHODS_UNSUPPORTED");});
  it("maps a classified exact discount and rejects incomplete/unsupported ones",()=>{const discounted=line({grossAmount:"100",discountAmount:"10.1200",discountCode:"07",discountReason:"Promo",taxableBase:"89.88",lineSubtotal:"89.88",taxes:[tax({taxableBase:"89.88",taxAmount:"11.6844",netTaxAmount:"11.6844"})],taxAmount:"11.6844",netTaxAmount:"11.6844",lineTotal:"101.5644"});expect(prepareFacturaEnCrSubmission(fixture({lines:[discounted]})).canonicalBody).toContain('"montoDescuento":10.12');for(const code of [null,"98","99"])expectCode(()=>prepareFacturaEnCrSubmission(fixture({lines:[{...discounted,discountCode:code}]})),"FACTURA_EN_CR_DISCOUNT_UNSUPPORTED");});

  it("maps an ordinary exemption with exact decimals",()=>{const exempt=exemptLine();const body=JSON.parse(prepareFacturaEnCrSubmission(fixture({lines:[exempt]})).canonicalBody);expect(body.detalle[0].impuesto[0].exoneracion).toEqual({tipoDocumento:"01",numeroDocumento:"AUTH-1",fechaEmision:"2026-01-10T00:00:00-06:00",nombreInstitucion:"01",porcentajeExoneracion:100,montoExoneracion:13});expect(prepareFacturaEnCrSubmission(fixture({lines:[exempt]})).canonicalBody).toContain('"montoExoneracion":13');});
  it("validates exemption required fields, dates, article/inciso and 99 cases",()=>{const e=exemption();for(const override of [{documentNumber:""},{issueDate:"2026-02-30"},{documentTypeCode:"99"},{issuingInstitutionCode:"99",otherInstitutionDescription:null},{documentTypeCode:"02",legalArticle:null,legalSection:null}])expectCode(()=>prepareFacturaEnCrSubmission(fixture({lines:[exemptLine({...e,...override})]})),"FACTURA_EN_CR_LINE_TAX_INVALID");const other=JSON.parse(prepareFacturaEnCrSubmission(fixture({lines:[exemptLine({...e,issuingInstitutionCode:"99",otherInstitutionDescription:"Otra"})]})).canonicalBody);expect(other.detalle[0].impuesto[0].exoneracion.nombreInstitucionOtros).toBe("Otra");});

  it("escapes JSON strings and prevents injection while remaining parseable",()=>{const description='quote" slash\\ control\n unicode é separators\u2028\u2029 ,"evil":1';const result=prepareFacturaEnCrSubmission(fixture({lines:[line({description})]}));const parsed=JSON.parse(result.canonicalBody);expect(parsed.detalle[0].detalle).toBe(description);expect(parsed.detalle[0]).not.toHaveProperty("evil");});
  it("fails safely for runtime undefined",()=>{const d=fixture();(d.receiver as unknown as Record<string,unknown>).name=undefined;expectCode(()=>prepareFacturaEnCrSubmission(d),"FACTURA_EN_CR_RECEIVER_INVALID");});
  it("is byte deterministic, hashes exact UTF-8, changes meaningfully, and returns exact idempotency",()=>{const a=prepareFacturaEnCrSubmission(fixture()),b=prepareFacturaEnCrSubmission(fixture()),changed=prepareFacturaEnCrSubmission(fixture({lines:[line({description:"Changed"})]}));expect(a.canonicalBody).toBe(b.canonicalBody);expect(a.requestHash).toBe(createHash("sha256").update(a.canonicalBody,"utf8").digest("hex"));expect(changed.requestHash).not.toBe(a.requestHash);expect(a.idempotencyKey).toBe("billing-document:document-a:electronic-issuance:v1");expectCode(()=>prepareFacturaEnCrSubmission(fixture({issuanceIdempotencyKey:"other"})),"FACTURA_EN_CR_SNAPSHOT_INCOMPLETE");});
  it("structurally excludes internal and provider-managed fields",()=>{const body=JSON.parse(prepareFacturaEnCrSubmission(fixture()).canonicalBody);for(const key of ["tenantId","id","environment","certificateId","clave","fiscalNumber","providerRequestHash","grossSubtotal","total","metadata"])expect(body).not.toHaveProperty(key);});
});

function fixture(o:Partial<FacturaEnCrSubmissionAggregate>={}):FacturaEnCrSubmissionAggregate{return{id:"document-a",tenantId:"tenant-a",documentTypeCode:"01",issuerIdentification:"3101000000",issuerEconomicActivityCode:"791100",issuerEstablishmentCode:"001",issuerTerminalCode:"00001",billingDocumentNumberSequenceId:"sequence-a",allocatedSequenceNumber:"42",fiscalNumber:"00100001010000000042",issuanceIdempotencyKey:"billing-document:document-a:electronic-issuance:v1",fiscalEmissionAt:new Date("2026-08-23T12:34:56.789Z"),fiscalIssueDate:"2026-08-23",currencyCode:"CRC",exchangeRate:null,officialExchangeRateObservation:null,paymentConditionCode:"01",creditTermDays:null,receiver:receiver(),paymentMethods:[payment("01")],lines:[line()],...o};}
function tiquete(o:Partial<FacturaEnCrSubmissionAggregate>={}){return fixture({documentTypeCode:"04",fiscalNumber:"00100001040000000042",...o});}
function usd(o:Partial<FacturaEnCrSubmissionAggregate>={}){return fixture({currencyCode:"USD",exchangeRate:"512.123456789012",officialExchangeRateObservation:official(),...o});}
function official(value="512.123456789012"){const identity={countryCode:"CR",foreignCurrencyCode:"USD",localCurrencyCode:"CRC",rateType:"REFERENCE_SELL" as const,effectiveDate:"2026-08-23",sourceAuthority:"BCCR",sourceIndicatorCode:"318"};return{id:"obs-a",...identity,value,requestIdentity:buildRequestIdentity(identity),responseHash:buildResponseHash(identity,value)};}
function receiver(){return{name:"Receiver",identificationType:"02",identification:"3101999999",economicActivityCode:null,email:null,phone:null,address:null};}
function payment(paymentMethodCode:string){return{paymentMethodOrder:1,paymentMethodCode,description:null,declaredAmount:null};}
function tax(o:Partial<FacturaEnCrTaxSnapshot>={}):FacturaEnCrTaxSnapshot{return{taxOrder:1,taxCode:"01",rateCode:"08",ratePercentage:"13.0000",taxableBase:"100.0000",taxAmount:"13.0000",calculationFactor:null,netTaxAmount:"13.0000",exemption:null,...o};}
function line(o:Partial<FacturaEnCrLineSnapshot>={}):FacturaEnCrLineSnapshot{return{lineNumber:1,cabysCode:"1234567890123",description:"Service",quantity:"1.0000",unitOfMeasureCode:"Sp",unitPrice:"100.0000",grossAmount:"100.0000",discountAmount:"0.0000",discountCode:null,discountReason:null,taxableBase:"100.0000",taxAmount:"13.0000",exoneratedTaxAmount:"0.0000",netTaxAmount:"13.0000",lineSubtotal:"100.0000",lineTotal:"113.0000",taxes:[tax()],...o};}
function exemption():NonNullable<FacturaEnCrTaxSnapshot["exemption"]>{return{documentTypeCode:"01",documentNumber:"AUTH-1",legalArticle:null,legalSection:null,issuingInstitutionCode:"01",issuingInstitutionName:"Hacienda",otherInstitutionDescription:null,issueDate:"2026-01-10",exemptedPercentage:"100.0000",exemptedAmount:"13.0000"};}
function exemptLine(e=exemption()){return line({exoneratedTaxAmount:"13",netTaxAmount:"0",lineTotal:"100",taxes:[tax({netTaxAmount:"0",exemption:e})]});}
function expectCode(fn:()=>unknown,code:string){try{fn();fail("expected error");}catch(error){expect(error).toBeInstanceOf(FacturaEnCrPreparationError);expect((error as FacturaEnCrPreparationError).code).toBe(code);expect((error as Error).message).toBe(code);}}
