import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import type { ConfigService } from "@nestjs/config";
import { FacturaEnCrElectronicSubmissionAdapter } from "./factura-en-cr-electronic-submission.adapter";
import { ElectronicDocumentSubmissionError, type PreparedElectronicDocumentSubmission } from "./electronic-document-submission.provider";

const CONSECUTIVE = "00100001010000000866";
const KEY = "50624072600310167816600100001010000000866142351111";
type MutablePrepared = { -readonly [K in Exclude<keyof PreparedElectronicDocumentSubmission,"metadata">]: PreparedElectronicDocumentSubmission[K] } & { metadata: { -readonly [K in keyof PreparedElectronicDocumentSubmission["metadata"]]: PreparedElectronicDocumentSubmission["metadata"][K] } };

describe("FacturaEnCrElectronicSubmissionAdapter", () => {
  afterEach(() => { jest.restoreAllMocks(); jest.useRealTimers(); });

  it("keeps the provider port free of FacturaEnCR prepared-type imports",()=>{const source=readFileSync(require.resolve("./electronic-document-submission.provider"),"utf8");expect(source).not.toMatch(/from\s+["'][^"']*factura-en-cr-submission["']/);expect(source).not.toContain("FacturaEnCrPreparedSubmission");});

  it.each([["01","/documents/factura"],["04","/documents/tiquete"]] as const)("POSTs exact %s prepared bytes to %s", async(type,endpoint)=>{
    const fetchMock=mockFetch(response(202,ack({consecutivo:consecutive(type),clave:keyFor(consecutive(type))})));
    const input=prepared(type,endpoint); await adapter().submitElectronicDocument(input);
    expect(fetchMock).toHaveBeenCalledTimes(1); const [url,init]=fetchMock.mock.calls[0] as unknown as [URL,RequestInit];
    expect(url.toString()).toBe(`https://api.facturaencr.com/v2/efactura${endpoint}`);expect(init.method).toBe("POST");expect(init.body).toBe(input.canonicalBody);
  });

  it("preserves hash, body, idempotency and exact safe headers without exposing metadata date",async()=>{const fetchMock=mockFetch(response(202,ack()));const input=prepared();await adapter().submitElectronicDocument(input);const init=fetchMock.mock.calls[0][1] as RequestInit;expect(init.body).toBe(input.canonicalBody);expect(init.headers).toEqual({"X-API-Key":"key","X-API-Secret":"secret","Content-Type":"application/json",Accept:"application/json","Idempotency-Key":input.idempotencyKey});expect(init.headers).not.toHaveProperty("Authorization");expect(JSON.stringify(init.headers)).not.toContain("tenant-a");expect(JSON.stringify(init.headers)).not.toContain(input.metadata.fiscalIssueDate);expect(String(init.body)).not.toContain("tenant-a");expect(String(init.body)).not.toContain(input.metadata.fiscalIssueDate);});
  it("rejects hash mismatch before configuration and fetch",async()=>{const get=jest.fn();const fetchMock=mockFetch(response(202,ack()));const input=prepared();input.requestHash="0".repeat(64);await expectError(new FacturaEnCrElectronicSubmissionAdapter({get} as unknown as ConfigService).submitElectronicDocument(input),"ELECTRONIC_SUBMISSION_LOCAL_REQUEST_INVALID");expect(get).not.toHaveBeenCalled();expect(fetchMock).not.toHaveBeenCalled();});
  it.each(["/documents/other","https://evil.test/documents/factura","/documents/factura?x=1","/documents/factura#x","/documents/../factura"])("rejects unsafe path %s before fetch",async endpoint=>{const fetchMock=mockFetch(response(202,ack()));await expectError(adapter().submitElectronicDocument(prepared("01",endpoint as never)),"ELECTRONIC_SUBMISSION_LOCAL_REQUEST_INVALID");expect(fetchMock).not.toHaveBeenCalled();});
  it("rejects endpoint/type and consecutive/type contradictions locally",async()=>{const fetchMock=mockFetch(response(202,ack()));await expectError(adapter().submitElectronicDocument(prepared("01","/documents/tiquete")),"ELECTRONIC_SUBMISSION_LOCAL_REQUEST_INVALID");const input=prepared();input.metadata.fiscalNumber="00100001040000000866";await expectError(adapter().submitElectronicDocument(input),"ELECTRONIC_SUBMISSION_LOCAL_REQUEST_INVALID");expect(fetchMock).not.toHaveBeenCalled();});
  it.each(["2026-02-29","2026-02-30","2026-7-24",""]) ("rejects non-canonical prepared issue date %s locally",async fiscalIssueDate=>{const fetchMock=mockFetch(response(202,ack()));const input=prepared();input.metadata.fiscalIssueDate=fiscalIssueDate;await expectError(adapter().submitElectronicDocument(input),"ELECTRONIC_SUBMISSION_LOCAL_REQUEST_INVALID");expect(fetchMock).not.toHaveBeenCalled();});

  it.each([{FACTURA_EN_CR_API_KEY:""},{FACTURA_EN_CR_API_SECRET:""},{FACTURA_EN_CR_BASE_URL:"http://api.test"},{FACTURA_EN_CR_BASE_URL:"not a url"},{FACTURA_EN_CR_BASE_URL:"https://user:pass@api.test"},{FACTURA_EN_CR_BASE_URL:"https://api.test?q=1"},{FACTURA_EN_CR_TIMEOUT_MS:"99"}])("rejects invalid configuration without fetch: %o",async invalid=>{const fetchMock=mockFetch(response(202,ack()));await expectError(adapter(invalid as unknown as Record<string,string>).submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_CONFIGURATION_MISSING");expect(fetchMock).not.toHaveBeenCalled();});
  it.each([{FACTURA_EN_CR_API_KEY:1},{FACTURA_EN_CR_API_SECRET:{}},{FACTURA_EN_CR_BASE_URL:true},{FACTURA_EN_CR_TIMEOUT_MS:5000}])("rejects non-string configuration without throwing native errors: %o",async invalid=>{const fetchMock=mockFetch(response(202,ack()));await expectError(adapter(invalid).submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_CONFIGURATION_MISSING","CONFIGURATION_FAILURE");expect(fetchMock).not.toHaveBeenCalled();});
  it("normalizes a trailing-slash base path without changing the fixed endpoint",async()=>{const fetchMock=mockFetch(response(202,ack()));await adapter({FACTURA_EN_CR_BASE_URL:"https://api.facturaencr.com/v2/efactura///"}).submitElectronicDocument(prepared());expect(String(fetchMock.mock.calls[0][0])).toBe("https://api.facturaencr.com/v2/efactura/documents/factura");});
  it("classifies timeout as unknown and aborts once without retry",async()=>{jest.useFakeTimers();const fetchMock=jest.spyOn(global,"fetch").mockImplementation((_url,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(Object.assign(new Error("secret detail"),{name:"AbortError"})))));const promise=adapter({FACTURA_EN_CR_TIMEOUT_MS:"100"}).submitElectronicDocument(prepared());jest.advanceTimersByTime(101);await expectError(promise,"ELECTRONIC_SUBMISSION_TIMEOUT","UNKNOWN_REQUIRES_RECONCILIATION");expect(fetchMock).toHaveBeenCalledTimes(1);});
  it("classifies network failure as unknown without leaking it or retrying",async()=>{const fetchMock=jest.spyOn(global,"fetch").mockRejectedValue(new Error("raw network secret"));const error=await capture(adapter().submitElectronicDocument(prepared()));expect(error.code).toBe("ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE");expect(error.outcome).toBe("UNKNOWN_REQUIRES_RECONCILIATION");expect(error.message).not.toContain("raw network");expect(fetchMock).toHaveBeenCalledTimes(1);});
  it("always clears its timeout on success and error paths",async()=>{const clear=jest.spyOn(global,"clearTimeout");mockFetch(response(202,ack()));await adapter().submitElectronicDocument(prepared());mockFetch(response(202,{...ack(),error:"contradiction"}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE");expect(clear).toHaveBeenCalledTimes(2);});

  it("normalizes the documented 202 acknowledgement",async()=>{mockFetch(response(202,ack()));const result=await adapter().submitElectronicDocument(prepared());expect(result).toEqual({classification:"ACKNOWLEDGED_PROVIDER_SUBMISSION",providerDocumentId:"provider-doc",haciendaKey:KEY,consecutive:CONSECUTIVE,status:{providerStatus:"queued",final:false,accepted:false,rejected:false},providerEnvironment:"sandbox",estimatedReadyAt:"2026-07-25T01:07:58.112Z",rejectionDetail:null});});
  it("normalizes immediate rejected Hacienda detail without truncation",async()=>{const detail="  -400, Código CABYS inválido\nDetalle  ";mockFetch(response(202,ack({status:"rejected",haciendaMessage:detail})));await expect(adapter().submitElectronicDocument(prepared())).resolves.toMatchObject({status:{providerStatus:"rejected",final:true,accepted:false,rejected:true},rejectionDetail:detail.trim()});});
  it.each([undefined,null])("accepts rejected acknowledgement with optional Hacienda detail %p",async haciendaMessage=>{const body=ack({status:"rejected",...(haciendaMessage===undefined?{}:{haciendaMessage})});mockFetch(response(202,body));await expect(adapter().submitElectronicDocument(prepared())).resolves.toMatchObject({rejectionDetail:null});});
  it("preserves Hacienda detail longer than 1,000 characters within the response budget",async()=>{const detail=`  ${"R".repeat(1500)}  `;mockFetch(response(202,ack({status:"rejected",haciendaMessage:detail})));const result=await adapter().submitElectronicDocument(prepared());expect(result.rejectionDetail).toBe(detail.trim());expect(result.rejectionDetail).toHaveLength(1500);});
  it.each(["   ",42,{message:"raw"},"bad\u0000detail","bad\u007fdetail"])("rejects malformed rejected Hacienda detail %p",async haciendaMessage=>{mockFetch(response(202,ack({status:"rejected",haciendaMessage})));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it.each(["queued","accepted"])("returns null detail for %s without a Hacienda message",async status=>{mockFetch(response(202,ack({status})));await expect(adapter().submitElectronicDocument(prepared())).resolves.toMatchObject({rejectionDetail:null});});
  it.each(["queued","accepted"])("rejects contradictory %s acknowledgement with Hacienda detail",async status=>{mockFetch(response(202,ack({status,haciendaMessage:"raw Hacienda detail"})));const error=await capture(adapter().submitElectronicDocument(prepared()));expect(error.code).toBe("ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE");expect(JSON.stringify(error)).not.toContain("raw Hacienda detail");});
  it.each([200,201,204])("treats undocumented successful HTTP %s as an unknown invalid acknowledgement",async status=>{mockFetch(status===204?new Response(null,{status}):response(status,ack()));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it.each([["accepted",true,true,false],["rejected",true,false,true],["future_status",false,false,false]] as const)("normalizes provider status %s",async(status,final,accepted,rejected)=>{mockFetch(response(202,ack({status})));const result=await adapter().submitElectronicDocument(prepared());expect(result.status).toEqual({providerStatus:status,final,accepted,rejected});});
  it.each(["Queued"," queued","queued ","queued/path","<html>","line\nbreak","a".repeat(65)])("rejects unsafe provider status %p",async status=>{mockFetch(response(202,ack({status})));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it("accepts absent estimated time and rejects invalid time",async()=>{mockFetch(response(202,ack({estimatedReadyAt:null})));await expect(adapter().submitElectronicDocument(prepared())).resolves.toMatchObject({estimatedReadyAt:null});mockFetch(response(202,ack({estimatedReadyAt:"2026-99-99"})));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it.each([{documentId:""},{clave:"1".repeat(49)},{consecutivo:"0".repeat(20)},{environment:"other"},{status:""}])("rejects invalid acknowledgement as unknown: %o",async override=>{mockFetch(response(202,ack(override)));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it("rejects a contradictory success acknowledgement containing error",async()=>{mockFetch(response(202,{...ack(),error:"provider_error"}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it("cross-checks returned consecutive, type, and key embedding",async()=>{for(const override of [{consecutivo:"00100001010000000867"},{consecutivo:"00100001040000000866"},{clave:"1".repeat(50)}]){mockFetch(response(202,ack(override)));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");}});
  it("binds Hacienda key DDMMAA to the persisted issue date, including leap days",async()=>{mockFetch(response(202,ack({clave:KEY.replace("240726","230726")})));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");const leap=prepared();leap.metadata.fiscalIssueDate="2024-02-29";mockFetch(response(202,ack({clave:KEY.replace("240726","290224")})));await expect(adapter().submitElectronicDocument(leap)).resolves.toMatchObject({haciendaKey:KEY.replace("240726","290224")});});
  it.each(["310226","290225"])("rejects impossible Hacienda key date %s as unknown",async keyDate=>{const input=prepared();input.metadata.fiscalIssueDate=keyDate==="290225"?"2025-02-28":"2026-02-28";mockFetch(response(202,ack({clave:KEY.replace("240726",keyDate)})));await expectError(adapter().submitElectronicDocument(input),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it.each([{clave:KEY.replace(/^506/,"507")},{clave:KEY.slice(0,41)+"4"+KEY.slice(42)}])("rejects invalid key country or situation",async override=>{mockFetch(response(202,ack(override)));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});

  it.each([[400,"ELECTRONIC_SUBMISSION_INVALID","DEFINITE_REJECTION"],[401,"ELECTRONIC_SUBMISSION_AUTHENTICATION_FAILED","CONFIGURATION_FAILURE"],[403,"ELECTRONIC_SUBMISSION_AUTHORIZATION_FAILED","CONFIGURATION_FAILURE"],[404,"ELECTRONIC_SUBMISSION_ISSUER_NOT_READY","DEFINITE_REJECTION"],[413,"ELECTRONIC_SUBMISSION_PAYLOAD_TOO_LARGE","DEFINITE_REJECTION"],[422,"ELECTRONIC_SUBMISSION_FISCAL_RULE_REJECTED","DEFINITE_REJECTION"],[500,"ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE","UNKNOWN_REQUIRES_RECONCILIATION"],[502,"ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE","UNKNOWN_REQUIRES_RECONCILIATION"],[503,"ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE","UNKNOWN_REQUIRES_RECONCILIATION"],[504,"ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE","UNKNOWN_REQUIRES_RECONCILIATION"]] as const)("maps HTTP %s safely",async(status,code,outcome)=>{mockFetch(response(status,{message:"raw customer data",details:["secret"]}));await expectError(adapter().submitElectronicDocument(prepared()),code,outcome);});
  it.each([["idempotency_conflict","ELECTRONIC_SUBMISSION_IDEMPOTENCY_CONFLICT","DEFINITE_REJECTION"],["other_conflict","ELECTRONIC_SUBMISSION_CONFLICT","DEFINITE_REJECTION"]] as const)("maps 409 %s",async(providerCode,code,outcome)=>{mockFetch(response(409,{error:providerCode,message:"raw"}));await expectError(adapter().submitElectronicDocument(prepared()),code,outcome);});
  it("maps in-progress with only bounded retry timing",async()=>{mockFetch(response(409,{error:"idempotency_in_progress",retryAfterSeconds:5,message:"raw"}));let error=await capture(adapter().submitElectronicDocument(prepared()));expect(error.code).toBe("ELECTRONIC_SUBMISSION_IDEMPOTENCY_IN_PROGRESS");expect(error.retryAfterSeconds).toBe(5);mockFetch(response(409,{error:"idempotency_in_progress",retryAfterSeconds:999999}));error=await capture(adapter().submitElectronicDocument(prepared()));expect(error.retryAfterSeconds).toBeNull();});
  it("maps rate limiting with bounded Retry-After",async()=>{mockFetch(response(429,{}, {"Retry-After":"30"}));let error=await capture(adapter().submitElectronicDocument(prepared()));expect(error.code).toBe("ELECTRONIC_SUBMISSION_RATE_LIMITED");expect(error.retryAfterSeconds).toBe(30);mockFetch(response(429,{}, {"Retry-After":"raw"}));error=await capture(adapter().submitElectronicDocument(prepared()));expect(error.retryAfterSeconds).toBeNull();});
  it.each(["", "not json", "[]", "true"])("rejects malformed successful body as unknown",async body=>{mockFetch(new Response(body,{status:202}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it("rejects oversized declared and streamed success bodies",async()=>{mockFetch(new Response("{}",{status:202,headers:{"Content-Length":String(65*1024)}}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");mockFetch(new Response("x".repeat(65*1024),{status:202}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it("accepts an acknowledgement body exactly at the 64 KiB limit",async()=>{const json=JSON.stringify(ack()),body=json+" ".repeat(64*1024-Buffer.byteLength(json));mockFetch(new Response(body,{status:202}));await expect(adapter().submitElectronicDocument(prepared())).resolves.toMatchObject({providerDocumentId:"provider-doc"});});
  it("rejects invalid UTF-8 success bytes as unknown",async()=>{mockFetch(new Response(new Uint8Array([0xc3,0x28]),{status:202}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION");});
  it("classifies malformed and oversized 409 bodies safely",async()=>{for(const body of ["not-json","x".repeat(65*1024)]){mockFetch(new Response(body,{status:409}));await expectError(adapter().submitElectronicDocument(prepared()),"ELECTRONIC_SUBMISSION_CONFLICT","DEFINITE_REJECTION");}});
  it("never exposes credentials, URL, body, headers, idempotency, key, or raw response in errors",async()=>{const input=prepared();mockFetch(response(400,{message:"raw-provider-message",details:[KEY]}));const error=await capture(adapter().submitElectronicDocument(input));const serialized=JSON.stringify({code:error.code,message:error.message,outcome:error.outcome});for(const secret of ["raw-provider-message",KEY,"secret","key","tenant-a","https://api.facturaencr.com",input.canonicalBody,input.idempotencyKey,"X-API-Key"])expect(serialized).not.toContain(secret);});
  it("performs no request at construction/import time",()=>{const fetchMock=mockFetch(response(202,ack()));adapter();expect(fetchMock).not.toHaveBeenCalled();});
});

function prepared(type:"01"|"04"="01",endpoint:"/documents/factura"|"/documents/tiquete"="/documents/factura"):MutablePrepared{const canonicalBody='{"safe":"exact"}',fiscalNumber=consecutive(type);return{endpoint,canonicalBody,requestHash:createHash("sha256").update(canonicalBody,"utf8").digest("hex"),idempotencyKey:"billing-document:document-a:electronic-issuance:v1",metadata:{billingDocumentId:"document-a",tenantId:"tenant-a",documentTypeCode:type,fiscalNumber,fiscalIssueDate:"2026-07-24"}};}
function consecutive(type:"01"|"04"){return `00100001${type}0000000866`;}
function keyFor(consecutiveValue:string){return `506240726003101678166${consecutiveValue}142351111`;}
function ack(o:Record<string,unknown>={}){return{documentId:"provider-doc",clave:KEY,consecutivo:CONSECUTIVE,status:"queued",environment:"sandbox",estimatedReadyAt:"2026-07-25T01:07:58.112Z",...o};}
function response(status:number,body:unknown,headers:Record<string,string>={}){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...headers}});}
function values(overrides:Record<string,unknown>={}){return{FACTURA_EN_CR_API_KEY:"key",FACTURA_EN_CR_API_SECRET:"secret",FACTURA_EN_CR_BASE_URL:"https://api.facturaencr.com/v2/efactura",FACTURA_EN_CR_TIMEOUT_MS:"5000",...overrides};}
function adapter(overrides:Record<string,unknown>={}){const config=values(overrides);return new FacturaEnCrElectronicSubmissionAdapter({get:jest.fn((key:string,fallback:string)=>config[key as keyof typeof config]??fallback)} as unknown as ConfigService);}
function mockFetch(value:Response){return jest.spyOn(global,"fetch").mockResolvedValue(value);}
async function capture(promise:Promise<unknown>){try{await promise;throw new Error("expected error");}catch(error){expect(error).toBeInstanceOf(ElectronicDocumentSubmissionError);return error as ElectronicDocumentSubmissionError;}}
async function expectError(promise:Promise<unknown>,code:string,outcome?:string){const error=await capture(promise);expect(error.code).toBe(code);if(outcome)expect(error.outcome).toBe(outcome);expect(error.message).not.toBe(code);}
