import type { ConfigService } from "@nestjs/config";import { ElectronicDocumentRefreshError,type ElectronicDocumentRefreshInput } from "./electronic-document-refresh.provider";import { FacturaEnCrDocumentRefreshAdapter } from "./factura-en-cr-document-refresh.adapter";
const ID="6a640c68a06e822633e9db71",CONSECUTIVE="00100001010000000866",KEY="50624072600310167816600100001010000000866142351111";
describe("FacturaEnCrDocumentRefreshAdapter",()=>{afterEach(()=>{jest.restoreAllMocks();jest.useRealTimers();});
  it("sends exactly one bodyless POST to the fixed refresh path",async()=>{const fetch=mockFetch(response(200,ack()));await adapter().refreshElectronicDocumentStatus(input());expect(fetch).toHaveBeenCalledTimes(1);const[url,init]=fetch.mock.calls[0] as unknown as[URL,RequestInit];expect(url.toString()).toBe(`https://api.facturaencr.com/v2/efactura/documents/${ID}/refresh`);expect(init).toMatchObject({method:"POST",headers:{"X-API-Key":"key","X-API-Secret":"secret",Accept:"application/json"}});expect(init.body).toBeUndefined();expect(init.headers).not.toHaveProperty("Content-Type");expect(init.headers).not.toHaveProperty("Authorization");});
  it("normalizes the documented refresh acknowledgement without inventing a fiscal decision",async()=>{mockFetch(response(200,ack()));await expect(adapter().refreshElectronicDocumentStatus(input())).resolves.toEqual({classification:"ELECTRONIC_DOCUMENT_REFRESH_ACKNOWLEDGED",providerDocumentId:ID,previousStatus:"polling",currentStatus:"accepted",haciendaCheckedAt:"2026-07-25T01:09:14.322Z"});});
  it.each(["","../x","x/y","x%2Fy","x?q=1","x#f","https://evil.test"," x","x\n","a".repeat(256)])("rejects unsafe ID %p before configuration or fetch",async providerDocumentId=>{const get=jest.fn(),fetch=mockFetch(response(200,ack()));await expectCode(new FacturaEnCrDocumentRefreshAdapter({get} as unknown as ConfigService).refreshElectronicDocumentStatus(input({providerDocumentId})),"ELECTRONIC_DOCUMENT_REFRESH_LOCAL_REQUEST_INVALID");expect(get).not.toHaveBeenCalled();expect(fetch).not.toHaveBeenCalled();});
  it.each([{FACTURA_EN_CR_API_KEY:1},{FACTURA_EN_CR_API_SECRET:""},{FACTURA_EN_CR_TIMEOUT_MS:"99"},{FACTURA_EN_CR_TIMEOUT_MS:"30001"},{FACTURA_EN_CR_BASE_URL:"http://api.test"},{FACTURA_EN_CR_BASE_URL:"https://u:p@api.test"}])("rejects unsafe configuration: %o",async override=>{const fetch=mockFetch(response(200,ack()));await expectCode(adapter(override).refreshElectronicDocumentStatus(input()),"ELECTRONIC_DOCUMENT_REFRESH_CONFIGURATION_MISSING");expect(fetch).not.toHaveBeenCalled();});
  it.each([[401,"AUTHENTICATION_FAILED"],[403,"AUTHORIZATION_FAILED"],[404,"NOT_FOUND"],[409,"CONFLICT"],[400,"REJECTED"],[422,"REJECTED"],[500,"PROVIDER_UNAVAILABLE"],[502,"PROVIDER_UNAVAILABLE"],[503,"PROVIDER_UNAVAILABLE"],[504,"PROVIDER_UNAVAILABLE"]] as const)("maps HTTP %i safely",async(status,suffix)=>{mockFetch(response(status,{error:"provider secret"}));await expectCode(adapter().refreshElectronicDocumentStatus(input()),`ELECTRONIC_DOCUMENT_REFRESH_${suffix}`);});
  it("maps bounded Retry-After for 429",async()=>{mockFetch(response(429,{error:"refresh_throttled"},{"retry-after":"43"}));const error=await capture(adapter().refreshElectronicDocumentStatus(input()));expect(error).toMatchObject({code:"ELECTRONIC_DOCUMENT_REFRESH_RATE_LIMITED",retryAfterSeconds:43});});
  it.each([201,202,204])("rejects unexpected successful HTTP %i",async status=>{mockFetch(response(status,ack()));await expectCode(adapter().refreshElectronicDocumentStatus(input()),"ELECTRONIC_DOCUMENT_REFRESH_INVALID_PROVIDER_RESPONSE");});
  it.each([{},[],"text",null,{...ack(),id:"other"},{...ack(),currentStatus:"Accepted"},{...ack(),haciendaCheckedAt:"2026-02-30T00:00:00Z"},{...ack(),extra:true}])("rejects malformed or contradictory success %p",async value=>{mockFetch(response(200,value));await expectCode(adapter().refreshElectronicDocumentStatus(input()),"ELECTRONIC_DOCUMENT_REFRESH_INVALID_PROVIDER_RESPONSE");});
  it("rejects declared and streamed bodies over 64 KiB",async()=>{mockFetch(response(200,ack(),{"content-length":"65537"}));await expectCode(adapter().refreshElectronicDocumentStatus(input()),"ELECTRONIC_DOCUMENT_REFRESH_INVALID_PROVIDER_RESPONSE");mockFetch(response(200,"x".repeat(65537)));await expectCode(adapter().refreshElectronicDocumentStatus(input()),"ELECTRONIC_DOCUMENT_REFRESH_INVALID_PROVIDER_RESPONSE");});
  it("maps timeout without retry and clears its timer",async()=>{jest.useFakeTimers();const clear=jest.spyOn(global,"clearTimeout"),fetch=jest.spyOn(global,"fetch").mockImplementation((_u,init)=>new Promise((_r,reject)=>init?.signal?.addEventListener("abort",()=>reject(Object.assign(new Error("secret"),{name:"AbortError"})))));const pending=adapter({FACTURA_EN_CR_TIMEOUT_MS:"100"}).refreshElectronicDocumentStatus(input()),assertion=expectCode(pending,"ELECTRONIC_DOCUMENT_REFRESH_TIMEOUT");await jest.advanceTimersByTimeAsync(101);await assertion;expect(fetch).toHaveBeenCalledTimes(1);expect(clear).toHaveBeenCalledTimes(1);});
  it("maps a network failure safely without retry",async()=>{const fetch=jest.spyOn(global,"fetch").mockRejectedValue(new Error("credential secret"));await expectCode(adapter().refreshElectronicDocumentStatus(input()),"ELECTRONIC_DOCUMENT_REFRESH_PROVIDER_UNAVAILABLE");expect(fetch).toHaveBeenCalledTimes(1);});
});
function input(overrides:Record<string,unknown>={}):ElectronicDocumentRefreshInput{return{providerDocumentId:ID,expectedHaciendaKey:KEY,expectedConsecutive:CONSECUTIVE,expectedProviderEnvironment:"sandbox",expectedFiscalIssueDate:"2026-07-24",expectedDocumentType:"01",...overrides} as ElectronicDocumentRefreshInput;}function ack(){return{id:ID,previousStatus:"polling",currentStatus:"accepted",haciendaCheckedAt:"2026-07-25T01:09:14.322Z"};}
function adapter(overrides:Record<string,unknown>={}){const values={FACTURA_EN_CR_API_KEY:"key",FACTURA_EN_CR_API_SECRET:"secret",FACTURA_EN_CR_BASE_URL:"https://api.facturaencr.com/v2/efactura",FACTURA_EN_CR_TIMEOUT_MS:"5000",...overrides};return new FacturaEnCrDocumentRefreshAdapter({get:jest.fn((key:string,fallback:unknown)=>key in values?values[key as keyof typeof values]:fallback)} as unknown as ConfigService);}function response(status:number,value:unknown,headers:Record<string,string>={}){const text=typeof value==="string"?value:JSON.stringify(value);return new Response(status===204?null:text,{status,headers:{"content-type":"application/json",...headers}});}function mockFetch(value:Response){return jest.spyOn(global,"fetch").mockResolvedValue(value);}async function capture(p:Promise<unknown>){try{await p;throw new Error("expected");}catch(error){return error as ElectronicDocumentRefreshError;}}async function expectCode(p:Promise<unknown>,code:string){const error=await capture(p);expect(error).toBeInstanceOf(ElectronicDocumentRefreshError);expect(error.code).toBe(code);expect(JSON.stringify(error)).not.toMatch(/provider secret|credential secret|6a640c68|506240726/);}
