export const OPERATIONS_SOURCE_ITEM_APPROVED_EVENT = "SOURCE_ITEM_APPROVED";
export const ADDITIONAL_SERVICE_ORDER_LINE_SOURCE = "ADDITIONAL_SERVICE_ORDER_LINE";
export const TRAVEL_PACKAGE_COST_COMPONENT_SOURCE = "TRAVEL_PACKAGE_COST_COMPONENT";
export const CUSTOM_QUOTATION_LINE_SOURCE = "CUSTOM_QUOTATION_LINE";

export const OPERATIONS_INTAKE_OUTBOX_POLL_INTERVAL_MS = 5_000;
export const OPERATIONS_INTAKE_OUTBOX_BATCH_SIZE = 10;
export const OPERATIONS_INTAKE_OUTBOX_TENANT_BATCH_SIZE = 25;
export const OPERATIONS_INTAKE_OUTBOX_PROCESSING_LEASE_MS = 60_000;
export const OPERATIONS_INTAKE_OUTBOX_RETRY_BASE_MS = 60_000;
export const OPERATIONS_INTAKE_OUTBOX_RETRY_MAX_MS = 60 * 60_000;
