'use client';

import { useEffect, useState } from 'react';
import { AlertCircle, Download, Mail, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { downloadCustomerAccountStatement, formatFinanceMoney, getCustomerAccountStatement, sendCustomerAccountStatement, type AccountReceivableGroup, type CustomerAccountStatement } from '@/lib/finance-api';
import { formatBusinessDate } from '@/shared/regional';
import styles from './accounts-receivable.module.css';

const AR_LABEL = { OPEN: 'Abierta', PARTIALLY_SETTLED: 'Abonada', SETTLED: 'Cancelada', CANCELLED: 'Anulada' } as const;
const PAYMENT_LABEL = { RECEIVED: 'Recibido', PARTIALLY_ALLOCATED: 'Aplicado parcialmente', FULLY_ALLOCATED: 'Aplicado por completo', CANCELLED: 'Anulado' } as const;

export function CustomerAccountStatementModal({ group, canSend, onClose }: { group: AccountReceivableGroup; canSend: boolean; onClose: () => void }) {
  const [statement, setStatement] = useState<CustomerAccountStatement | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [to, setTo] = useState(''); const [cc, setCc] = useState(''); const [downloading, setDownloading] = useState(false); const [sending, setSending] = useState(false); const [sent, setSent] = useState<string | null>(null);
  useEffect(() => { if (!group.customerId) return; const controller = new AbortController(); setLoading(true); getCustomerAccountStatement(group.customerId, group.currencyCode, controller.signal).then((value) => { setStatement(value); setTo(value.customer.email ?? ''); }).catch((requestError) => { if (!controller.signal.aborted) setError(requestError instanceof Error ? requestError.message : 'No se pudo cargar el estado de cuenta.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [group.currencyCode, group.customerId]);
  async function download() { if (!group.customerId) return; setDownloading(true); setError(null); try { const result = await downloadCustomerAccountStatement(group.customerId, group.currencyCode); const url = URL.createObjectURL(result.blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = result.fileName; anchor.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo descargar el PDF.'); } finally { setDownloading(false); } }
  async function send() { if (!group.customerId || !to.trim()) { setError('Indique el correo destinatario.'); return; } setSending(true); setError(null); setSent(null); try { const result = await sendCustomerAccountStatement(group.customerId, { currencyCode: group.currencyCode, to: to.trim(), ...(cc.trim() ? { cc: cc.trim() } : {}) }); setSent(`Estado de cuenta enviado a ${result.sentTo}.`); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'No se pudo enviar el estado de cuenta.'); } finally { setSending(false); } }
  return <><button className={styles.paymentBackdrop} type="button" aria-label="Cerrar estado de cuenta" onClick={onClose} /><section className={`${styles.paymentModal} ${styles.statementModal}`} role="dialog" aria-modal="true" aria-labelledby="statement-title"><header className={styles.paymentModalHeader}><div><p>Finanzas · cartera del cliente</p><h2 id="statement-title">Estado de cuenta — {group.debtor.displayName}</h2></div><Button className={styles.closeButton} size="icon" variant="ghost" type="button" aria-label="Cerrar" onClick={onClose}><X aria-hidden="true" /></Button></header><div className={styles.paymentModalBody}>
    {loading ? <div className={styles.childLoading}>Cargando facturas y pagos desde Finanzas…</div> : error && !statement ? <div className={styles.paymentError}><AlertCircle aria-hidden="true" /><span>{error}</span></div> : statement && <><section className={styles.statementSummary}><article><span>Total facturado</span><strong>{formatFinanceMoney(statement.totals.invoicedAmount, statement.currencyCode)}</strong></article><article><span>Pagos aplicados</span><strong>{formatFinanceMoney(statement.totals.allocatedAmount, statement.currencyCode)}</strong></article><article><span>Saldo pendiente</span><strong className={styles.pendingAmount}>{formatFinanceMoney(statement.totals.outstandingAmount, statement.currencyCode)}</strong></article><article><span>Saldo disponible</span><strong className={styles.availableAmount}>{formatFinanceMoney(statement.totals.availableAmount, statement.currencyCode)}</strong></article></section>
      <section className={styles.statementSection}><h3>Facturas que componen el total</h3><div className={styles.statementTableWrap}><table><thead><tr><th>Factura</th><th>Emisión</th><th>Vencimiento</th><th>Estado</th><th>Original</th><th>Aplicado</th><th>Pendiente</th></tr></thead><tbody>{statement.invoices.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.number}</strong><small>{invoice.documentType ?? 'Cuenta por cobrar'}</small>{invoice.allocations.map((allocation, index) => <small key={`${allocation.receiptNumber}-${index}`}>{allocation.receiptNumber} · {formatFinanceMoney(allocation.amount, statement.currencyCode)} · {allocation.statusLabel}</small>)}</td><td>{formatBusinessDate(invoice.recognizedAt)}</td><td>{formatBusinessDate(invoice.dueDate)}</td><td>{AR_LABEL[invoice.status]}</td><td>{formatFinanceMoney(invoice.originalAmount, statement.currencyCode)}</td><td>{formatFinanceMoney(invoice.allocatedAmount, statement.currencyCode)}</td><td className={styles.pendingAmount}>{formatFinanceMoney(invoice.outstandingAmount, statement.currencyCode)}</td></tr>)}</tbody></table></div></section>
      <section className={styles.statementSection}><h3>Pagos y facturas asignadas</h3><div className={styles.statementTableWrap}><table><thead><tr><th>Recibo</th><th>Fecha</th><th>Método</th><th>Estado</th><th>Asignaciones</th><th>Recibido</th><th>Disponible</th></tr></thead><tbody>{statement.payments.map((payment) => <tr key={payment.id}><td><strong>{payment.receiptNumber}</strong></td><td>{formatBusinessDate(payment.receivedAt)}</td><td>{payment.paymentMethodLabel}</td><td>{PAYMENT_LABEL[payment.status]}</td><td>{payment.allocations.length ? payment.allocations.map((allocation, index) => <small key={`${allocation.invoiceNumber}-${index}`}>{allocation.invoiceNumber} · {formatFinanceMoney(allocation.amount, statement.currencyCode)} · {allocation.statusLabel}</small>) : 'Sin asignaciones'}</td><td>{formatFinanceMoney(payment.receivedAmount, statement.currencyCode)}</td><td className={styles.availableAmount}>{formatFinanceMoney(payment.availableAmount, statement.currencyCode)}</td></tr>)}</tbody></table></div></section>
      {error && <div className={styles.paymentError}><AlertCircle aria-hidden="true" /><span>{error}</span></div>}{sent && <div className={styles.paymentSuccess}><Mail aria-hidden="true" /><strong>{sent}</strong></div>}
      {canSend && <section className={styles.statementEmail}><div className={styles.field}><label htmlFor="statement-to">Enviar a</label><input id="statement-to" className={styles.input} type="email" value={to} onChange={(event) => setTo(event.target.value)} placeholder="cliente@correo.com" /></div><div className={styles.field}><label htmlFor="statement-cc">CC (opcional)</label><input id="statement-cc" className={styles.input} type="email" value={cc} onChange={(event) => setCc(event.target.value)} placeholder="copia@correo.com" /></div></section>}
      <div className={styles.paymentActions}><Button className={styles.secondaryAction} variant="outline" type="button" onClick={onClose}>Cerrar</Button><Button className={styles.secondaryAction} disabled={downloading} variant="outline" type="button" onClick={() => void download()}><Download aria-hidden="true" />{downloading ? 'Generando…' : 'Descargar PDF'}</Button>{canSend && <Button className={styles.primaryAction} disabled={sending || !to.trim()} type="button" onClick={() => void send()}><Mail aria-hidden="true" />{sending ? 'Enviando…' : 'Enviar por correo'}</Button>}</div>
    </>}
  </div></section></>;
}
