import { Injectable } from "@nestjs/common";
import { AccountReceivableStatus, CustomerFundsAllocationCommandStatus, PaymentStatus, Prisma } from "@prisma/client";
import { createHash } from "crypto";
import { PrismaService } from "../prisma/prisma.service";
import { applyLockedPaymentAllocations, type LockedPaymentAllocationFragment, PAYMENT_ALLOCATION_ERRORS } from "./payment-allocation.service";
import type { FinanceActor } from "./finance-audit";

export const CUSTOMER_FUNDS_ERRORS={INVALID:"CUSTOMER_FUNDS_ALLOCATION_INVALID",CUSTOMER_REQUIRED:"CUSTOMER_FUNDS_ALLOCATION_CUSTOMER_REQUIRED",TARGET_INVALID:"CUSTOMER_FUNDS_ALLOCATION_TARGET_INVALID",DUPLICATE_TARGET:"CUSTOMER_FUNDS_ALLOCATION_DUPLICATE_TARGET",INSUFFICIENT:"CUSTOMER_FUNDS_ALLOCATION_INSUFFICIENT",IDEMPOTENCY_CONFLICT:"CUSTOMER_FUNDS_ALLOCATION_IDEMPOTENCY_CONFLICT"} as const;
type Target={accountReceivableId:string;amount:Prisma.Decimal}; type Input={tenantId:string;actor:FinanceActor;customerId:string;currencyCode:string;targets:readonly Target[];deduplicationKey?:string};
class CustomerFundsError extends Error{constructor(readonly code:string){super(code)}}
@Injectable() export class CustomerFundsAllocationService { constructor(private readonly prisma:PrismaService){}
 async preview(input:Input){const x=normalize(input,false);const [payments,ars]=await Promise.all([this.prisma.payment.findMany({where:{tenantId:x.tenantId,customerId:x.customerId,currencyCode:x.currencyCode,status:{in:[PaymentStatus.RECEIVED,PaymentStatus.PARTIALLY_ALLOCATED]},availableAmount:{gt:0}},orderBy:[{receivedAt:"asc"},{id:"asc"}]}),this.prisma.accountReceivable.findMany({where:{tenantId:x.tenantId,id:{in:x.targets.map(t=>t.accountReceivableId)}}})]);validateTargets(ars,x);return result(x,payments,ars,plan(payments,ars,x.targets));}
 async commit(input:Input){const x=normalize(input,true);const hash=requestHash(x);try{return await this.prisma.$transaction(async tx=>{
  const existing=await tx.customerFundsAllocationCommand.findUnique({where:{tenantId_deduplicationKey:{tenantId:x.tenantId,deduplicationKey:x.deduplicationKey!}}});if(existing){if(existing.requestHash!==hash)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.IDEMPOTENCY_CONFLICT);if(existing.status===CustomerFundsAllocationCommandStatus.COMMITTED&&existing.resultSnapshot)return existing.resultSnapshot;}
  const command=existing??await tx.customerFundsAllocationCommand.create({data:{tenantId:x.tenantId,customerId:x.customerId,currencyCode:x.currencyCode,deduplicationKey:x.deduplicationKey!,requestHash:hash,requestedByUserId:x.actor.userId}});
  const paymentLocks=await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "payments" WHERE "tenantId"=${x.tenantId} AND "customerId"=${x.customerId} AND "currencyCode"=${x.currencyCode} AND "status" IN ('RECEIVED','PARTIALLY_ALLOCATED') AND "availableAmount">0 ORDER BY "receivedAt" ASC,"id" ASC FOR UPDATE`;
  const payments=await tx.payment.findMany({where:{tenantId:x.tenantId,id:{in:paymentLocks.map(p=>p.id)}},orderBy:[{receivedAt:"asc"},{id:"asc"}]});const ids=[...x.targets.map(t=>t.accountReceivableId)].sort();const arLocks=await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "account_receivables" WHERE "tenantId"=${x.tenantId} AND "id" IN (${Prisma.join(ids)}) ORDER BY "id" ASC FOR UPDATE`;if(arLocks.length!==ids.length)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.TARGET_INVALID);const ars=await tx.accountReceivable.findMany({where:{tenantId:x.tenantId,id:{in:ids}}});validateTargets(ars,x);const fragments=plan(payments,ars,x.targets);const keyedFragments=fragments.map((f,i)=>({...f,allocationDeduplicationKey:childKey(command.id,i,f)}));const persisted=await applyLockedPaymentAllocations(tx,x.tenantId,x.actor,payments,ars,keyedFragments);const snapshot=result({...x,commandId:command.id},payments,ars,keyedFragments,persisted);await tx.customerFundsAllocationCommand.update({where:{id:command.id},data:{status:CustomerFundsAllocationCommandStatus.COMMITTED,resultSnapshot:snapshot as Prisma.InputJsonValue,committedAt:new Date()}});return snapshot;
 });}catch(e){if((e as {code?:string})?.code==="P2002"){const winner=await this.prisma.customerFundsAllocationCommand.findUnique({where:{tenantId_deduplicationKey:{tenantId:x.tenantId,deduplicationKey:x.deduplicationKey!}}});if(winner){if(winner.requestHash!==hash)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.IDEMPOTENCY_CONFLICT);if(winner.status===CustomerFundsAllocationCommandStatus.COMMITTED&&winner.resultSnapshot)return winner.resultSnapshot;}}if(e instanceof CustomerFundsError||e instanceof Error&&Object.values(PAYMENT_ALLOCATION_ERRORS).includes(e.message as never))throw e;throw e;}}
}
function normalize(i:Input,commit:boolean){const customerId=text(i.customerId),currencyCode=text(i.currencyCode).toUpperCase();if(!customerId)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.CUSTOMER_REQUIRED);if(!/^[A-Z]{3}$/.test(currencyCode)||!Array.isArray(i.targets)||i.targets.length<1||i.targets.length>25)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.INVALID);const seen=new Set<string>();const targets=i.targets.map(t=>{const accountReceivableId=text(t.accountReceivableId);if(!accountReceivableId||seen.has(accountReceivableId))throw new CustomerFundsError(seen.has(accountReceivableId)?CUSTOMER_FUNDS_ERRORS.DUPLICATE_TARGET:CUSTOMER_FUNDS_ERRORS.INVALID);seen.add(accountReceivableId);if(!(t.amount instanceof Prisma.Decimal)||!t.amount.isFinite()||t.amount.isNegative()||t.amount.isZero()||t.amount.decimalPlaces()>5)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.INVALID);return{accountReceivableId,amount:t.amount}});const deduplicationKey=commit?text(i.deduplicationKey):undefined;if(commit&&!deduplicationKey)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.INVALID);return{...i,customerId,currencyCode,targets,deduplicationKey};}
function validateTargets(ars:any[],x:any){if(ars.length!==x.targets.length)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.TARGET_INVALID);const by=new Map(ars.map(a=>[a.id,a]));for(const t of x.targets){const a=by.get(t.accountReceivableId);if(!a||a.customerId!==x.customerId||a.currencyCode!==x.currencyCode||![AccountReceivableStatus.OPEN,AccountReceivableStatus.PARTIALLY_SETTLED].includes(a.status)||a.outstandingAmount.lte(0)||t.amount.greaterThan(a.outstandingAmount))throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.TARGET_INVALID);}}
function plan(payments:any[],ars:any[],targets:Target[]):LockedPaymentAllocationFragment[]{const available=payments.map(p=>({p,left:new Prisma.Decimal(p.availableAmount)}));let pi=0;const out:LockedPaymentAllocationFragment[]=[];for(const t of targets){let left=t.amount;while(left.gt(0)){const funding=available[pi];if(!funding)throw new CustomerFundsError(CUSTOMER_FUNDS_ERRORS.INSUFFICIENT);const amount=Prisma.Decimal.min(left,funding.left);out.push({paymentId:funding.p.id,accountReceivableId:t.accountReceivableId,amount,allocationDeduplicationKey:""});left=left.minus(amount);funding.left=funding.left.minus(amount);if(funding.left.isZero())pi++;}}return out;}
function result(x:any,payments:any[],ars:any[],fragments:LockedPaymentAllocationFragment[],persisted?:any[]){const total=fragments.reduce((v,f)=>v.plus(f.amount),new Prisma.Decimal(0));const available=payments.reduce((v,p)=>v.plus(p.availableAmount),new Prisma.Decimal(0));const byAr=new Map<string,Prisma.Decimal>();for(const f of fragments)byAr.set(f.accountReceivableId,(byAr.get(f.accountReceivableId)??new Prisma.Decimal(0)).plus(f.amount));const byKey=new Map((persisted??[]).map(p=>[p.allocationDeduplicationKey,p]));return{customerId:x.customerId,currencyCode:x.currencyCode,totalAvailableAmount:available.toFixed(),totalRequestedAmount:total.toFixed(),remainingAvailableAmount:available.minus(total).toFixed(),targets:x.targets.map((t:Target)=>{const a=ars.find(a=>a.id===t.accountReceivableId);const outstanding=a.outstandingAmount.minus(byAr.get(a.id)!);return{accountReceivableId:a.id,requestedAmount:t.amount.toFixed(),currentOutstandingAmount:a.outstandingAmount.toFixed(),projectedOutstandingAmount:outstanding.toFixed(),resultingStatus:outstanding.isZero()?"SETTLED":"PARTIALLY_SETTLED"}}),fundingBreakdown:fragments.map((f,i)=>({paymentId:f.paymentId,receiptNumber:payments.find(p=>p.id===f.paymentId).receiptNumber,accountReceivableId:f.accountReceivableId,amount:f.amount.toFixed(),paymentAllocationId:byKey.get(f.allocationDeduplicationKey)?.id})),commandId:x.commandId};}
function requestHash(x:any){return createHash("sha256").update(JSON.stringify({customerId:x.customerId,currencyCode:x.currencyCode,targets:x.targets.map((t:Target)=>[t.accountReceivableId,t.amount.toFixed()])})).digest("hex")}function childKey(id:string,n:number,f:LockedPaymentAllocationFragment){return createHash("sha256").update(`${id}:${n}:${f.paymentId}:${f.accountReceivableId}:${f.amount.toFixed()}`).digest("hex")}function text(x:unknown){return typeof x==="string"?x.trim():""}
