import { AccountReceivableStatus, CustomerFundsAllocationCommandStatus, PaymentStatus, Prisma } from "@prisma/client";
import { CustomerFundsAllocationService, CUSTOMER_FUNDS_ERRORS } from "./customer-funds-allocation.service";

const d=(v:string)=>new Prisma.Decimal(v);
const actor={userId:"user-a",name:"Finance User"};
const input=(targets=[{accountReceivableId:"ar-a",amount:d("10")}],key="key-a")=>({tenantId:"tenant-a",actor,customerId:"customer-a",currencyCode:"crc",deduplicationKey:key,targets});
describe("CustomerFundsAllocationService",()=>{
 it("plans exact FIFO fragments and commits normal allocation/audit/state records",async()=>{const c=context({payments:[payment("a","20.04",new Date("2026-01-01")),payment("b","12.27",new Date("2026-01-02")),payment("c","50.00",new Date("2026-01-03"))],ars:[ar("ar-a","40")]});const r:any=await c.service.commit(input([{accountReceivableId:"ar-a",amount:d("40")}])) ;expect(r.fundingBreakdown.map((x:any)=>[x.paymentId,x.amount])).toEqual([["a","20.04"],["b","12.27"],["c","7.69"]]);expect(c.db.payments.map((p:any)=>p.availableAmount.toFixed())).toEqual(["0","0","42.31"]);expect(c.db.payments.map((p:any)=>p.status)).toEqual([PaymentStatus.FULLY_ALLOCATED,PaymentStatus.FULLY_ALLOCATED,PaymentStatus.PARTIALLY_ALLOCATED]);expect(c.db.ars[0].outstandingAmount.toFixed()).toBe("0");expect(c.db.allocations).toHaveLength(3);expect(c.db.audits).toHaveLength(3);expect(c.db.commands[0]).toMatchObject({status:CustomerFundsAllocationCommandStatus.COMMITTED});expect(r.fundingBreakdown.every((x:any)=>x.paymentAllocationId)).toBe(true);});
 it("consumes targets in request order across FIFO payments",async()=>{const c=context({payments:[payment("a","7",new Date("2026-01-01")),payment("b","10",new Date("2026-01-02"))],ars:[ar("ar-a","10"),ar("ar-b","10")]});const r:any=await c.service.commit(input([{accountReceivableId:"ar-b",amount:d("5")},{accountReceivableId:"ar-a",amount:d("8")}])) ;expect(r.fundingBreakdown.map((x:any)=>[x.paymentId,x.accountReceivableId,x.amount])).toEqual([["a","ar-b","5"],["a","ar-a","2"],["b","ar-a","6"]]);});
 it("uses id as FIFO tie-breaker",async()=>{const c=context({payments:[payment("z","5",new Date("2026-01-01")),payment("a","5",new Date("2026-01-01"))],ars:[ar("ar-a","10")]});const r:any=await c.service.preview(input([{accountReceivableId:"ar-a",amount:d("10")}])) ;expect(r.fundingBreakdown.map((x:any)=>x.paymentId)).toEqual(["a","z"]);});
 it("preview is read-only and has the same fragments as commit",async()=>{const c=context({payments:[payment("a","6",new Date()),payment("b","5",new Date())],ars:[ar("ar-a","10")]});const before=JSON.stringify(state(c.db));const preview:any=await c.service.preview(input([{accountReceivableId:"ar-a",amount:d("10")}])) ;expect(JSON.stringify(state(c.db))).toBe(before);expect(c.db.commands).toHaveLength(0);const committed:any=await c.service.commit(input([{accountReceivableId:"ar-a",amount:d("10")}])) ;expect(committed.fundingBreakdown.map((x:any)=>[x.paymentId,x.amount])).toEqual(preview.fundingBreakdown.map((x:any)=>[x.paymentId,x.amount]));});
 it("replays the stored committed snapshot without new money movement",async()=>{const c=context();const first:any=await c.service.commit(input());c.db.payments[0].availableAmount=d("999");const replay:any=await c.service.commit(input());expect(replay).toEqual(first);expect(c.db.allocations).toHaveLength(1);expect(c.db.audits).toHaveLength(1);});
 it("rejects an idempotency key reused with different canonical intent",async()=>{const c=context();await c.service.commit(input());await expect(c.service.commit(input([{accountReceivableId:"ar-a",amount:d("9")}]))).rejects.toThrow(CUSTOMER_FUNDS_ERRORS.IDEMPOTENCY_CONFLICT);});
 it.each([
  ["insufficient funds",{payments:[payment("a","5")],ars:[ar("ar-a","10")]},input(),CUSTOMER_FUNDS_ERRORS.INSUFFICIENT],
  ["over outstanding",{},input([{accountReceivableId:"ar-a",amount:d("11")}]),CUSTOMER_FUNDS_ERRORS.TARGET_INVALID],
  ["other customer",{ars:[ar("ar-a","10",{customerId:"customer-b"})]},input(),CUSTOMER_FUNDS_ERRORS.TARGET_INVALID],
  ["other currency",{ars:[ar("ar-a","10",{currencyCode:"USD"})]},input(),CUSTOMER_FUNDS_ERRORS.TARGET_INVALID],
  ["settled AR",{ars:[ar("ar-a","10",{status:AccountReceivableStatus.SETTLED,outstandingAmount:d("0")})]},input(),CUSTOMER_FUNDS_ERRORS.TARGET_INVALID],
  ["cancelled AR",{ars:[ar("ar-a","10",{status:AccountReceivableStatus.CANCELLED})]},input(),CUSTOMER_FUNDS_ERRORS.TARGET_INVALID],
 ])("rejects %s without financial writes",async(_,setup,command,code)=>{const c=context(setup as any),before=JSON.stringify(state(c.db));await expect(c.service.commit(command as any)).rejects.toThrow(code as string);expect(JSON.stringify(state(c.db))).toBe(before);});
 it("rejects null customer and duplicate targets before writes",async()=>{const c=context();await expect(c.service.commit({...input(),customerId:""})).rejects.toThrow(CUSTOMER_FUNDS_ERRORS.CUSTOMER_REQUIRED);await expect(c.service.commit(input([{accountReceivableId:"ar-a",amount:d("1")},{accountReceivableId:"ar-a",amount:d("1")}]))).rejects.toThrow(CUSTOMER_FUNDS_ERRORS.DUPLICATE_TARGET);expect(c.db.allocations).toHaveLength(0);});
 it("excludes cancelled, fully allocated and zero-available payments",async()=>{const c=context({payments:[payment("bad-1","50",undefined,{status:PaymentStatus.CANCELLED}),payment("bad-2","0",undefined,{status:PaymentStatus.FULLY_ALLOCATED,availableAmount:d("0")}),payment("bad-3","0"),payment("good","10")]});const r:any=await c.service.preview(input());expect(r.fundingBreakdown.map((x:any)=>x.paymentId)).toEqual(["good"]);});
 it("rolls back all command and financial state when an allocation update fails",async()=>{const c=context({failArUpdate:true}),before=JSON.stringify(state(c.db));await expect(c.service.commit(input())).rejects.toThrow("FAIL_AR_UPDATE");expect(JSON.stringify(state(c.db))).toBe(before);});
 it("creates ordinary ACTIVE allocations suitable for individual reversal",async()=>{const c=context();await c.service.commit(input());expect(c.db.allocations[0]).toMatchObject({paymentId:"payment-a",accountReceivableId:"ar-a",status:"ACTIVE",allocationDeduplicationKey:expect.any(String)});});
});
function payment(id:string,available:string="10",receivedAt=new Date("2026-01-01"),extra:any={}){return{id,tenantId:"tenant-a",customerId:"customer-a",currencyCode:"CRC",receivedAmount:d(available==="0"?"10":available),availableAmount:d(available),status:PaymentStatus.RECEIVED,receivedAt,receiptNumber:`RCP-${id}`,...extra}}
function ar(id:string,outstanding:string="10",extra:any={}){return{id,tenantId:"tenant-a",customerId:"customer-a",currencyCode:"CRC",originalAmount:d(outstanding),outstandingAmount:d(outstanding),status:AccountReceivableStatus.OPEN,...extra}}
function state(db:any){return{payments:db.payments.map((p:any)=>({...p,availableAmount:p.availableAmount.toFixed()})),ars:db.ars.map((a:any)=>({...a,outstandingAmount:a.outstandingAmount.toFixed()})),allocations:db.allocations,audits:db.audits,commands:db.commands}}
function context(o:any={}){const db={payments:o.payments??[payment("payment-a")],ars:o.ars??[ar("ar-a")],allocations:[] as any[],audits:[] as any[],commands:[] as any[]};let allocationId=0;const tx:any={
 $queryRaw:jest.fn(async(strings:any)=>{const sql=String(strings);if(sql.includes('"payments"'))return db.payments.filter((p:any)=>p.customerId==="customer-a"&&p.currencyCode==="CRC"&&[PaymentStatus.RECEIVED,PaymentStatus.PARTIALLY_ALLOCATED].includes(p.status)&&p.availableAmount.gt(0)).sort((a:any,b:any)=>a.receivedAt-b.receivedAt||a.id.localeCompare(b.id)).map((p:any)=>({id:p.id}));if(sql.includes('"account_receivables"'))return db.ars.map((a:any)=>({id:a.id}));if(sql.includes('"payment_allocations"'))return db.allocations.map((a:any)=>({id:a.id}));return[]}),
 payment:{findMany:jest.fn(async(a:any)=>db.payments.filter((p:any)=>{if(a.where.id&&!a.where.id.in.includes(p.id))return false;if(a.where.status&&!a.where.status.in.includes(p.status))return false;if(a.where.availableAmount&&!p.availableAmount.gt(0))return false;return true}).sort((x:any,y:any)=>x.receivedAt-y.receivedAt||x.id.localeCompare(y.id))),update:jest.fn(async({where,data}:any)=>Object.assign(db.payments.find((p:any)=>p.id===where.id),data))},
 accountReceivable:{findMany:jest.fn(async(a:any)=>db.ars.filter((r:any)=>!a.where.id||a.where.id.in.includes(r.id))),update:jest.fn(async({where,data}:any)=>{if(o.failArUpdate)throw new Error("FAIL_AR_UPDATE");return Object.assign(db.ars.find((r:any)=>r.id===where.id),data)})},
 paymentAllocation:{createMany:jest.fn(async({data}:any)=>{for(const x of data)if(!db.allocations.some(a=>a.allocationDeduplicationKey===x.allocationDeduplicationKey))db.allocations.push({...x,id:`alloc-${++allocationId}`})}),findMany:jest.fn(async({where}:any)=>db.allocations.filter(a=>where.allocationDeduplicationKey.in.includes(a.allocationDeduplicationKey)))},
 billingAuditLog:{createMany:jest.fn(async({data}:any)=>db.audits.push(...data))},customerFundsAllocationCommand:{findUnique:jest.fn(async({where}:any)=>db.commands.find(c=>c.tenantId===where.tenantId_deduplicationKey.tenantId&&c.deduplicationKey===where.tenantId_deduplicationKey.deduplicationKey)??null),create:jest.fn(async({data}:any)=>{const c={...data,id:`command-${db.commands.length+1}`,status:CustomerFundsAllocationCommandStatus.PENDING,resultSnapshot:null};db.commands.push(c);return c}),update:jest.fn(async({where,data}:any)=>Object.assign(db.commands.find(c=>c.id===where.id),data))}
 };const prisma:any={...tx,$transaction:async(fn:any)=>{const snapshot=JSON.parse(JSON.stringify(state(db)));try{return await fn(tx)}catch(e){db.payments.forEach((p:any,i:number)=>Object.assign(p,{...snapshot.payments[i],availableAmount:d(snapshot.payments[i].availableAmount)}));db.ars.forEach((a:any,i:number)=>Object.assign(a,{...snapshot.ars[i],outstandingAmount:d(snapshot.ars[i].outstandingAmount)}));db.allocations.splice(0,db.allocations.length,...snapshot.allocations);db.audits.splice(0,db.audits.length,...snapshot.audits);db.commands.splice(0,db.commands.length,...snapshot.commands);throw e}}};return{db,service:new CustomerFundsAllocationService(prisma)}}
