import { Prisma } from "@prisma/client";
import { PaymentReceiptService } from "./payment-receipt.service";

describe("PaymentReceiptService", () => {
  const payment = { findFirst: jest.fn() }; const client = { findFirst: jest.fn() }; const billingAuditLog = { findFirst: jest.fn(), create: jest.fn() }; const tenantBillingConfiguration = { findUnique: jest.fn() }; const renderDocumentToBuffer = jest.fn(); const sendEmail = jest.fn(); const getTenantConfig = jest.fn();
  const service = new PaymentReceiptService({ payment, client, billingAuditLog, tenantBillingConfiguration } as never, { renderDocumentToBuffer } as never, { sendEmail } as never, { getTenantConfig } as never);
  beforeEach(() => { jest.clearAllMocks(); payment.findFirst.mockResolvedValue({ id: "payment-1", customerId: "customer-1", receiptNumber: "RCP-2026-000015", payerDisplayName: "Nombre guardado", payerIdentificationNumber: "snapshot-id", currencyCode: "USD", receivedAmount: new Prisma.Decimal("100.125"), availableAmount: new Prisma.Decimal("60"), receivedAt: new Date("2026-09-01T01:30:00.000Z"), paymentMethod: "BANK_TRANSFER", externalReference: "REF-123", description: "Nota", status: "PARTIALLY_ALLOCATED", allocations: [{ id: "allocation-1", amount: new Prisma.Decimal("40.125"), status: "ACTIVE", allocatedAt: new Date("2026-09-01T01:30:00.000Z"), accountReceivable: { sourceNumber: "FE-1", sourceId: "ar-1" } }, { id: "allocation-2", amount: new Prisma.Decimal("10"), status: "REVERSED", allocatedAt: new Date("2026-09-01T01:30:00.000Z"), accountReceivable: { sourceNumber: null, sourceId: "ar-2" } }] }); client.findFirst.mockResolvedValue({ fullName: "Cliente actual", idNumber: "3101999999", email: "cliente@example.com" }); billingAuditLog.findFirst.mockResolvedValue({ actorName: "Agente" }); tenantBillingConfiguration.findUnique.mockResolvedValue({ fiscalTimezone: "America/Costa_Rica" }); getTenantConfig.mockResolvedValue({ name: "Agencia", logoUrl: null, contactEmail: "info@example.com", contactPhone: "2222", primaryColor: "#123456", secondaryColor: null }); renderDocumentToBuffer.mockResolvedValue({ pdfBuffer: Buffer.from("pdf") }); sendEmail.mockResolvedValue({ success: true, emailId: "email-1" }); billingAuditLog.create.mockResolvedValue({}); });
  it("reads only the tenant payment and returns exact current receipt data", async () => { const result = await service.get("tenant-1", "payment-1"); expect(payment.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { id: "payment-1", tenantId: "tenant-1" } })); expect(result).toMatchObject({ receiptNumber: "RCP-2026-000015", customer: { name: "Cliente actual", identification: "3101999999" }, receivedAmount: "100.125", appliedAmount: "40.125", availableAmount: "60.00", paymentMethodLabel: "Transferencia bancaria" }); expect(result.allocations).toEqual(expect.arrayContaining([expect.objectContaining({ sourceNumber: "FE-1", statusLabel: "Aplicado" }), expect.objectContaining({ sourceNumber: "ar-2", statusLabel: "Revertido" })])); });
  it("renders and sends the shared PDF attachment, recording the send audit", async () => { const result = await service.send("tenant-1", { userId: "user-1", email: "agent@example.com", fullName: "Agente" }, "payment-1"); expect(renderDocumentToBuffer).toHaveBeenCalledWith(expect.stringContaining("RCP-2026-000015")); expect(sendEmail).toHaveBeenCalledWith(expect.objectContaining({ to: "cliente@example.com", template: "business-document-attachment", attachments: [expect.objectContaining({ filename: "recibo-RCP-2026-000015.pdf", contentType: "application/pdf" })] })); expect(billingAuditLog.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ entityId: "payment-1", action: "RECEIPT_SENT", actorName: "Agente" }) })); expect(result).toMatchObject({ ok: true, sentTo: "cliente@example.com", emailId: "email-1" }); });
});
