import { Injectable } from "@nestjs/common";
import { AccountReceivableStatus, PaymentAllocationStatus, PaymentStatus, Prisma } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { FINANCE_AUDIT_ACTIONS, FINANCE_AUDIT_ENTITY_TYPES, financeAuditRecord, financeMoney, type FinanceActor } from "./finance-audit";
const MAX = new Prisma.Decimal("99999999999999.99999"), LIMIT = 25;
export const PAYMENT_ALLOCATION_ERRORS = { INVALID:"PAYMENT_ALLOCATION_INVALID", PAYMENT_INVALID:"PAYMENT_ALLOCATION_PAYMENT_INVALID", RECEIVABLE_INVALID:"PAYMENT_ALLOCATION_RECEIVABLE_INVALID", CURRENCY_MISMATCH:"PAYMENT_ALLOCATION_CURRENCY_MISMATCH", CUSTOMER_MISMATCH:"PAYMENT_ALLOCATION_CUSTOMER_MISMATCH", PAYMENT_INSUFFICIENT:"PAYMENT_ALLOCATION_PAYMENT_INSUFFICIENT", RECEIVABLE_INSUFFICIENT:"PAYMENT_ALLOCATION_RECEIVABLE_INSUFFICIENT", CONFLICT:"PAYMENT_ALLOCATION_CONFLICT", PERSISTENCE_FAILED:"PAYMENT_ALLOCATION_PERSISTENCE_FAILED" } as const;
export interface PaymentAllocationCommand { tenantId:string; actor:FinanceActor; paymentId:string; allocations:ReadonlyArray<{accountReceivableId:string;amount:Prisma.Decimal;allocationDeduplicationKey:string}> }
export interface LockedPaymentAllocationFragment { paymentId:string; accountReceivableId:string; amount:Prisma.Decimal; allocationDeduplicationKey:string }
class PaymentAllocationError extends Error { constructor(readonly code:(typeof PAYMENT_ALLOCATION_ERRORS)[keyof typeof PAYMENT_ALLOCATION_ERRORS]) { super(code); } }
@Injectable() export class PaymentAllocationService {
 constructor(private readonly prisma:PrismaService) {}
 async allocate(command:PaymentAllocationCommand):Promise<void> { const input=normalize(command); try { await this.prisma.$transaction(async tx=>{
  const pl=await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "payments" WHERE "id"=${input.paymentId} AND "tenantId"=${input.tenantId} FOR UPDATE`; if(pl.length!==1)fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID);
  const payment=await tx.payment.findFirst({where:{id:input.paymentId,tenantId:input.tenantId}}); if(!payment)fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID);
  const ids=[...new Set(input.allocations.map(x=>x.accountReceivableId))].sort(); const al=await tx.$queryRaw<Array<{id:string}>>`SELECT "id" FROM "account_receivables" WHERE "tenantId"=${input.tenantId} AND "id" IN (${Prisma.join(ids)}) ORDER BY "id" ASC FOR UPDATE`; if(al.length!==ids.length)fail(PAYMENT_ALLOCATION_ERRORS.RECEIVABLE_INVALID);
  const ars=await tx.accountReceivable.findMany({where:{tenantId:input.tenantId,id:{in:ids}}}); if(ars.length!==ids.length)fail(PAYMENT_ALLOCATION_ERRORS.RECEIVABLE_INVALID);
  await applyLockedPaymentAllocations(tx,input.tenantId,input.actor,[payment],ars,input.allocations.map(x=>({...x,paymentId:input.paymentId})));
 }); } catch(e) { if(e instanceof PaymentAllocationError)throw e; throw new PaymentAllocationError(PAYMENT_ALLOCATION_ERRORS.PERSISTENCE_FAILED); } }
}
/** Shared mutation primitive. Callers acquire Payment then AR locks before entry. */
type LockedPaymentAllocationPayment = {
 id:string;customerId:string|null;currencyCode:string;receivedAmount:Prisma.Decimal;availableAmount:Prisma.Decimal;status:PaymentStatus;
 settlementCurrencyCode?:string|null;settlementAmount?:Prisma.Decimal|null;settlementAvailableAmount?:Prisma.Decimal|null;settlementExchangeRate?:Prisma.Decimal|null;
};

export async function applyLockedPaymentAllocations(tx:Prisma.TransactionClient,tenantId:string,actor:FinanceActor,payments:ReadonlyArray<LockedPaymentAllocationPayment>,ars:ReadonlyArray<{id:string;customerId:string|null;currencyCode:string;originalAmount:Prisma.Decimal;outstandingAmount:Prisma.Decimal;status:AccountReceivableStatus}>,fragments:ReadonlyArray<LockedPaymentAllocationFragment>) {
 const ps=new Map(payments.map(x=>[x.id,x])), rs=new Map(ars.map(x=>[x.id,x])); const old=await lockedExisting(tx,tenantId,fragments.map(x=>x.allocationDeduplicationKey)), oldBy=new Map(old.map(x=>[x.allocationDeduplicationKey,x])); const fresh:LockedPaymentAllocationFragment[]=[];
 for(const x of fragments){const w=oldBy.get(x.allocationDeduplicationKey);if(w){if(!winner(w,x))fail(PAYMENT_ALLOCATION_ERRORS.CONFLICT)}else fresh.push(x)} if(!fresh.length)return old;
 const pt=new Map<string,Prisma.Decimal>(),rt=new Map<string,Prisma.Decimal>(),pools=new Map<string,PaymentAllocationPool>(); for(const x of fresh){const p=ps.get(x.paymentId),r=rs.get(x.accountReceivableId);if(!p||p.status===PaymentStatus.CANCELLED||p.status===PaymentStatus.FULLY_ALLOCATED)fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID);if(!r||r.status===AccountReceivableStatus.CANCELLED||r.status===AccountReceivableStatus.SETTLED)fail(PAYMENT_ALLOCATION_ERRORS.RECEIVABLE_INVALID);validPayment(p);validAr(r);const pool=pools.get(p.id)??allocationPool(p);pools.set(p.id,pool);if(pool.currencyCode!==r.currencyCode)fail(PAYMENT_ALLOCATION_ERRORS.CURRENCY_MISMATCH);if(!hasCompatibleAllocationCustomer(p.customerId,r.customerId))fail(PAYMENT_ALLOCATION_ERRORS.CUSTOMER_MISMATCH);pt.set(p.id,(pt.get(p.id)??new Prisma.Decimal(0)).plus(x.amount));rt.set(r.id,(rt.get(r.id)??new Prisma.Decimal(0)).plus(x.amount));}
 for(const [id,total] of pt)if(total.greaterThan(pools.get(id)!.availableAmount))fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INSUFFICIENT);for(const [id,total] of rt)if(total.greaterThan(rs.get(id)!.outstandingAmount))fail(PAYMENT_ALLOCATION_ERRORS.RECEIVABLE_INSUFFICIENT);
 const now=new Date();await tx.paymentAllocation.createMany({data:fresh.map(x=>({tenantId,paymentId:x.paymentId,accountReceivableId:x.accountReceivableId,allocationDeduplicationKey:x.allocationDeduplicationKey,amount:x.amount,status:PaymentAllocationStatus.ACTIVE,allocatedAt:now})),skipDuplicates:true});const persisted=await lockedExisting(tx,tenantId,fresh.map(x=>x.allocationDeduplicationKey));if(persisted.length!==fresh.length||!fresh.every(x=>{const p=persisted.find(y=>y.allocationDeduplicationKey===x.allocationDeduplicationKey);return p&&winner(p,x)}))fail(PAYMENT_ALLOCATION_ERRORS.CONFLICT);const persistedBy=new Map(persisted.map(x=>[x.allocationDeduplicationKey,x]));
 await tx.billingAuditLog.createMany({ data: fresh.map(x => {
  const p=ps.get(x.paymentId)!, r=rs.get(x.accountReceivableId)!;
  return financeAuditRecord({ tenantId, entityType:FINANCE_AUDIT_ENTITY_TYPES.ALLOCATION, entityId:persistedBy.get(x.allocationDeduplicationKey)!.id, action:FINANCE_AUDIT_ACTIONS.APPLIED, actor, occurredAt:now,
   beforeJson:{paymentId:p.id,accountReceivableId:r.id,paymentAvailableAmount:financeMoney(p.availableAmount),paymentSettlementAvailableAmount:p.settlementAvailableAmount?financeMoney(p.settlementAvailableAmount):null,accountReceivableOutstandingAmount:financeMoney(r.outstandingAmount)},
   afterJson:{paymentId:p.id,accountReceivableId:r.id,amount:financeMoney(x.amount),paymentAvailableAmount:financeMoney(remainingPhysicalAmount(p,pools.get(p.id)!,pt.get(p.id)!)),paymentSettlementAvailableAmount:pools.get(p.id)!.usesSettlement?financeMoney(pools.get(p.id)!.availableAmount.minus(pt.get(p.id)!)):null,accountReceivableOutstandingAmount:financeMoney(r.outstandingAmount.minus(rt.get(r.id)!))}
  });
 }) });
 for(const [id,total]of pt){const p=ps.get(id)!,pool=pools.get(id)!,settlementAvailableAmount=pool.availableAmount.minus(total),availableAmount=remainingPhysicalAmount(p,pool,total);await tx.payment.update({where:{id},data:{availableAmount,status:settlementAvailableAmount.isZero()?PaymentStatus.FULLY_ALLOCATED:PaymentStatus.PARTIALLY_ALLOCATED,...(pool.usesSettlement?{settlementAvailableAmount}: {})} as never})}for(const [id,total]of rt){const r=rs.get(id)!,outstandingAmount=r.outstandingAmount.minus(total);await tx.accountReceivable.update({where:{id},data:{outstandingAmount,status:outstandingAmount.isZero()?AccountReceivableStatus.SETTLED:AccountReceivableStatus.PARTIALLY_SETTLED,settledAt:outstandingAmount.isZero()?now:null}})} return persisted;
}
type PaymentAllocationPool={currencyCode:string;availableAmount:Prisma.Decimal;usesSettlement:boolean};
function allocationPool(payment:LockedPaymentAllocationPayment):PaymentAllocationPool{const currencyCode=payment.settlementCurrencyCode?.toUpperCase();if(!currencyCode)return{currencyCode:payment.currencyCode,availableAmount:payment.availableAmount,usesSettlement:false};const settlementAmount=payment.settlementAmount,availableAmount=payment.settlementAvailableAmount;if(!(settlementAmount instanceof Prisma.Decimal)||!(availableAmount instanceof Prisma.Decimal)||!positive(settlementAmount)||!nonNegative(availableAmount)||availableAmount.greaterThan(settlementAmount))fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID);if(currencyCode!==payment.currencyCode){const rate=payment.settlementExchangeRate;if(!(rate instanceof Prisma.Decimal)||!positive(rate))fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID)}return{currencyCode,availableAmount,usesSettlement:true}}
function remainingPhysicalAmount(payment:LockedPaymentAllocationPayment,pool:PaymentAllocationPool,allocatedSettlementAmount:Prisma.Decimal):Prisma.Decimal{if(!pool.usesSettlement||pool.currencyCode===payment.currencyCode)return payment.availableAmount.minus(allocatedSettlementAmount);const remainingSettlement=pool.availableAmount.minus(allocatedSettlementAmount);if(remainingSettlement.isZero())return new Prisma.Decimal(0);const rate=payment.settlementExchangeRate!;const spent=payment.currencyCode==="CRC"&&pool.currencyCode==="USD"?allocatedSettlementAmount.times(rate):payment.currencyCode==="USD"&&pool.currencyCode==="CRC"?allocatedSettlementAmount.dividedBy(rate):null;if(!spent)fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID);const remaining=payment.availableAmount.minus(spent.toDecimalPlaces(5,Prisma.Decimal.ROUND_HALF_UP));if(remaining.isNegative())fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INSUFFICIENT);return remaining.toDecimalPlaces(5,Prisma.Decimal.ROUND_HALF_UP)}
function normalize(c:PaymentAllocationCommand){const tenantId=req(c.tenantId,191),actor={userId:req(c.actor?.userId,191),name:req(c.actor?.name,500)},paymentId=req(c.paymentId,191);if(!Array.isArray(c.allocations)||c.allocations.length<1||c.allocations.length>LIMIT)fail(PAYMENT_ALLOCATION_ERRORS.INVALID);const a=new Set<string>(),k=new Set<string>();const allocations=c.allocations.map(x=>{if(!x||typeof x!=="object")fail(PAYMENT_ALLOCATION_ERRORS.INVALID);const accountReceivableId=req(x.accountReceivableId,191),allocationDeduplicationKey=req(x.allocationDeduplicationKey,200);if(a.has(accountReceivableId)||k.has(allocationDeduplicationKey))fail(PAYMENT_ALLOCATION_ERRORS.INVALID);a.add(accountReceivableId);k.add(allocationDeduplicationKey);return{accountReceivableId,allocationDeduplicationKey,amount:exact(x.amount)}});return{tenantId,actor,paymentId,allocations}}
async function lockedExisting(tx:Prisma.TransactionClient,tenantId:string,keys:readonly string[]):Promise<Array<{id:string;paymentId:string;accountReceivableId:string;amount:Prisma.Decimal;allocationDeduplicationKey:string}>>{if(!keys.length)return[];await tx.$queryRaw`SELECT "id" FROM "payment_allocations" WHERE "tenantId"=${tenantId} AND "allocationDeduplicationKey" IN (${Prisma.join([...keys])}) ORDER BY "allocationDeduplicationKey" ASC FOR UPDATE`;return tx.paymentAllocation.findMany({where:{tenantId,allocationDeduplicationKey:{in:[...keys]}}})}function winner(w:{paymentId:string;accountReceivableId:string;amount:Prisma.Decimal},x:LockedPaymentAllocationFragment){return w.paymentId===x.paymentId&&w.accountReceivableId===x.accountReceivableId&&w.amount.equals(x.amount)}function validPayment(x:{receivedAmount:Prisma.Decimal;availableAmount:Prisma.Decimal}){if(!positive(x.receivedAmount)||!nonNegative(x.availableAmount)||x.availableAmount.greaterThan(x.receivedAmount))fail(PAYMENT_ALLOCATION_ERRORS.PAYMENT_INVALID)}function validAr(x:{originalAmount:Prisma.Decimal;outstandingAmount:Prisma.Decimal}){if(!positive(x.originalAmount)||!nonNegative(x.outstandingAmount)||x.outstandingAmount.greaterThan(x.originalAmount))fail(PAYMENT_ALLOCATION_ERRORS.RECEIVABLE_INVALID)}export function hasCompatibleAllocationCustomer(a:string|null,b:string|null){return a===null||b===null||a===b}function exact(x:unknown):Prisma.Decimal{if(!positive(x))fail(PAYMENT_ALLOCATION_ERRORS.INVALID);return x}function positive(x:unknown):x is Prisma.Decimal{return nonNegative(x)&&!x.isZero()}function nonNegative(x:unknown):x is Prisma.Decimal{return x instanceof Prisma.Decimal&&x.isFinite()&&!x.isNegative()&&x.decimalPlaces()<=5&&x.lessThanOrEqualTo(MAX)}function req(x:unknown,max:number):string{if(typeof x!=="string")fail(PAYMENT_ALLOCATION_ERRORS.INVALID);const value=x.trim();if(!value||value.length>max)fail(PAYMENT_ALLOCATION_ERRORS.INVALID);return value}function fail(code:(typeof PAYMENT_ALLOCATION_ERRORS)[keyof typeof PAYMENT_ALLOCATION_ERRORS]):never{throw new PaymentAllocationError(code)}
