'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, RefreshCw } from 'lucide-react';
import { ConfirmModal } from '@/components/confirm-modal';
import { LoadingSpinner } from '@/components/loading-spinner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { getHomeRouteForRole, getStoredSession } from '@/lib/auth-api';
import { FiscalBillingApiError, getBillingDocumentWorkspace, requestBillingDocumentElectronicIssuance, type BillingDocumentWorkspace } from '@/lib/fiscal-billing-api';
import { formatFiscalDecimal, formatFiscalMoney } from '@/lib/fiscal-money';
import styles from '../../fiscal-billing.module.css';

const INTERVAL=5_000, WINDOW=600_000, MAX_ERRORS=3;
const lifecycle:Record<string,string>={DRAFT:'Borrador',CONFIRMED:'Confirmado',SUBMITTED:'Enviado'};
const provider:Record<string,string>={NOT_SUBMITTED:'No enviado',PENDING:'Pendiente de envío',PROCESSED:'Procesado por el proveedor',FAILED:'Falló el envío'};
const hacienda:Record<string,string>={NOT_SUBMITTED:'No enviado a Hacienda',PROCESSING:'En procesamiento',ACCEPTED:'Aceptado',REJECTED:'Rechazado'};
const payments:Record<string,string>={'01':'Efectivo','02':'Tarjeta','03':'Cheque','04':'Transferencia/depósito bancario','05':'Recaudado por terceros','06':'SINPE Móvil','07':'Plataforma digital','99':'Otros'};
function validId(v:string){return v.length>0&&v.length<=200&&v.trim()===v&&/^[A-Za-z0-9_-]+$/.test(v);}
const decimal = formatFiscalDecimal;
const money = formatFiscalMoney;
function time(v:string|null){if(!v)return 'No disponible';const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('es-CR',{dateStyle:'medium',timeStyle:'medium',timeZone:'America/Costa_Rica'}).format(d):'No disponible';}
function date(v:string|null){return v&&/^\d{4}-\d{2}-\d{2}$/.test(v)?v:'No disponible';}
function badge(v:string){return v==='ACCEPTED'?styles.readyBadge:v==='REJECTED'||v==='FAILED'?styles.errorBadge:v==='PENDING'||v==='PROCESSING'?styles.warningBadge:styles.documentTypeBadge;}
function terminal(w:BillingDocumentWorkspace){return w.taxAuthorityStatus==='ACCEPTED'||w.taxAuthorityStatus==='REJECTED'||w.providerStatus==='FAILED';}
function active(w:BillingDocumentWorkspace){return Boolean(w.fiscalNumber)&&!terminal(w)&&w.lifecycleStatus!=='DRAFT'&&(w.providerStatus==='PENDING'||w.taxAuthorityStatus==='PROCESSING'||w.lifecycleStatus==='CONFIRMED'||w.lifecycleStatus==='SUBMITTED');}
function eligible(w:BillingDocumentWorkspace){return w.lifecycleStatus==='DRAFT'&&w.providerStatus==='NOT_SUBMITTED'&&w.taxAuthorityStatus==='NOT_SUBMITTED'&&w.fiscalNumber===null&&w.allocatedSequenceNumber===null&&w.providerDocumentId===null&&!w.readiness.receiverFiscalIdentityMissing&&!w.readiness.exchangeRateMissing;}
function technical(code:string){const m:Record<string,string>={ELECTRONIC_SUBMISSION_CONFIGURATION_INVALID:'La configuración del proveedor fiscal no está disponible.',ELECTRONIC_SUBMISSION_AUTHENTICATION_FAILED:'La autenticación con el proveedor fiscal falló.',ELECTRONIC_SUBMISSION_AUTHORIZATION_FAILED:'La cuenta no está autorizada para emitir.',ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE:'El proveedor fiscal no está disponible.',ELECTRONIC_SUBMISSION_TIMEOUT:'El proveedor fiscal no respondió a tiempo.',ELECTRONIC_SUBMISSION_RATE_LIMITED:'El proveedor fiscal limitó temporalmente las solicitudes.'};return m[code]??'No fue posible completar la comunicación fiscal.';}

export default function Page(){
  const {billingDocumentId:id}=useParams<{billingDocumentId:string}>(),router=useRouter(),routeValid=validId(id);
  const [authorized,setAuthorized]=useState(false),[workspace,setWorkspace]=useState<BillingDocumentWorkspace|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState<FiscalBillingApiError|null>(null);
  const [confirming,setConfirming]=useState(false),[issuing,setIssuing]=useState(false),[refreshing,setRefreshing]=useState(false),[operationError,setOperationError]=useState<FiscalBillingApiError|null>(null),[success,setSuccess]=useState<string|null>(null),[monitorNotice,setMonitorNotice]=useState<string|null>(null),[monitorStopped,setMonitorStopped]=useState(false);
  const issuingRef=useRef(false),inflight=useRef<Promise<BillingDocumentWorkspace|null>|null>(null),generation=useRef(0),deadline=useRef(0),pollErrors=useRef(0);
  useEffect(()=>{const s=getStoredSession();if(!s?.user?.id){router.replace('/');return;}const r=String(s.user.role??'').toUpperCase();if(r!=='ADMIN'&&r!=='FACTURACION_COBROS'){router.replace(getHomeRouteForRole(r));return;}queueMicrotask(()=>setAuthorized(true));},[router]);
  const refresh=useCallback((manual:boolean)=>{if(!routeValid||inflight.current)return inflight.current??Promise.resolve(null);const g=generation.current;if(manual)setRefreshing(true);const p=getBillingDocumentWorkspace(id).then(f=>{if(generation.current!==g)return null;setWorkspace(f);setLoadError(null);if(manual){setMonitorNotice(null);pollErrors.current=0;}return f;}).catch((e:unknown)=>{if(generation.current!==g)return null;const safe=e instanceof FiscalBillingApiError?e:new FiscalBillingApiError('BILLING_DOCUMENT_SUBMISSION_READ_FAILED','No se pudo actualizar el documento fiscal.');if(manual)setOperationError(safe);throw safe;}).finally(()=>{if(generation.current===g){inflight.current=null;if(manual)setRefreshing(false);}});inflight.current=p;return p;},[id,routeValid]);
  useEffect(()=>{if(!authorized||!routeValid)return;const g=++generation.current;setLoading(true);setLoadError(null);deadline.current=Date.now()+WINDOW;pollErrors.current=0;setMonitorStopped(false);void getBillingDocumentWorkspace(id).then(f=>{if(generation.current===g)setWorkspace(f);}).catch((e:unknown)=>{if(generation.current===g)setLoadError(e instanceof FiscalBillingApiError?e:new FiscalBillingApiError('BILLING_DOCUMENT_SUBMISSION_READ_FAILED','No se pudo cargar el documento fiscal.'));}).finally(()=>{if(generation.current===g)setLoading(false);});return()=>{generation.current+=1;inflight.current=null;};},[authorized,id,routeValid]);
  useEffect(()=>{if(!workspace||!active(workspace)||monitorStopped||issuing||refreshing)return;let cancelled=false,timer:ReturnType<typeof setTimeout>|null=null;const schedule=()=>{if(cancelled)return;if(Date.now()>=deadline.current){setMonitorNotice('El monitoreo automático terminó. El procesamiento continúa en segundo plano; puede actualizar el estado manualmente.');setMonitorStopped(true);return;}timer=setTimeout(()=>{void refresh(false).then(f=>{if(cancelled||!f||!active(f))return;pollErrors.current=0;schedule();}).catch(()=>{if(cancelled)return;pollErrors.current+=1;if(pollErrors.current>=MAX_ERRORS){setMonitorStopped(true);setMonitorNotice('El monitoreo automático se detuvo después de varios errores. Use “Actualizar estado” para volver a consultar.');return;}setMonitorNotice('No fue posible actualizar automáticamente. Se conserva la última información válida.');schedule();});},INTERVAL);};schedule();return()=>{cancelled=true;if(timer)clearTimeout(timer);};},[issuing,monitorStopped,refresh,refreshing,workspace]);
  async function issue(){if(issuingRef.current||!workspace||!eligible(workspace))return;issuingRef.current=true;setIssuing(true);setConfirming(false);setOperationError(null);setSuccess(null);try{const result=await requestBillingDocumentElectronicIssuance(id);setSuccess(result.newlyAllocated?`Se asignó el número fiscal ${result.fiscalNumber}. La presentación continúa en segundo plano.`:`La emisión ya estaba asignada con el número fiscal ${result.fiscalNumber}. La presentación continúa en segundo plano.`);const fresh=await refresh(false);if(fresh&&active(fresh)){deadline.current=Date.now()+WINDOW;pollErrors.current=0;setMonitorStopped(false);setMonitorNotice(null);}}catch(e){setOperationError(e instanceof FiscalBillingApiError?e:new FiscalBillingApiError('FISCAL_BILLING_REQUEST_FAILED','No se pudo solicitar la emisión electrónica.'));}finally{issuingRef.current=false;setIssuing(false);}}
  if(authorized&&!routeValid)return <main className="app-shell"><div className={styles.state}><div><h1>Documento fiscal no encontrado</h1><p>La identidad solicitada no es válida.</p><Button asChild variant="outline"><Link href="/fiscal-billing/sales-orders">Volver</Link></Button></div></div></main>;
  if(!authorized||loading)return <main className="app-shell"><div className={styles.state}><LoadingSpinner message="Cargando documento fiscal persistido…"/></div></main>;
  if(loadError||!workspace)return <main className="app-shell"><div className={styles.state}><div><h1>No se pudo cargar el documento fiscal</h1><p>{loadError?.message??'Documento no disponible.'}</p>{loadError&&<p className={styles.errorCode}>Código: {loadError.code}</p>}<Button variant="outline" onClick={()=>window.location.reload()}>Intentar nuevamente</Button>{' '}<Button asChild variant="outline"><Link href="/fiscal-billing/sales-orders">Volver</Link></Button></div></div></main>;
  const w=workspace,isReady=!w.readiness.receiverFiscalIdentityMissing&&!w.readiness.exchangeRateMissing,isEligible=eligible(w),isActive=active(w);
  return <main className="app-shell"><div className={styles.page}>
    <Link className={`${styles.backLink} ${styles.navigationButton}`} href={issuing?'#':'/fiscal-billing/sales-orders'} aria-disabled={issuing}><ArrowLeft/>Volver a Órdenes por facturar</Link>
    <header className={styles.header}><p className={styles.eyebrow}>Workspace fiscal · Snapshot persistido</p><h1 className={styles.title}>{w.internalNumber}</h1><p className={styles.subtitle}>Documento {w.documentTypeCode} · {w.currencyCode}</p><div className={styles.types}><Badge variant="outline" className={badge(w.lifecycleStatus)}>Documento: {lifecycle[w.lifecycleStatus]??w.lifecycleStatus}</Badge><Badge variant="outline" className={badge(w.providerStatus)}>Proveedor: {provider[w.providerStatus]??w.providerStatus}</Badge><Badge variant="outline" className={badge(w.taxAuthorityStatus)}>Hacienda: {hacienda[w.taxAuthorityStatus]??w.taxAuthorityStatus}</Badge></div></header>
    {w.taxAuthorityStatus==='ACCEPTED'&&<div className={`${styles.statusAlert} ${styles.successAlert}`}><strong>Documento aceptado por Hacienda</strong><p>Número fiscal: {w.fiscalNumber??'No disponible'} · Clave: {w.haciendaKey??'No disponible'}</p><p>Enviado: {time(w.submittedAt)} · Emitido: {time(w.issuedAt)}</p>{w.providerEnvironment&&<p>Entorno: {w.providerEnvironment}</p>}</div>}
    {w.taxAuthorityStatus==='REJECTED'&&<div className={`${styles.statusAlert} ${styles.dangerAlert}`}><strong>Documento rechazado por Hacienda</strong><p className={styles.rejectionText}>{w.haciendaRejectionDetail??'Hacienda no proporcionó un detalle adicional del rechazo.'}</p><p>Número fiscal: {w.fiscalNumber??'No disponible'} · Clave: {w.haciendaKey??'No disponible'}</p><p>Enviado: {time(w.submittedAt)}</p></div>}
    {w.providerStatus==='FAILED'&&<div className={`${styles.statusAlert} ${styles.dangerAlert}`}><strong>Falló el envío electrónico</strong><p>{w.providerLastErrorCode?technical(w.providerLastErrorCode):'El backend registró un fallo técnico seguro durante el envío.'}</p>{w.providerLastErrorCode&&<p>Código: {w.providerLastErrorCode}</p>}</div>}
    {isActive&&<div className={`${styles.statusAlert} ${styles.infoAlert}`}><strong>Procesamiento electrónico en curso</strong><p>La presentación continúa de forma asíncrona. “Procesado por el proveedor” no significa que Hacienda lo haya aceptado.</p></div>}
    {success&&<div className={`${styles.statusAlert} ${styles.successAlert}`}><strong>Solicitud registrada</strong><p>{success}</p></div>}
    {operationError&&<div className={`${styles.statusAlert} ${styles.dangerAlert}`}><strong>No se pudo completar la operación</strong><p>{operationError.message}</p><p>Código: {operationError.code}</p></div>}
    {monitorNotice&&<div className={`${styles.statusAlert} ${styles.infoAlert}`}><p>{monitorNotice}</p></div>}
    <div className={styles.workspaceActions}>{isEligible&&<Button className={styles.primaryAction} disabled={issuing||refreshing} onClick={()=>setConfirming(true)}>{issuing?'Solicitando emisión…':'Solicitar emisión electrónica'}</Button>}<Button className={styles.secondaryAction} variant="outline" disabled={issuing||refreshing} onClick={()=>{setOperationError(null);void refresh(true).catch(()=>undefined);}}><RefreshCw className={refreshing?styles.spin:undefined}/>{refreshing?'Actualizando…':'Actualizar estado'}</Button></div>
    <div className={styles.grid}><section className={`${styles.card} ${styles.section}`}><h2>Origen y condición comercial</h2><dl className={styles.details}><div><dt>Orden de venta</dt><dd>{w.sourceNumber??w.sourceId??'No disponible'}</dd></div><div><dt>Condición</dt><dd>{w.paymentConditionCode??'No disponible'}</dd></div><div><dt>Plazo</dt><dd>{w.creditTermDays===null?'No aplica':`${w.creditTermDays} días`}</dd></div><div><dt>Moneda</dt><dd>{w.currencyCode}</dd></div><div><dt>Tipo de cambio</dt><dd>{w.exchangeRate??'No aplica'}</dd></div><div><dt>Fecha fiscal</dt><dd>{date(w.fiscalIssueDate)}</dd></div></dl>{w.sourceId&&<Button asChild className={styles.secondaryAction} variant="outline" disabled={issuing}><Link href={`/fiscal-billing/sales-orders/${encodeURIComponent(w.sourceId)}/preparation`}>Ver preparación de la orden</Link></Button>}</section><section className={`${styles.card} ${styles.section}`}><h2>Preparación para emisión</h2><Badge variant="outline" className={isReady?styles.readyBadge:styles.errorBadge}>{isReady?'Lista':'Requiere revisión'}</Badge><p className={styles.muted}>{w.readiness.receiverFiscalIdentityMissing?'Falta la identidad fiscal completa del receptor. ':''}{w.readiness.exchangeRateMissing?'Falta el tipo de cambio fiscal. ':''}</p></section></div>
    <div className={styles.grid}><section className={`${styles.card} ${styles.section}`}><h2>Emisor</h2><dl className={styles.details}><div><dt>Nombre legal</dt><dd>{w.issuerName}</dd></div><div><dt>Identificación</dt><dd>{w.issuerIdentificationType} · {w.issuerIdentification}</dd></div><div><dt>Actividad</dt><dd>{w.issuerEconomicActivityCode??'No disponible'}</dd></div><div><dt>Establecimiento</dt><dd>{w.issuerEstablishmentCode??'No disponible'}</dd></div><div><dt>Terminal</dt><dd>{w.issuerTerminalCode??'No disponible'}</dd></div></dl></section><section className={`${styles.card} ${styles.section}`}><h2>Receptor</h2><dl className={styles.details}><div><dt>Nombre</dt><dd>{w.receiverName??'No disponible'}</dd></div><div><dt>Identificación</dt><dd>{w.receiverIdentificationType&&w.receiverIdentification?`${w.receiverIdentificationType} · ${w.receiverIdentification}`:'No disponible'}</dd></div><div><dt>Actividad</dt><dd>{w.receiverEconomicActivityCode??'No disponible'}</dd></div></dl></section></div>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Métodos de pago</h2><div className={styles.types}>{w.paymentMethods.map(p=><Badge key={p.id} variant="outline" className={styles.paymentMethodBadge}>{p.paymentMethodCode} · {p.description??payments[p.paymentMethodCode]??'Método fiscal'}</Badge>)}</div></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Líneas fiscales</h2><div className={styles.lineList}>{w.lines.map(l=><article className={styles.line} key={l.id}><div className={styles.lineHeader}><div><h3>{l.lineNumber}. {l.description}</h3><p>CABYS {l.cabysCode??'No disponible'} · Unidad {l.unitOfMeasureCode}</p></div><strong>{money(l.lineTotal,w.currencyCode)}</strong></div><div className={styles.profileGrid}><div><span>Cantidad</span><strong>{decimal(l.quantity)}</strong></div><div><span>Precio unitario</span><strong>{money(l.unitPrice,w.currencyCode)}</strong></div><div><span>Descuento</span><strong>{money(l.discountAmount,w.currencyCode)}</strong></div><div><span>Base imponible</span><strong>{money(l.taxableBase,w.currencyCode)}</strong></div><div><span>Impuesto</span><strong>{money(l.taxAmount,w.currencyCode)}</strong></div><div><span>Neto</span><strong>{money(l.netTaxAmount,w.currencyCode)}</strong></div></div>{l.taxes.map(t=><div className={styles.notes} key={t.id}>Impuesto {t.taxCode}/{t.rateCode}: {t.ratePercentage}% · {money(t.taxAmount,w.currencyCode)}{t.exemption&&<div>Exoneración {t.exemption.documentNumber}: {t.exemption.exemptedPercentage}% · {money(t.exemption.exemptedAmount,w.currencyCode)}</div>}</div>)}</article>)}</div></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Totales fiscales persistidos</h2><dl className={styles.details}>{[['Subtotal bruto',w.grossSubtotal],['Descuentos',w.discountTotal],['Total gravado',w.taxableTotal],['Total exento',w.exemptTotal],['Total exonerado',w.exoneratedTotal],['Impuesto bruto',w.grossTaxTotal],['Impuesto exonerado',w.exoneratedTaxTotal],['Impuesto neto',w.netTaxTotal],['Total',w.total]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(value,w.currencyCode)}</dd></div>)}</dl></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Identidad fiscal y proveedor</h2><dl className={styles.details}><div><dt>Consecutivo asignado</dt><dd>{w.allocatedSequenceNumber??'Aún no asignado'}</dd></div><div><dt>Número fiscal</dt><dd>{w.fiscalNumber??'Aún no asignado'}</dd></div><div><dt>Clave Hacienda</dt><dd>{w.haciendaKey??'No disponible'}</dd></div><div><dt>Entorno</dt><dd>{w.providerEnvironment??'No disponible'}</dd></div><div><dt>ID proveedor</dt><dd>{w.providerDocumentId??'No disponible'}</dd></div><div><dt>Enviado</dt><dd>{time(w.submittedAt)}</dd></div><div><dt>Emitido</dt><dd>{time(w.issuedAt)}</dd></div></dl></section>
    <ConfirmModal isOpen={confirming} title="Solicitar emisión electrónica" confirmText={issuing?'Solicitando emisión…':'Confirmar emisión'} confirmVariant="warning" isLoading={issuing} onCancel={()=>{if(!issuing)setConfirming(false);}} onConfirm={()=>void issue()} message={<div><p>Se asignará un consecutivo fiscal que no podrá devolverse ni reducirse desde esta pantalla.</p><p>El documento será encolado para presentación electrónica. FacturaEnCR y Hacienda procesan la solicitud de forma asíncrona.</p><p>La operación puede tener efecto fiscal real según el entorno configurado por el backend. Esta confirmación no espera la decisión final de Hacienda.</p></div>}/>
  </div></main>;
}
