'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ArrowLeft } from 'lucide-react';
import { LoadingSpinner } from '@/components/loading-spinner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { getHomeRouteForRole, getStoredSession } from '@/lib/auth-api';
import { FiscalBillingApiError, getBillingDocumentWorkspace, type BillingDocumentWorkspace } from '@/lib/fiscal-billing-api';
import styles from '../../fiscal-billing.module.css';

const PAYMENT_LABELS:Record<string,string>={'01':'Efectivo','02':'Tarjeta','03':'Cheque','04':'Transferencia/depósito bancario','05':'Recaudado por terceros','06':'SINPE Móvil','07':'Plataforma digital','99':'Otros'};
function boundedId(value:string){return value.length>=1&&value.length<=200&&value.trim()===value&&/^[A-Za-z0-9_-]+$/.test(value);}
function decimal(value:string){const match=/^(-?)(\d+)(?:\.(\d+))?$/.exec(value);if(!match)return value;const grouped=match[2].replace(/\B(?=(\d{3})+(?!\d))/g,',');return `${match[1]}${grouped}.${(match[3]??'').padEnd(2,'0').slice(0,2)}`;}
function money(value:string,currency:string){return `${currency} ${decimal(value)}`;}
function timestamp(value:string|null){if(!value)return 'No disponible';const date=new Date(value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('es-CR',{dateStyle:'medium',timeStyle:'medium',timeZone:'America/Costa_Rica'}).format(date):'No disponible';}
function dateOnly(value:string|null){return value&&/^\d{4}-\d{2}-\d{2}$/.test(value)?value:'No disponible';}
function address(value:unknown){if(!value||typeof value!=='object'||Array.isArray(value))return[];return Object.entries(value as Record<string,unknown>).flatMap(([key,item])=>typeof item==='string'&&item.trim()?[[key,item] as const]:[]);}
function statusClass(value:string){return value==='ACCEPTED'?styles.readyBadge:value==='REJECTED'||value==='FAILED'?styles.errorBadge:styles.documentTypeBadge;}
function providerErrorMessage(code:string){const messages:Record<string,string>={ELECTRONIC_SUBMISSION_AUTHENTICATION_FAILED:'La autenticación con el proveedor fiscal falló.',ELECTRONIC_SUBMISSION_AUTHORIZATION_FAILED:'La cuenta no está autorizada para emitir.',ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE:'El proveedor fiscal no está disponible.',ELECTRONIC_SUBMISSION_TIMEOUT:'El proveedor fiscal no respondió a tiempo.'};return messages[code]??'No fue posible completar la comunicación fiscal.';}

export default function FiscalWorkspacePage(){const params=useParams<{billingDocumentId:string}>(),router=useRouter(),id=params.billingDocumentId;const [authorized,setAuthorized]=useState(false),[workspace,setWorkspace]=useState<BillingDocumentWorkspace|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<FiscalBillingApiError|null>(null),[reload,setReload]=useState(0);
  const routeValid=boundedId(id);
  useEffect(()=>{const session=getStoredSession();if(!session?.user?.id){router.replace('/');return;}const role=String(session.user.role??'').toUpperCase();if(role!=='ADMIN'&&role!=='FACTURACION_COBROS'){router.replace(getHomeRouteForRole(role));return;}queueMicrotask(()=>setAuthorized(true));},[router]);
  useEffect(()=>{if(!authorized||!routeValid)return;const controller=new AbortController();void reload;void getBillingDocumentWorkspace(id,controller.signal).then(setWorkspace).catch(requestError=>{if(!controller.signal.aborted)setError(requestError instanceof FiscalBillingApiError?requestError:new FiscalBillingApiError('FISCAL_BILLING_REQUEST_FAILED','No se pudo cargar el documento fiscal.'));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[authorized,id,reload,routeValid]);
  if(authorized&&!routeValid)return <main className="app-shell"><div className={styles.state}><div><h1>Documento fiscal no encontrado</h1><p>La identidad solicitada no es válida.</p><Button asChild variant="outline"><Link href="/fiscal-billing/sales-orders">Volver</Link></Button></div></div></main>;
  if(!authorized||loading)return <main className="app-shell"><div className={styles.state}><LoadingSpinner message="Cargando borrador fiscal persistido…"/></div></main>;
  if(error||!workspace)return <main className="app-shell"><div className={styles.state}><div><h1>No se pudo cargar el documento fiscal</h1><p>{error?.message??'Documento no disponible.'}</p>{error&&<p className={styles.errorCode}>Código: {error.code}</p>}<Button variant="outline" onClick={()=>{setLoading(true);setError(null);setWorkspace(null);setReload(value=>value+1);}}>Intentar nuevamente</Button>{' '}<Button asChild variant="outline"><Link href="/fiscal-billing/sales-orders">Volver</Link></Button></div></div></main>;
  const receiverAddress=address(workspace.receiverAddressSnapshot),issuerAddress=address(workspace.issuerAddressSnapshot),ready=!workspace.readiness.receiverFiscalIdentityMissing&&!workspace.readiness.exchangeRateMissing;
  return <main className="app-shell"><div className={styles.page}>
    <Link className={styles.backLink} href="/fiscal-billing/sales-orders"><ArrowLeft/>Volver a Órdenes por facturar</Link>
    <header className={styles.header}><p className={styles.eyebrow}>Workspace fiscal · Snapshot persistido</p><h1 className={styles.title}>{workspace.internalNumber}</h1><p className={styles.subtitle}>Documento {workspace.documentTypeCode} · {workspace.currencyCode}</p><div className={styles.types}>{[['Ciclo',workspace.lifecycleStatus],['Proveedor',workspace.providerStatus],['Hacienda',workspace.taxAuthorityStatus]].map(([label,value])=><Badge key={label} variant="outline" className={statusClass(value)}>{label}: {value}</Badge>)}</div></header>
    <div className={styles.grid}><section className={`${styles.card} ${styles.section}`}><h2>Origen y condición comercial</h2><dl className={styles.details}><div><dt>Orden de venta</dt><dd>{workspace.sourceNumber??workspace.sourceId??'No disponible'}</dd></div><div><dt>Condición</dt><dd>{workspace.paymentConditionCode??'No disponible'}</dd></div><div><dt>Plazo de crédito</dt><dd>{workspace.creditTermDays===null?'No aplica':`${workspace.creditTermDays} días`}</dd></div><div><dt>Moneda</dt><dd>{workspace.currencyCode}</dd></div><div><dt>Tipo de cambio</dt><dd>{workspace.exchangeRate??'No aplica'}</dd></div><div><dt>Fecha fiscal</dt><dd>{dateOnly(workspace.fiscalIssueDate)}</dd></div></dl>{workspace.sourceId&&<Button asChild variant="outline"><Link href={`/fiscal-billing/sales-orders/${encodeURIComponent(workspace.sourceId)}/preparation`}>Ver preparación de la orden</Link></Button>}</section>
    <section className={`${styles.card} ${styles.section}`}><h2>Preparación para emisión</h2><Badge variant="outline" className={ready?styles.readyBadge:styles.errorBadge}>{ready?'Lista':'Requiere revisión'}</Badge><p className={styles.muted}>{workspace.readiness.receiverFiscalIdentityMissing?'Falta la identidad fiscal completa del receptor. ':''}{workspace.readiness.exchangeRateMissing?'Falta el tipo de cambio fiscal. ':''}</p><Button disabled>Emisión disponible en el siguiente paso</Button></section></div>
    <div className={styles.grid}><section className={`${styles.card} ${styles.section}`}><h2>Emisor</h2><dl className={styles.details}><div><dt>Nombre legal</dt><dd>{workspace.issuerName}</dd></div><div><dt>Identificación</dt><dd>{workspace.issuerIdentificationType} · {workspace.issuerIdentification}</dd></div><div><dt>Establecimiento</dt><dd>{workspace.issuerEstablishmentCode??'No disponible'}</dd></div><div><dt>Terminal</dt><dd>{workspace.issuerTerminalCode??'No disponible'}</dd></div><div><dt>Actividad</dt><dd>{workspace.issuerEconomicActivityCode??'No disponible'}</dd></div><div><dt>País</dt><dd>{workspace.countryCode}</dd></div>{issuerAddress.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section>
    <section className={`${styles.card} ${styles.section}`}><h2>Receptor</h2><dl className={styles.details}><div><dt>Nombre</dt><dd>{workspace.receiverName??'No disponible'}</dd></div><div><dt>Identificación</dt><dd>{workspace.receiverIdentificationType&&workspace.receiverIdentification?`${workspace.receiverIdentificationType} · ${workspace.receiverIdentification}`:'No disponible'}</dd></div><div><dt>Actividad</dt><dd>{workspace.receiverEconomicActivityCode??'No disponible'}</dd></div>{receiverAddress.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section></div>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Métodos de pago</h2><div className={styles.types}>{workspace.paymentMethods.map(method=><Badge key={method.id} variant="outline">{method.paymentMethodCode} · {method.description??PAYMENT_LABELS[method.paymentMethodCode]??'Método fiscal'}</Badge>)}</div></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Líneas fiscales</h2><div className={styles.lineList}>{workspace.lines.map(line=><article className={styles.line} key={line.id}><div className={styles.lineHeader}><div><h3>{line.lineNumber}. {line.description}</h3><p>CABYS {line.cabysCode??'No disponible'} · Unidad {line.unitOfMeasureCode}</p></div><strong>{money(line.lineTotal,workspace.currencyCode)}</strong></div><div className={styles.profileGrid}><div><span>Cantidad</span><strong>{decimal(line.quantity)}</strong></div><div><span>Precio unitario</span><strong>{money(line.unitPrice,workspace.currencyCode)}</strong></div><div><span>Descuento</span><strong>{money(line.discountAmount,workspace.currencyCode)}</strong></div><div><span>Base imponible</span><strong>{money(line.taxableBase,workspace.currencyCode)}</strong></div><div><span>Impuesto</span><strong>{money(line.taxAmount,workspace.currencyCode)}</strong></div><div><span>Neto</span><strong>{money(line.netTaxAmount,workspace.currencyCode)}</strong></div></div>{line.taxes.map(tax=><div className={styles.notes} key={tax.id}>Impuesto {tax.taxCode}/{tax.rateCode}: {tax.ratePercentage}% · {money(tax.taxAmount,workspace.currencyCode)}{tax.exemption&&<div>Exoneración {tax.exemption.documentNumber}: {tax.exemption.exemptedPercentage}% · {money(tax.exemption.exemptedAmount,workspace.currencyCode)}</div>}</div>)}</article>)}</div></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Totales fiscales persistidos</h2><dl className={styles.details}>{[['Subtotal bruto',workspace.grossSubtotal],['Descuentos',workspace.discountTotal],['Total gravado',workspace.taxableTotal],['Total exento',workspace.exemptTotal],['Total exonerado',workspace.exoneratedTotal],['Impuesto bruto',workspace.grossTaxTotal],['Impuesto exonerado',workspace.exoneratedTaxTotal],['Impuesto neto',workspace.netTaxTotal],['Total',workspace.total]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{money(value,workspace.currencyCode)}</dd></div>)}</dl></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Identidad fiscal y proveedor</h2><dl className={styles.details}><div><dt>Consecutivo asignado</dt><dd>{workspace.allocatedSequenceNumber??'Aún no asignado'}</dd></div><div><dt>Número fiscal</dt><dd>{workspace.fiscalNumber??'Aún no asignado'}</dd></div><div><dt>Clave Hacienda</dt><dd>{workspace.haciendaKey??'No disponible'}</dd></div><div><dt>Entorno</dt><dd>{workspace.providerEnvironment??'No disponible'}</dd></div><div><dt>ID proveedor</dt><dd>{workspace.providerDocumentId??'No disponible'}</dd></div><div><dt>Enviado</dt><dd>{timestamp(workspace.submittedAt)}</dd></div><div><dt>Emitido</dt><dd>{timestamp(workspace.issuedAt)}</dd></div></dl></section>
    {(workspace.providerLastErrorCode||workspace.haciendaRejectionDetail)&&<section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Incidencias</h2>{workspace.providerLastErrorCode&&<div className={`${styles.issue} ${styles.issueBlocking}`}><strong>{providerErrorMessage(workspace.providerLastErrorCode)}</strong><p>Código: {workspace.providerLastErrorCode}</p><p>{timestamp(workspace.providerLastErrorAt)}</p></div>}{workspace.haciendaRejectionDetail&&<div className={`${styles.issue} ${styles.issueBlocking}`}><strong>Hacienda rechazó el documento</strong><p className={styles.rejectionText}>{workspace.haciendaRejectionDetail}</p></div>}</section>}
  </div></main>;
}
