export enum AdditionalServiceType {
  SEAT = "SEAT",
  BAGGAGE = "BAGGAGE",
  TOUR = "TOUR",
  ACCOMMODATION = "ACCOMMODATION",
  LODGING = "LODGING",
  INSURANCE = "INSURANCE",
  TRAVEL_EXTENSION = "TRAVEL_EXTENSION",
  ITINERARY_CHANGE = "ITINERARY_CHANGE",
  TRANSPORTATION = "TRANSPORTATION",
  VISA_ASSISTANCE = "VISA_ASSISTANCE",
  OTHER = "OTHER",
}
