import type { JobDispatcherService } from "../../infrastructure/job-dispatcher";
import { Logger } from "@nestjs/common";
import { PLATFORM_QUEUE_KEYS } from "../../infrastructure/queue";
import type { PrismaService } from "../../prisma/prisma.service";
import { FISCAL_STATUS_RECONCILIATION_BATCH_SIZE, FISCAL_STATUS_RECONCILIATION_JOB_NAME, FISCAL_STATUS_RECONCILIATION_LEASE_MS, fiscalStatusReconciliationJobId } from "./fiscal-status-reconciliation.constants";
import { FiscalStatusReconciliationPublisher } from "./fiscal-status-reconciliation.publisher";

describe("FiscalStatusReconciliationPublisher",()=>{
  afterEach(()=>jest.restoreAllMocks());
  it("claims with the exact SQL aliases and maximum generated lock-owner shape",async()=>{const c=context([validRow()]);await c.publisher.publishDueStatusChecks();
    expect(c.transaction).toHaveBeenCalledTimes(1);const sql=c.sql.mock.calls[0][0].join(" ");for(const fragment of ["WITH selected AS","FOR UPDATE SKIP LOCKED",'ORDER BY "providerNextStatusCheckAt" ASC, "id" ASC','"lifecycleStatus" = \'SUBMITTED\'','"providerStatus" = \'PROCESSED\'','"taxAuthorityStatus" = \'PROCESSING\'','"providerNextStatusCheckAt" <=','"providerStatusCheckLeaseUntil" <=','UPDATE "billing_documents"','document."id" AS "billingDocumentId"','document."providerStatusCheckLockOwner" AS "statusCheckLockOwner"','"providerStatusCheckLeaseUntil"'])expect(sql).toContain(fragment);expect(c.sql.mock.calls[0]).toContain(FISCAL_STATUS_RECONCILIATION_BATCH_SIZE);expect(STATUS_CHECK_LOCK_OWNER).toHaveLength(43);
    expect(c.dispatch).toHaveBeenCalledWith({queueKey:PLATFORM_QUEUE_KEYS.FISCAL_STATUS_RECONCILIATION,jobName:FISCAL_STATUS_RECONCILIATION_JOB_NAME,payload:{tenantId:TENANT_ID,billingDocumentId:BILLING_DOCUMENT_ID,statusCheckLockOwner:STATUS_CHECK_LOCK_OWNER,eventVersion:1},metadata:{tenantId:TENANT_ID},options:{jobId:fiscalStatusReconciliationJobId(BILLING_DOCUMENT_ID),attempts:3,backoff:{type:"exponential",delay:2000},removeOnComplete:true,removeOnFail:false}});
    expect(FISCAL_STATUS_RECONCILIATION_LEASE_MS).toBe(60_000);
  });
  it("continues the claimed batch after one enqueue failure and leaves leases for expiry",async()=>{const c=context([{tenantId:"tenant-a",billingDocumentId:"a",statusCheckLockOwner:"owner-1"},{tenantId:"tenant-b",billingDocumentId:"b",statusCheckLockOwner:"owner-2"}]);c.dispatch.mockRejectedValueOnce(new Error("redis secret")).mockResolvedValueOnce({});await c.publisher.publishDueStatusChecks();expect(c.dispatch).toHaveBeenCalledTimes(2);expect(c.prisma).not.toHaveProperty("billingDocument");});
  it("classifies a disabled dispatcher with its established static message",async()=>{const log=errorLog(),c=context([validRow()]);c.dispatch.mockRejectedValueOnce(new Error("Generic job dispatcher is disabled."));await c.publisher.publishDueStatusChecks();expect(log).toHaveBeenCalledWith('FISCAL_STATUS_RECONCILIATION_DISPATCH_FAILED phase=DURING_DISPATCH category=DISPATCHER_DISABLED error=Error reason="Generic job dispatcher is disabled."');});
  it.each([["Redis is not configured.",'REDIS_CONFIGURATION_MISSING error=Error reason="Redis is not configured."'],["Queue is unavailable: private-queue-name.",'QUEUE_UNAVAILABLE error=Error reason="Queue is unavailable."']])("classifies unavailable Redis/queue configuration without logging runtime details",async(message,expected)=>{const log=errorLog(),c=context([validRow()]);c.dispatch.mockRejectedValueOnce(new Error(message));await c.publisher.publishDueStatusChecks();expect(log).toHaveBeenCalledWith(`FISCAL_STATUS_RECONCILIATION_DISPATCH_FAILED phase=DURING_DISPATCH category=${expected}`);expect(log.mock.calls.join(" ")).not.toContain("private-queue-name");});
  it("classifies an invalid claimed row before dispatch",async()=>{const log=errorLog(),c=context([{...validRow(),billingDocumentId:""}]);await c.publisher.publishDueStatusChecks();expect(c.dispatch).not.toHaveBeenCalled();expect(log).toHaveBeenCalledWith('FISCAL_STATUS_RECONCILIATION_DISPATCH_FAILED phase=BEFORE_DISPATCH category=INVALID_CLAIMED_ROW error=Error reason="FISCAL_STATUS_RECONCILIATION_JOB_INVALID"');});
  it("proves the former unaliased database field is not the claimed-row contract",async()=>{const log=errorLog(),c=context([{tenantId:TENANT_ID,billingDocumentId:BILLING_DOCUMENT_ID,providerStatusCheckLockOwner:STATUS_CHECK_LOCK_OWNER} as unknown as ReturnType<typeof validRow>]);await c.publisher.publishDueStatusChecks();expect(c.dispatch).not.toHaveBeenCalled();expect(log).toHaveBeenCalledWith('FISCAL_STATUS_RECONCILIATION_DISPATCH_FAILED phase=BEFORE_DISPATCH category=INVALID_CLAIMED_ROW error=Error reason="FISCAL_STATUS_RECONCILIATION_JOB_INVALID"');});
  it("treats a deduplicated dispatcher resolution as unchanged success",async()=>{const log=errorLog(),c=context([validRow()]);c.dispatch.mockResolvedValueOnce({id:"existing-job"});await c.publisher.publishDueStatusChecks();expect(c.dispatch).toHaveBeenCalledTimes(1);expect(log).not.toHaveBeenCalled();});
  it("logs only the stable code and safe class for an unknown native error",async()=>{const log=errorLog(),c=context([validRow()]);c.dispatch.mockRejectedValueOnce(new TypeError("redis://credential@host customer fiscal payload"));await c.publisher.publishDueStatusChecks();expect(log).toHaveBeenCalledWith("FISCAL_STATUS_RECONCILIATION_DISPATCH_FAILED phase=DURING_DISPATCH category=UNKNOWN error=TypeError");expect(log.mock.calls.join(" ")).not.toContain("credential");});
  it.each([undefined,null,"","   "])("never dispatches an invalid BillingDocument identifier: %p",async billingDocumentId=>{const c=context([{tenantId:"tenant-a",billingDocumentId:billingDocumentId as string,statusCheckLockOwner:"owner-1"}]);await c.publisher.publishDueStatusChecks();expect(c.dispatch).not.toHaveBeenCalled();expect(fiscalStatusReconciliationJobId("document-a")).toBe("fiscal-status-document-a");});
  it("uses one deterministic document job ID across duplicate scheduler cycles",async()=>{const c=context([{tenantId:"tenant-a",billingDocumentId:"document-a",statusCheckLockOwner:"owner-1"}]);await c.publisher.publishDueStatusChecks();await c.publisher.publishDueStatusChecks();expect(c.dispatch).toHaveBeenCalledTimes(2);expect(c.dispatch.mock.calls.map(([request])=>request.options.jobId)).toEqual(["fiscal-status-document-a","fiscal-status-document-a"]);});
  it("uses completion-scheduled lifecycle and awaits an active shutdown cycle",async()=>{jest.useFakeTimers();const c=context([]);c.publisher.onModuleInit();expect(jest.getTimerCount()).toBe(1);await jest.runOnlyPendingTimersAsync();expect(jest.getTimerCount()).toBe(1);await c.publisher.onModuleDestroy();expect(jest.getTimerCount()).toBe(0);jest.useRealTimers();});
});
function context(rows:Array<{tenantId:string;billingDocumentId:string;statusCheckLockOwner:string}>){const sql=jest.fn().mockResolvedValue(rows),transaction=jest.fn(async(cb:(tx:{ $queryRaw:jest.Mock})=>unknown)=>cb({$queryRaw:sql})),dispatch=jest.fn().mockResolvedValue({}),prisma={$transaction:transaction};return{sql,transaction,dispatch,prisma,publisher:new FiscalStatusReconciliationPublisher(prisma as unknown as PrismaService,{dispatch} as unknown as JobDispatcherService)};}
const TENANT_ID="cm1tenant00000000000000001";
const BILLING_DOCUMENT_ID="cm1document00000000000001";
const STATUS_CHECK_LOCK_OWNER="fsr-123e4567-e89b-12d3-a456-426614174000-25";
function validRow(){return{tenantId:TENANT_ID,billingDocumentId:BILLING_DOCUMENT_ID,statusCheckLockOwner:STATUS_CHECK_LOCK_OWNER};}
function errorLog(){return jest.spyOn(Logger.prototype,"error").mockImplementation(()=>undefined);}
