import { UnrecoverableError,type Job } from "bullmq";import type { JobEnvelope } from "../../infrastructure/job-dispatcher";import { PLATFORM_QUEUE_KEYS } from "../../infrastructure/queue";import type { WorkerService } from "../../infrastructure/worker";import type { BillingDocumentStatusLookupService } from "../billing-document-status-lookup.service";import type { BillingDocumentStatusPersistenceService } from "../billing-document-status-persistence.service";import { FISCAL_STATUS_RECONCILIATION_CONCURRENCY,FISCAL_STATUS_RECONCILIATION_JOB_NAME,FISCAL_STATUS_RECONCILIATION_WORKER_KEY,fiscalStatusReconciliationJobId } from "./fiscal-status-reconciliation.constants";import { FiscalStatusReconciliationProcessor } from "./fiscal-status-reconciliation.processor";
describe("FiscalStatusReconciliationProcessor",()=>{
  it.each(["PROCESSING","ACCEPTED","REJECTED"] as const)("delegates one exact %s lookup and persistence",async taxAuthorityStatus=>{const c=context(taxAuthorityStatus);c.processor.onModuleInit();expect(c.register).toHaveBeenCalledWith(FISCAL_STATUS_RECONCILIATION_WORKER_KEY,PLATFORM_QUEUE_KEYS.FISCAL_STATUS_RECONCILIATION,expect.any(Function),{concurrency:FISCAL_STATUS_RECONCILIATION_CONCURRENCY,jobNames:FISCAL_STATUS_RECONCILIATION_JOB_NAME});expect(FISCAL_STATUS_RECONCILIATION_CONCURRENCY).toBe(10);const value=job(),result=await c.handler!(value);expect(c.lookup).toHaveBeenCalledWith("tenant-a","document-a","claim-a");expect(c.lookup).toHaveBeenCalledTimes(1);expect(c.persist).toHaveBeenCalledWith(c.lookupResult);expect(c.persist.mock.calls[0][0]).toBe(c.lookupResult);expect(result).toEqual({completed:true,classification:taxAuthorityStatus});});
  it.each([{name:"other"},{id:"wrong"},{data:{payload:{tenantId:"tenant-a",billingDocumentId:"document-a",statusCheckLockOwner:"claim-a",eventVersion:1,extra:true},metadata:{tenantId:"tenant-a"}}},{data:{payload:{tenantId:"tenant-b",billingDocumentId:"document-a",statusCheckLockOwner:"claim-a",eventVersion:1},metadata:{tenantId:"tenant-a"}}}])("rejects malformed jobs once before lookup: %o",async override=>{const c=context("PROCESSING");c.processor.onModuleInit();const error=await c.handler!({...job(),...override} as never).catch(value=>value);expect(error).toBeInstanceOf(UnrecoverableError);expect((error as Error).message).toBe("FISCAL_STATUS_RECONCILIATION_JOB_INVALID");expect(c.lookup).not.toHaveBeenCalled();});
  it("propagates lookup and persistence failures without direct side effects",async()=>{let c=context("PROCESSING");c.lookup.mockRejectedValueOnce(new Error("provider unavailable"));c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("provider unavailable");expect(c.persist).not.toHaveBeenCalled();c=context("PROCESSING");c.persist.mockRejectedValueOnce(new Error("db unavailable"));c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("db unavailable");expect(c.lookup).toHaveBeenCalledTimes(1);});
  it.each(["ACCEPTED","REJECTED"] as const)("completes an already persisted %s retry without persistence",async taxAuthorityStatus=>{const c=context(taxAuthorityStatus);c.lookup.mockResolvedValueOnce({classification:"ALREADY_COMPLETED",taxAuthorityStatus});c.processor.onModuleInit();await expect(c.handler!(job())).resolves.toEqual({completed:true,classification:taxAuthorityStatus});expect(c.persist).not.toHaveBeenCalled();});
});
function job(){return{name:FISCAL_STATUS_RECONCILIATION_JOB_NAME,id:fiscalStatusReconciliationJobId("document-a"),data:{payload:{tenantId:"tenant-a",billingDocumentId:"document-a",statusCheckLockOwner:"claim-a",eventVersion:1},metadata:{tenantId:"tenant-a"}}} as unknown as Job<JobEnvelope<unknown>>;}
function context(taxAuthorityStatus:"PROCESSING"|"ACCEPTED"|"REJECTED"){let handler:((job:Job<JobEnvelope<unknown>>)=>Promise<unknown>)|undefined;const register=jest.fn((_k,_q,h)=>handler=h),lookupResult={persistedIdentity:{},providerResult:{}},lookup=jest.fn().mockResolvedValue(lookupResult),persist=jest.fn().mockResolvedValue({taxAuthorityStatus});return{register,lookup,persist,lookupResult,processor:new FiscalStatusReconciliationProcessor({registerWorker:register} as unknown as WorkerService,{lookupStatus:lookup} as unknown as BillingDocumentStatusLookupService,{persist} as unknown as BillingDocumentStatusPersistenceService),get handler(){return handler;}};}
