import { HttpException } from "@nestjs/common";
import type { ConfigService } from "@nestjs/config";
import { readFileSync } from "node:fs";
import { UnrecoverableError, type Job } from "bullmq";
import type { JobEnvelope } from "../../infrastructure/job-dispatcher";
import { PLATFORM_QUEUE_KEYS } from "../../infrastructure/queue";
import { getQueueConfig } from "../../infrastructure/queue/queue.config";
import type { WorkerService } from "../../infrastructure/worker";
import { getWorkerConfig } from "../../infrastructure/worker/worker.config";
import type { BillingDocumentSubmissionPreparationService, BillingDocumentSubmissionPreparationResult } from "../billing-document-submission-preparation.service";
import type { BillingDocumentSubmissionAttemptService, BillingDocumentSubmissionAttemptResult } from "../billing-document-submission-attempt.service";
import { BillingDocumentSubmissionExecutorService, type BillingDocumentSubmissionExecutorOutcome } from "../billing-document-submission-executor.service";
import type { BillingDocumentSubmissionOutcomeService } from "../billing-document-submission-outcome.service";
import type { BillingDocumentSubmissionFailureFinalizationService } from "../billing-document-submission-failure-finalization.service";
import type { ElectronicDocumentSubmissionProvider } from "../providers/electronic-document-submission.provider";
import { FISCAL_BILLING_SUBMISSION_CONCURRENCY, FISCAL_BILLING_SUBMISSION_WORKER_REGISTRATION_KEY, FiscalBillingSubmissionProcessor } from "./fiscal-billing-submission.processor";
import { FISCAL_ISSUANCE_JOB_NAME } from "./fiscal-outbox-publisher.constants";

const HASH="a".repeat(64),ATTEMPT=new Date("2026-08-24T12:00:00.123Z");
describe("FiscalBillingSubmissionProcessor",()=>{
  it("registers exactly once on the existing fiscal queue and forwards the exact safe envelope",async()=>{const c=context(ackOutcome());c.processor.onModuleInit();expect(c.registerWorker).toHaveBeenCalledTimes(1);expect(c.registerWorker).toHaveBeenCalledWith(FISCAL_BILLING_SUBMISSION_WORKER_REGISTRATION_KEY,PLATFORM_QUEUE_KEYS.FISCAL_BILLING,expect.any(Function),{concurrency:5,jobNames:FISCAL_ISSUANCE_JOB_NAME});expect(FISCAL_BILLING_SUBMISSION_CONCURRENCY).toBe(5);const jobValue=job(),result=await c.handler!(jobValue);expect(c.execute).toHaveBeenCalledTimes(1);const envelope=c.execute.mock.calls[0][0];expect(envelope).toEqual({name:jobValue.name,id:jobValue.id,payload:jobValue.data.payload,metadata:jobValue.data.metadata});expect(envelope.payload).toBe(jobValue.data.payload);expect(envelope.metadata).toBe(jobValue.data.metadata);expect(c.persist).toHaveBeenCalledWith(c.outcome);expect(result).toEqual({completed:true,classification:"ACKNOWLEDGED"});});

  it("handles only the exact fiscal job name",async()=>{const c=context(ackOutcome());c.processor.onModuleInit();const unsupported={...job(),name:"other"} as Job<JobEnvelope<unknown>>;await expect(c.handler!(unsupported)).rejects.toThrow("FISCAL_SUBMISSION_JOB_UNSUPPORTED");expect(c.execute).not.toHaveBeenCalled();expect(c.persist).not.toHaveBeenCalled();});

  it.each([definiteOutcome(),reconciliationOutcome(),alreadyAcknowledged(),alreadyFailed()])("persists and completes normalized $classification without retry throw",async outcome=>{const c=context(outcome);c.processor.onModuleInit();await expect(c.handler!(job())).resolves.toEqual({completed:true,classification:outcome.classification});expect(c.execute).toHaveBeenCalledTimes(1);expect(c.persist).toHaveBeenCalledTimes(1);expect(c.persist).toHaveBeenCalledWith(outcome);expect(c.finalize).not.toHaveBeenCalled();});

  it("fails unknown executor outcomes before persistence",async()=>{const c=context({classification:"UNKNOWN"} as never);c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("FISCAL_SUBMISSION_OUTCOME_INVALID");expect(c.persist).not.toHaveBeenCalled();});

  it("propagates malformed/infrastructure executor failures and outcome persistence failures",async()=>{let c=context(ackOutcome());c.execute.mockRejectedValue(new Error("stable-executor-failure"));c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("stable-executor-failure");expect(c.persist).not.toHaveBeenCalled();c=context(ackOutcome());c.persist.mockRejectedValue(new Error("stable-persistence-failure"));c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("stable-persistence-failure");expect(c.execute).toHaveBeenCalledTimes(1);expect(c.persist).toHaveBeenCalledTimes(1);});

  it("finalizes permanent preparation failure without BullMQ retry",async()=>{const c=context(ackOutcome());c.execute.mockRejectedValue(fiscalError("BILLING_DOCUMENT_SUBMISSION_PREPARATION_FAILED",422));c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toBeInstanceOf(UnrecoverableError);expect(c.finalize).toHaveBeenCalledWith({tenantId:"tenant-a",billingDocumentId:"document-a",errorCode:"BILLING_DOCUMENT_SUBMISSION_PREPARATION_FAILED"});expect(c.persist).not.toHaveBeenCalled();});

  it("keeps transient failures retryable before the final BullMQ attempt",async()=>{const c=context(ackOutcome());c.execute.mockRejectedValue(new Error("temporary failure"));c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("temporary failure");expect(c.finalize).not.toHaveBeenCalled();});

  it("finalizes a retryable failure only on the final BullMQ attempt",async()=>{const c=context(ackOutcome());c.execute.mockRejectedValue(new Error("temporary failure"));c.processor.onModuleInit();await expect(c.handler!(job("outbox-a","document-a","tenant-a",2))).rejects.toThrow("temporary failure");expect(c.finalize).toHaveBeenCalledWith({tenantId:"tenant-a",billingDocumentId:"document-a",errorCode:"BILLING_DOCUMENT_SUBMISSION_WORKER_EXHAUSTED"});});

  it("a retry after a committed claim cannot make a second provider call",async()=>{const prepared=preparation(),prepare=jest.fn().mockResolvedValue(prepared),claim=jest.fn().mockResolvedValueOnce(claimed()).mockResolvedValueOnce({classification:"RECONCILIATION_REQUIRED",tenantId:"tenant-a",billingDocumentId:"document-a"}),submit=jest.fn().mockResolvedValue(acknowledgement()),persist=jest.fn().mockRejectedValueOnce(new Error("db unavailable")).mockResolvedValueOnce({classification:"ALREADY_PERSISTED"});const executor=new BillingDocumentSubmissionExecutorService({prepare} as unknown as BillingDocumentSubmissionPreparationService,{claim} as unknown as BillingDocumentSubmissionAttemptService,{submitElectronicDocument:submit} as ElectronicDocumentSubmissionProvider);const c=contextWithExecutor(executor,persist);c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toThrow("db unavailable");await expect(c.handler!(job())).resolves.toMatchObject({classification:"RECONCILIATION_REQUIRED"});expect(submit).toHaveBeenCalledTimes(1);expect(claim).toHaveBeenCalledTimes(2);expect(persist).toHaveBeenCalledTimes(2);});

  it("a transient failure before claim can retry and submit exactly once",async()=>{const prepared=preparation(),prepare=jest.fn().mockResolvedValue(prepared),claim=jest.fn().mockRejectedValueOnce(new Error("temporary database failure")).mockResolvedValueOnce(claimed()),submit=jest.fn().mockResolvedValue(acknowledgement()),persist=jest.fn().mockResolvedValue({classification:"PERSISTED"});const executor=new BillingDocumentSubmissionExecutorService({prepare} as unknown as BillingDocumentSubmissionPreparationService,{claim} as unknown as BillingDocumentSubmissionAttemptService,{submitElectronicDocument:submit} as ElectronicDocumentSubmissionProvider);const c=contextWithExecutor(executor,persist);c.processor.onModuleInit();await expect(c.handler!(job())).rejects.toBeDefined();await expect(c.handler!(job())).resolves.toMatchObject({classification:"ACKNOWLEDGED"});expect(claim).toHaveBeenCalledTimes(2);expect(submit).toHaveBeenCalledTimes(1);expect(persist).toHaveBeenCalledTimes(1);});

  it.each([["existing reconciliation",{classification:"RECONCILIATION_REQUIRED",tenantId:"tenant-a",billingDocumentId:"document-a"}],["existing acknowledgement",{classification:"ALREADY_ACKNOWLEDGED",tenantId:"tenant-a",billingDocumentId:"document-a"}]] as const)("duplicate delivery with %s makes no provider call",async(_label,claimResult)=>{const prepared=preparation(),submit=jest.fn(),executor=new BillingDocumentSubmissionExecutorService({prepare:jest.fn().mockResolvedValue(prepared)} as unknown as BillingDocumentSubmissionPreparationService,{claim:jest.fn().mockResolvedValue(claimResult)} as unknown as BillingDocumentSubmissionAttemptService,{submitElectronicDocument:submit} as ElectronicDocumentSubmissionProvider);const c=contextWithExecutor(executor,jest.fn().mockResolvedValue({classification:"ALREADY_PERSISTED"}));c.processor.onModuleInit();await c.handler!(job());expect(submit).not.toHaveBeenCalled();});

  it("same-document concurrent execution delegates safety and produces one provider call",async()=>{const prepared=preparation();let claims=0;const submit=jest.fn().mockResolvedValue(acknowledgement()),claim=jest.fn(async()=>++claims===1?claimed():{classification:"RECONCILIATION_REQUIRED",tenantId:"tenant-a",billingDocumentId:"document-a"} as BillingDocumentSubmissionAttemptResult),executor=new BillingDocumentSubmissionExecutorService({prepare:jest.fn().mockResolvedValue(prepared)} as unknown as BillingDocumentSubmissionPreparationService,{claim} as unknown as BillingDocumentSubmissionAttemptService,{submitElectronicDocument:submit} as ElectronicDocumentSubmissionProvider);const c=contextWithExecutor(executor,jest.fn().mockResolvedValue({classification:"PERSISTED"}));c.processor.onModuleInit();await Promise.all([c.handler!(job()),c.handler!(job())]);expect(submit).toHaveBeenCalledTimes(1);});

  it("different documents execute independently without a processor mutex",async()=>{const c=context(ackOutcome());c.processor.onModuleInit();await Promise.all([c.handler!(job("outbox-a","document-a")),c.handler!(job("outbox-b","document-b"))]);expect(c.execute).toHaveBeenCalledTimes(2);expect(c.persist).toHaveBeenCalledTimes(2);expect(c.execute.mock.calls.map(x=>x[0].id)).toEqual(["fiscal-issuance-outbox-a","fiscal-issuance-outbox-b"]);});

  it("same-tenant and cross-tenant identities can overlap without mixing",async()=>{const c=context(ackOutcome());let active=0,maximum=0;const release: Array<()=>void>=[];c.execute.mockImplementation(async envelope=>{active+=1;maximum=Math.max(maximum,active);await new Promise<void>(resolve=>release.push(resolve));active-=1;return{...ackOutcome(),attempt:{...attempt(),tenantId:(envelope.payload as {tenantId:string}).tenantId,billingDocumentId:(envelope.payload as {billingDocumentId:string}).billingDocumentId}};});c.processor.onModuleInit();const jobs=[job("a","document-a","tenant-a"),job("b","document-b","tenant-a"),job("c","document-c","tenant-b")];const running=jobs.map(value=>c.handler!(value));await Promise.resolve();expect(maximum).toBe(3);expect(c.execute.mock.calls.map(call=>call[0].payload)).toEqual(jobs.map(value=>value.data.payload));release.forEach(resolve=>resolve());await Promise.all(running);expect(c.persist).toHaveBeenCalledTimes(3);});

  it("uses explicit bounded fiscal retry policy without changing generic defaults",()=>{const config={get:jest.fn((_key:string,fallback:string)=>fallback)} as unknown as ConfigService;expect(getQueueConfig(config).defaultJobOptions).toMatchObject({attempts:1,removeOnComplete:false,removeOnFail:false});const worker=getWorkerConfig(config);expect(worker.concurrency).toBeGreaterThan(0);expect(Number.isInteger(worker.concurrency)).toBe(true);const publisher=readFileSync(require.resolve("./fiscal-outbox-publisher.service"),"utf8");expect(publisher).toContain("jobId: fiscalIssuanceJobId(event.id)");expect(publisher).toContain("attempts: 3");expect(publisher).toContain('backoff: { type: "exponential", delay: 2000 }');expect(publisher).toContain("removeOnComplete: false");expect(publisher).toContain("removeOnFail: false");const processor=readFileSync(require.resolve("./fiscal-billing-submission.processor"),"utf8");expect(processor).not.toMatch(/new Worker|new Redis|setInterval|setTimeout|OnModuleDestroy|Prisma|FacturaEnCr|BCCR|Hacienda|allocator|sequence/);});

  it("returns no sensitive payload or provider identity",async()=>{const c=context(ackOutcome());c.processor.onModuleInit();const result=await c.handler!(job());const safe=JSON.stringify(result);for(const secret of ["canonicalBody","idempotency","hacienda","consecutive","provider-a","customer","credential"])expect(safe.toLowerCase()).not.toContain(secret.toLowerCase());});
});

function context(outcome:BillingDocumentSubmissionExecutorOutcome){let handler:((job:Job<JobEnvelope<unknown>>)=>Promise<unknown>)|undefined;const registerWorker=jest.fn((_key,_queue,callback)=>{handler=callback;}),execute=jest.fn().mockResolvedValue(outcome),persist=jest.fn().mockResolvedValue({classification:"PERSISTED"}),finalize=jest.fn().mockResolvedValue("FINALIZED");const processor=new FiscalBillingSubmissionProcessor({registerWorker} as unknown as WorkerService,{execute} as unknown as BillingDocumentSubmissionExecutorService,{persist} as unknown as BillingDocumentSubmissionOutcomeService,{finalizePristineFailure:finalize} as unknown as BillingDocumentSubmissionFailureFinalizationService);return{processor,registerWorker,execute,persist,finalize,outcome,get handler(){return handler;}};}
function contextWithExecutor(executor:BillingDocumentSubmissionExecutorService,persist:jest.Mock){let handler:((job:Job<JobEnvelope<unknown>>)=>Promise<unknown>)|undefined;const registerWorker=jest.fn((_key,_queue,callback)=>{handler=callback;});const processor=new FiscalBillingSubmissionProcessor({registerWorker} as unknown as WorkerService,executor,{persist} as unknown as BillingDocumentSubmissionOutcomeService,{finalizePristineFailure:jest.fn().mockResolvedValue("FINALIZED")} as unknown as BillingDocumentSubmissionFailureFinalizationService);return{processor,get handler(){return handler;}};}
function job(outbox="outbox-a",document="document-a",tenant="tenant-a",attemptsMade=0){return{name:FISCAL_ISSUANCE_JOB_NAME,id:`fiscal-issuance-${outbox}`,data:{payload:{tenantId:tenant,billingDocumentId:document,eventVersion:1},metadata:{tenantId:tenant,correlationId:"safe"}},opts:{attempts:3,backoff:{type:"exponential",delay:2000},removeOnComplete:false,removeOnFail:false},attemptsMade} as unknown as Job<JobEnvelope<unknown>>;}
function fiscalError(code:string,status:number){return new HttpException({code},status);}
function attempt(){return{tenantId:"tenant-a",billingDocumentId:"document-a",requestHash:HASH,attemptedAt:ATTEMPT};}
function ackOutcome():BillingDocumentSubmissionExecutorOutcome{return{classification:"ACKNOWLEDGED",attempt:attempt(),acknowledgement:acknowledgement()};}
function definiteOutcome():BillingDocumentSubmissionExecutorOutcome{return{classification:"DEFINITE_FAILURE",attempt:attempt(),errorCode:"ELECTRONIC_SUBMISSION_INVALID"};}
function reconciliationOutcome():BillingDocumentSubmissionExecutorOutcome{return{classification:"RECONCILIATION_REQUIRED",attempt:attempt(),reasonCode:"ELECTRONIC_SUBMISSION_TIMEOUT",retryAfterSeconds:null};}
function alreadyAcknowledged():BillingDocumentSubmissionExecutorOutcome{return{classification:"ALREADY_ACKNOWLEDGED",tenantId:"tenant-a",billingDocumentId:"document-a"};}
function alreadyFailed():BillingDocumentSubmissionExecutorOutcome{return{classification:"ALREADY_FAILED",tenantId:"tenant-a",billingDocumentId:"document-a"};}
function acknowledgement(){return{classification:"ACKNOWLEDGED_PROVIDER_SUBMISSION" as const,providerDocumentId:"provider-a",haciendaKey:"50624082600310167816600100001010000000042142351111",consecutive:"00100001010000000042",status:{providerStatus:"queued",final:false,accepted:false,rejected:false},providerEnvironment:"sandbox" as const,estimatedReadyAt:null,rejectionDetail:null};}
function claimed():BillingDocumentSubmissionAttemptResult{return{classification:"CLAIMED",tenantId:"tenant-a",billingDocumentId:"document-a",requestHash:HASH,attemptedAt:ATTEMPT,issuanceIdempotencyKey:"billing-document:document-a:electronic-issuance:v1"};}
function preparation():BillingDocumentSubmissionPreparationResult{return{identity:{tenantId:"tenant-a",billingDocumentId:"document-a"},allocationIdentity:{billingDocumentNumberSequenceId:"sequence-a",allocatedSequenceNumber:"42"},recoveryIdentity:{fiscalNumber:"00100001010000000042",documentTypeCode:"01",issuanceIdempotencyKey:"billing-document:document-a:electronic-issuance:v1",fiscalEmissionAt:new Date("2026-08-24T06:00:00Z"),fiscalIssueDate:"2026-08-24",issuedAt:null},preparedSubmission:{endpoint:"/documents/factura",canonicalBody:'{"safe":true}',requestHash:HASH,idempotencyKey:"billing-document:document-a:electronic-issuance:v1",metadata:{billingDocumentId:"document-a",tenantId:"tenant-a",documentTypeCode:"01",fiscalNumber:"00100001010000000042",fiscalIssueDate:"2026-08-24"}},providerState:{billingMode:"ELECTRONIC_PROVIDER",lifecycleStatus:"CONFIRMED",providerStatus:"PENDING",taxAuthorityStatus:"NOT_SUBMITTED",providerDocumentId:null,providerEnvironment:null,providerRequestHash:null,providerLastAttemptAt:null,providerLastErrorCode:null,providerLastErrorAt:null,providerReconciliationRequired:false,haciendaKey:null,submittedAt:null}};}
