import { Injectable, Logger, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { JobDispatcherService } from '../../infrastructure/job-dispatcher';
import { PLATFORM_QUEUE_KEYS } from '../../infrastructure/queue';
import { PrismaService } from '../../prisma/prisma.service';
import { BILLING_DOCUMENT_ARTIFACT_RETRIEVAL_REQUESTED_EVENT_TYPE, BILLING_DOCUMENT_ARTIFACT_RETRIEVAL_REQUESTED_EVENT_VERSION, FISCAL_TERMINAL_ARTIFACT_FANOUT_AGGREGATE_TYPE } from './fiscal-terminal-artifact-fanout.constants';
import { FISCAL_ARTIFACT_RETRIEVAL_BATCH_SIZE, FISCAL_ARTIFACT_RETRIEVAL_JOB_NAME, FISCAL_ARTIFACT_RETRIEVAL_LEASE_MS, FISCAL_ARTIFACT_RETRIEVAL_POLL_INTERVAL_MS, FISCAL_ARTIFACT_RETRIEVAL_RETRY_BASE_MS, FISCAL_ARTIFACT_RETRIEVAL_RETRY_MAX_MS, fiscalArtifactRetrievalJobId, type FiscalArtifactRetrievalJobPayload } from './fiscal-artifact-retrieval.constants';
import { logFiscalPollerFailure } from './fiscal-poller-error-logging';
interface Event { id:string; tenantId:string; eventType:string; eventVersion:number; aggregateType:string; aggregateId:string; causationId:string|null; payload:Prisma.JsonValue; attemptCount:number; maximumAttempts:number; lockOwner:string; }
const INVALID='FISCAL_ARTIFACT_RETRIEVAL_OUTBOX_INVALID', DISPATCH='FISCAL_ARTIFACT_RETRIEVAL_DISPATCH_FAILED';
@Injectable() export class FiscalArtifactRetrievalPublisher implements OnModuleInit, OnModuleDestroy {
 private readonly logger=new Logger(FiscalArtifactRetrievalPublisher.name); private timer:ReturnType<typeof setTimeout>|null=null; private active:Promise<void>|null=null; private stopping=false;
 constructor(private readonly prisma:PrismaService,private readonly dispatcher:JobDispatcherService){}
 onModuleInit(){this.schedule(0);} async onModuleDestroy(){this.stopping=true;if(this.timer)clearTimeout(this.timer);this.timer=null;await this.active;}
 async publishAvailableEvents(){for(const event of await this.claim()){try{await this.publish(event);}catch{this.logger.error('Fiscal artifact retrieval publishing failed.');}}}
 private schedule(delay:number){if(!this.stopping)this.timer=setTimeout(()=>{this.timer=null;void this.cycle();},delay);} private async cycle(){if(this.stopping||this.active)return;const cycle=this.publishAvailableEvents().catch(error=>{logFiscalPollerFailure(this.logger,'FiscalArtifactRetrievalPublisher',error);});this.active=cycle;try{await cycle;}finally{this.active=null;this.schedule(FISCAL_ARTIFACT_RETRIEVAL_POLL_INTERVAL_MS);}}
 private claim(){const now=new Date(),cutoff=new Date(now.getTime()-FISCAL_ARTIFACT_RETRIEVAL_LEASE_MS),claimToken=randomUUID();return this.prisma.$transaction(tx=>tx.$queryRaw<Event[]>`WITH eligible AS (SELECT "id" FROM "billing_outbox_events" WHERE "eventType"=${BILLING_DOCUMENT_ARTIFACT_RETRIEVAL_REQUESTED_EVENT_TYPE} AND "eventVersion"=${BILLING_DOCUMENT_ARTIFACT_RETRIEVAL_REQUESTED_EVENT_VERSION} AND "attemptCount" < "maximumAttempts" AND (("status"='PENDING' AND "availableAt"<=${now}) OR ("status"='PROCESSING' AND "lockedAt"<${cutoff})) ORDER BY "availableAt","createdAt" LIMIT ${FISCAL_ARTIFACT_RETRIEVAL_BATCH_SIZE} FOR UPDATE SKIP LOCKED) UPDATE "billing_outbox_events" e SET "status"='PROCESSING',"attemptCount"=e."attemptCount"+1,"lockedAt"=${now},"lockedBy"=concat(${claimToken},'-',e."id"),"lastAttemptAt"=${now},"updatedAt"=${now} FROM eligible WHERE e."id"=eligible."id" RETURNING e."id",e."tenantId",e."eventType",e."eventVersion",e."aggregateType",e."aggregateId",e."causationId",e."payload",e."attemptCount",e."maximumAttempts",e."lockedBy" AS "lockOwner"`);}
 private async publish(event:Event){const payload=valid(event,event.lockOwner);if(!payload){await this.finish(event,{status:'FAILED',lastError:INVALID});return;}try{await this.dispatcher.dispatch<FiscalArtifactRetrievalJobPayload>({queueKey:PLATFORM_QUEUE_KEYS.FISCAL_ARTIFACT_RETRIEVAL,jobName:FISCAL_ARTIFACT_RETRIEVAL_JOB_NAME,payload,metadata:{tenantId:event.tenantId},options:{jobId:fiscalArtifactRetrievalJobId(event.id,event.attemptCount,event.lockOwner),attempts:3,backoff:{type:'exponential',delay:2000},removeOnComplete:false,removeOnFail:false}});}catch{if(event.attemptCount>=event.maximumAttempts)await this.finish(event,{status:'FAILED',lastError:DISPATCH});else{const n=Math.min(FISCAL_ARTIFACT_RETRIEVAL_RETRY_BASE_MS*2**Math.min(Math.max(event.attemptCount-1,0),30),FISCAL_ARTIFACT_RETRIEVAL_RETRY_MAX_MS);await this.finish(event,{status:'PENDING',availableAt:new Date(Date.now()+n),lastError:DISPATCH});}}}
 private finish(event:Event,data:Prisma.BillingOutboxEventUpdateManyMutationInput){return this.prisma.billingOutboxEvent.updateMany({where:{id:event.id,tenantId:event.tenantId,status:'PROCESSING',lockedBy:event.lockOwner},data:{...data,lockedAt:null,lockedBy:null}});}
}
function valid(e:Event,owner:string):FiscalArtifactRetrievalJobPayload|null{if(e.eventType!==BILLING_DOCUMENT_ARTIFACT_RETRIEVAL_REQUESTED_EVENT_TYPE||e.eventVersion!==1||e.aggregateType!==FISCAL_TERMINAL_ARTIFACT_FANOUT_AGGREGATE_TYPE||!e.causationId||typeof e.payload!=='object'||e.payload===null||Array.isArray(e.payload)||Object.keys(e.payload).length!==5)return null;const p=e.payload as Record<string,unknown>;return p.tenantId===e.tenantId&&p.billingDocumentId===e.aggregateId&&(p.artifactType==='SIGNED_FISCAL_XML'||p.artifactType==='TAX_AUTHORITY_RESPONSE_XML')&&p.artifactVersion===1&&p.eventVersion===1&&owner?{tenantId:e.tenantId,outboxEventId:e.id,lockOwner:owner,eventVersion:1}:null;}
