-- AlterTable
ALTER TABLE "Contract" ALTER COLUMN "pdfObjectKey" DROP NOT NULL,
ALTER COLUMN "pdfFileName" DROP NOT NULL,
ALTER COLUMN "pdfMimeType" DROP NOT NULL,
ALTER COLUMN "pdfSize" DROP NOT NULL;
