'use client';

import { type FormEvent, type SyntheticEvent, useCallback, useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight, Search } from 'lucide-react';
import { listPassengerGroups, type PassengerGroup } from '@/lib/passenger-groups-api';
import { getOperationalPassengerCommercialContext, getOperationalPassengerRoster, listOperationalWorkItems, operationsErrorMessage, type OperationalAdditionalServiceContext, type OperationalPassengerRosterRow, type OperationalRequirementSummary, type OperationalWorkItem } from '@/lib/operations-api';
import { OperationalFulfillmentsWorkspace } from '@/components/operations/operational-fulfillments-workspace';
import { OperationalRequirementsWorkspace } from '@/components/operations/operational-requirements-workspace';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

type Mode = 'passenger' | 'group' | 'all';
const status: Record<OperationalWorkItem['status'], string> = { PENDING: 'Por gestionar', IN_PROGRESS: 'En gestión', FULFILLED: 'Completado', CANCELLED: 'Cancelado', NOT_APPLICABLE: 'No aplica' };

export function OperationalUnifiedWorkspace({ travelPackageId, onCoverageChanged }: { travelPackageId: string; onCoverageChanged?: () => void }) {
  const [mode, setMode] = useState<Mode>('passenger');
  const [allVisited, setAllVisited] = useState(false);
  const [groupDirectoryNeededFor, setGroupDirectoryNeededFor] = useState<string | null>(null);
  const [roster, setRoster] = useState<OperationalPassengerRosterRow[]>([]), [rosterLoading, setRosterLoading] = useState(true), [rosterError, setRosterError] = useState<string | null>(null), [searchDraft, setSearchDraft] = useState(''), [search, setSearch] = useState('');
  const [groups, setGroups] = useState<PassengerGroup[]>([]), [selectedPassengerId, setSelectedPassengerId] = useState<string | null>(null), [selectedGroupId, setSelectedGroupId] = useState<string | null>(null);
  const [work, setWork] = useState<OperationalWorkItem[]>([]), [workLoading, setWorkLoading] = useState(false), [workError, setWorkError] = useState<string | null>(null), [managed, setManaged] = useState<OperationalWorkItem | null>(null);
  const [workVersion, setWorkVersion] = useState(0);
  const [commercialContextByParticipant, setCommercialContextByParticipant] = useState<Record<string, OperationalAdditionalServiceContext[]>>({});
  const commercialRequests = useRef(new Map<string, Promise<OperationalAdditionalServiceContext[]>>());

  useEffect(() => { let live = true; setRosterLoading(true); setRosterError(null); void getOperationalPassengerRoster(travelPackageId, 1, search || undefined).then((page) => { if (!live) return; setRoster(page.items); setSelectedPassengerId((current) => page.items.some((p) => p.travelPackageParticipantId === current) ? current : page.items[0]?.travelPackageParticipantId ?? null); }).catch((reason) => { if (live) setRosterError(operationsErrorMessage(reason, 'No se pudo cargar el roster de pasajeros.')); }).finally(() => { if (live) setRosterLoading(false); }); return () => { live = false; }; }, [travelPackageId, search]);
  useEffect(() => { setCommercialContextByParticipant({}); commercialRequests.current.clear(); }, [travelPackageId]);
  useEffect(() => { setGroups([]); setSelectedGroupId(null); }, [travelPackageId]);
  useEffect(() => { if (groupDirectoryNeededFor !== travelPackageId) return; let live = true; void listPassengerGroups(travelPackageId).then((items) => { if (!live) return; const active = items.filter((group) => group.status === 'ACTIVE'); setGroups(active); setSelectedGroupId((current) => active.some((group) => group.id === current) ? current : active[0]?.id ?? null); }).catch(() => { if (live) setGroups([]); }); return () => { live = false; }; }, [groupDirectoryNeededFor, travelPackageId]);
  const selectedPassenger = roster.find((passenger) => passenger.travelPackageParticipantId === selectedPassengerId) ?? null;
  const selectedGroup = groups.find((group) => group.id === selectedGroupId) ?? null;
  const loadCommercialContext = useCallback((participantId: string) => {
    const cached = commercialContextByParticipant[participantId];
    if (cached) return Promise.resolve(cached);
    const pending = commercialRequests.current.get(participantId);
    if (pending) return pending;
    const request = getOperationalPassengerCommercialContext(travelPackageId, participantId).then((context) => { setCommercialContextByParticipant((current) => ({ ...current, [participantId]: context.additionalServices })); return context.additionalServices; }).finally(() => { commercialRequests.current.delete(participantId); });
    commercialRequests.current.set(participantId, request);
    return request;
  }, [commercialContextByParticipant, travelPackageId]);
  const workFilter = mode === 'passenger' ? (selectedPassengerId ? { participantId: selectedPassengerId } : null) : mode === 'group' ? (selectedGroupId ? { passengerGroupId: selectedGroupId } : null) : null;
  useEffect(() => { if (mode === 'all') return; if (!workFilter) { setWork([]); return; } let live = true; setWorkLoading(true); setWorkError(null); void listOperationalWorkItems(travelPackageId, { page: 1, active: true, ...workFilter }).then((result) => { if (live) setWork(result.items); }).catch((reason) => { if (live) setWorkError(operationsErrorMessage(reason, 'No se pudo cargar el trabajo operativo.')); }).finally(() => { if (live) setWorkLoading(false); }); return () => { live = false; }; }, [mode, selectedPassengerId, selectedGroupId, travelPackageId, workVersion]);
  if (managed) return <OperationalFulfillmentsWorkspace travelPackageId={travelPackageId} requirementId={managed.id} requirementCoverage={managed.coverage} onBack={() => { setManaged(null); setWorkVersion((version) => version + 1); }} onCoverageChanged={() => { setWorkVersion((version) => version + 1); onCoverageChanged?.(); }} />;
  const selectPassenger = (id: string) => { setSelectedPassengerId(id); setMode('passenger'); };
  const ensureGroupDirectory = () => setGroupDirectoryNeededFor(travelPackageId);
  const selectMode = (next: Mode) => { if (next === 'all') setAllVisited(true); if (next !== 'passenger') ensureGroupDirectory(); setMode(next); };
  const submitSearch = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSearch(searchDraft.trim()); };
  return <section className="space-y-4" aria-label="Operación"><div><h1 className="text-2xl font-semibold">Operación</h1><p className="text-sm text-muted-foreground">Navega por pasajeros, grupos o todos los trabajos. La ejecución siempre conserva la necesidad compartida.</p></div><div className="flex flex-wrap gap-2" role="tablist" aria-label="Vistas de operación"><Button type="button" size="sm" role="tab" aria-selected={mode === 'passenger'} variant={mode === 'passenger' ? 'default' : 'outline'} onClick={() => selectMode('passenger')}>Por pasajero</Button><Button type="button" size="sm" role="tab" aria-selected={mode === 'group'} variant={mode === 'group' ? 'default' : 'outline'} onClick={() => selectMode('group')}>Por grupo</Button><Button type="button" size="sm" role="tab" aria-selected={mode === 'all'} variant={mode === 'all' ? 'default' : 'outline'} onClick={() => selectMode('all')}>Todos los trabajos</Button></div>
    {allVisited ? <div hidden={mode !== 'all'}><OperationalRequirementsWorkspace travelPackageId={travelPackageId} refreshVersion={workVersion} groups={groups} passengerOptions={roster.map((passenger) => ({ id: passenger.travelPackageParticipantId, fullName: passenger.fullName }))} onManageFulfillments={(item) => setManaged(item as unknown as OperationalWorkItem)} /></div> : null}
    {mode === 'passenger' ? <div className="grid gap-4 lg:grid-cols-[minmax(16rem,0.8fr)_minmax(0,2fr)]"><Roster roster={roster} loading={rosterLoading} error={rosterError} searchDraft={searchDraft} selectedId={selectedPassengerId} onSearchDraft={setSearchDraft} onSubmit={submitSearch} onSelect={selectPassenger} /><PassengerDetail passenger={selectedPassenger} work={work} loading={workLoading} error={workError} commercialServices={selectedPassenger ? commercialContextByParticipant[selectedPassenger.travelPackageParticipantId] : undefined} onLoadCommercial={loadCommercialContext} onManage={setManaged} onGroup={(id) => { ensureGroupDirectory(); setSelectedGroupId(id); setMode('group'); }} onPrevious={() => move(roster, selectedPassengerId, -1, selectPassenger)} onNext={() => move(roster, selectedPassengerId, 1, selectPassenger)} /></div> : null}
    {mode === 'group' ? <div className="grid gap-4 lg:grid-cols-[minmax(16rem,0.8fr)_minmax(0,2fr)]"><GroupList groups={groups} selectedId={selectedGroupId} onSelect={setSelectedGroupId} /><GroupDetail group={selectedGroup} work={work} loading={workLoading} error={workError} onManage={setManaged} onMember={selectPassenger} /></div> : null}
  </section>;
}

function Roster({ roster, loading, error, searchDraft, selectedId, onSearchDraft, onSubmit, onSelect }: { roster: OperationalPassengerRosterRow[]; loading: boolean; error: string | null; searchDraft: string; selectedId: string | null; onSearchDraft: (value: string) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onSelect: (id: string) => void }) { return <Card><CardContent className="space-y-3 py-4"><div><h2 className="font-semibold">Pasajeros</h2><p className="text-sm text-muted-foreground">Roster del viaje</p></div><form className="flex gap-2" onSubmit={onSubmit}><Input value={searchDraft} onChange={(event) => onSearchDraft(event.target.value)} placeholder="Buscar pasajero" aria-label="Buscar pasajero" /><Button type="submit" variant="outline" size="icon" aria-label="Buscar pasajero"><Search aria-hidden="true" /></Button></form>{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}{loading ? <p className="text-sm text-muted-foreground">Cargando pasajeros...</p> : roster.length ? <div className="space-y-1">{roster.map((passenger) => <Button key={passenger.travelPackageParticipantId} type="button" variant={selectedId === passenger.travelPackageParticipantId ? 'secondary' : 'ghost'} className="h-auto w-full justify-start px-2 py-2 text-left" onClick={() => onSelect(passenger.travelPackageParticipantId)}><span><span className="block font-medium">{passenger.fullName}</span><span className="block text-xs text-muted-foreground">{passenger.role} · {passenger.groups.length ? passenger.groups.map((group) => group.name).join(', ') : 'Sin grupo'} · {passenger.progress.fulfilled}/{passenger.progress.total}</span></span></Button>)}</div> : <p className="text-sm text-muted-foreground">No hay pasajeros para esta búsqueda.</p>}</CardContent></Card>; }
function PassengerDetail({ passenger, work, loading, error, commercialServices, onLoadCommercial, onManage, onGroup, onPrevious, onNext }: { passenger: OperationalPassengerRosterRow | null; work: OperationalWorkItem[]; loading: boolean; error: string | null; commercialServices: OperationalAdditionalServiceContext[] | undefined; onLoadCommercial: (participantId: string) => Promise<OperationalAdditionalServiceContext[]>; onManage: (item: OperationalWorkItem) => void; onGroup: (id: string) => void; onPrevious: () => void; onNext: () => void }) { if (!passenger) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Selecciona un pasajero para revisar su trabajo operativo.</CardContent></Card>; return <div className="space-y-4"><Card><CardContent className="space-y-2 py-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h2 className="text-xl font-semibold">{passenger.fullName}</h2><p className="text-sm text-muted-foreground">{passenger.role} · Avance {passenger.progress.fulfilled}/{passenger.progress.total}{passenger.progress.percent === null ? '' : ` · ${passenger.progress.percent}%`}</p></div><div className="flex gap-1"><Button type="button" size="sm" variant="outline" onClick={onPrevious}><ChevronLeft aria-hidden="true" />Anterior</Button><Button type="button" size="sm" variant="outline" onClick={onNext}>Siguiente<ChevronRight aria-hidden="true" /></Button></div></div><div className="flex flex-wrap gap-1">{passenger.groups.length ? passenger.groups.map((group) => <Button key={group.id} type="button" size="sm" variant="outline" onClick={() => onGroup(group.id)}>Grupo: {group.name}</Button>) : <span className="text-sm text-muted-foreground">Sin grupos activos.</span>}</div></CardContent></Card><section className="space-y-3"><div><h2 className="text-xl font-semibold">Trabajo operativo</h2><p className="text-sm text-muted-foreground">Necesidades operativas que aplican a este pasajero.</p></div><WorkList work={work} loading={loading} error={error} onManage={onManage} empty="Este pasajero no tiene trabajo operativo pendiente." /></section><PassengerCommercialContext participantId={passenger.travelPackageParticipantId} services={commercialServices} onLoad={onLoadCommercial} /></div>; }
function GroupList({ groups, selectedId, onSelect }: { groups: PassengerGroup[]; selectedId: string | null; onSelect: (id: string) => void }) { return <Card><CardContent className="space-y-2 py-4"><div><h2 className="font-semibold">Grupos de pasajeros</h2><p className="text-sm text-muted-foreground">Grupos activos del viaje</p></div>{groups.length ? groups.map((group) => <Button key={group.id} type="button" variant={selectedId === group.id ? 'secondary' : 'ghost'} className="h-auto w-full justify-start px-2 py-2 text-left" onClick={() => onSelect(group.id)}><span><span className="flex items-center gap-2 font-medium"><span aria-hidden="true" className="size-2 rounded-full" style={{ backgroundColor: group.color || 'currentColor' }} />{group.name}</span><span className="block text-xs text-muted-foreground">{group.serviceName} · {group.members.length} pasajeros</span></span></Button>) : <p className="text-sm text-muted-foreground">No hay grupos activos.</p>}</CardContent></Card>; }
function GroupDetail({ group, work, loading, error, onManage, onMember }: { group: PassengerGroup | null; work: OperationalWorkItem[]; loading: boolean; error: string | null; onManage: (item: OperationalWorkItem) => void; onMember: (id: string) => void }) { if (!group) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Selecciona un grupo para revisar su trabajo operativo.</CardContent></Card>; return <div className="space-y-4"><Card><CardContent className="py-4"><h2 className="text-xl font-semibold">{group.name}</h2><p className="text-sm text-muted-foreground">{group.serviceName} · {group.members.length} pasajeros</p><div className="mt-3 flex flex-wrap gap-2">{group.members.map((member) => <Button key={member.travelPackageParticipantId} type="button" size="sm" variant="outline" onClick={() => onMember(member.travelPackageParticipantId)}>{member.fullName}</Button>)}</div></CardContent></Card><section className="space-y-3"><div><h2 className="text-xl font-semibold">Trabajo operativo</h2><p className="text-sm text-muted-foreground">Trabajo relevante para los miembros de este grupo.</p></div><WorkList work={work} loading={loading} error={error} onManage={onManage} empty="Este grupo no tiene trabajo operativo pendiente." /></section></div>; }
function PassengerCommercialContext({ participantId, services, onLoad }: { participantId: string; services: OperationalAdditionalServiceContext[] | undefined; onLoad: (participantId: string) => Promise<OperationalAdditionalServiceContext[]> }) { const [open, setOpen] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState<string | null>(null); useEffect(() => { setOpen(false); setLoading(false); setError(null); }, [participantId]); const toggle = (event: SyntheticEvent<HTMLDetailsElement>) => { const next = event.currentTarget.open; setOpen(next); if (!next || services || loading) return; setLoading(true); setError(null); void onLoad(participantId).catch((reason) => { setError(operationsErrorMessage(reason, 'No se pudo cargar el contexto comercial.')); }).finally(() => setLoading(false)); }; return <details className="rounded-md border border-border p-3" open={open} onToggle={toggle}><summary className="cursor-pointer font-medium">Contexto comercial</summary>{open ? <div className="mt-3 space-y-2 text-sm">{loading ? <p className="text-muted-foreground">Cargando contexto comercial...</p> : error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : services?.length ? services.map((service) => <div key={service.sourceRef.lineId}><p className="font-medium">{service.presentation.title ?? service.serviceName}</p><p className="text-muted-foreground">{service.presentation.subtitle ?? service.presentation.fields.map((field) => `${field.label}: ${field.value}`).join(' · ')}</p></div>) : <p className="text-muted-foreground">No hay servicios vendidos para mostrar.</p>}</div> : null}</details>; }
function WorkList({ work, loading, error, onManage, empty }: { work: OperationalWorkItem[]; loading: boolean; error: string | null; onManage: (item: OperationalWorkItem) => void; empty: string }) { if (loading) return <Card><CardContent className="py-8 text-sm text-muted-foreground">Cargando trabajo operativo...</CardContent></Card>; if (error) return <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>; if (!work.length) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">{empty}</CardContent></Card>; return <div className="grid gap-3">{work.map((item) => <Card key={item.id}><CardContent className="space-y-2 py-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{item.servicePurposeName}</h3><p className="text-sm text-muted-foreground">{item.description}</p></div><Badge variant={item.status === 'FULFILLED' ? 'success' : item.status === 'CANCELLED' ? 'destructive' : item.status === 'IN_PROGRESS' ? 'info' : 'outline'}>{status[item.status]}</Badge></div>{item.soldContext.scope === 'EXACT_SERVICE_LINE' && item.soldContext.amount && item.soldContext.currency ? <p className="text-sm">Vendido: {item.soldContext.currency} {item.soldContext.amount}</p> : null}<div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><span>Aplica a {item.passengers.total} pasajeros</span><span>Cobertura general: {item.coverage.fulfilledPassengerCount}/{item.coverage.totalPassengerCount} confirmados</span>{item.participantCoverageStatus ? <span>Estado del pasajero: {item.participantCoverageStatus === 'FULFILLED' ? 'Confirmado' : 'Pendiente'}</span> : null}{item.critical ? <span className="text-destructive">Crítico</span> : null}{item.operationalDeadlineAt ? <span>Fecha límite: {item.operationalDeadlineAt}</span> : null}<span>{item.management.fulfillmentCount} gestiones · {item.management.purchaseCount} compras · {item.management.evidenceCount} documentos</span></div><Button type="button" onClick={() => onManage(item)}>Gestionar</Button></CardContent></Card>)}</div>; }
function move(roster: OperationalPassengerRosterRow[], current: string | null, direction: number, select: (id: string) => void) { const index = roster.findIndex((passenger) => passenger.travelPackageParticipantId === current); const next = roster[index + direction]; if (next) select(next.travelPackageParticipantId); }
