'use client';

import { type FormEvent, useEffect, useRef, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { getOperationalRequirement, listOperationalWorkItems, operationsErrorMessage, type OperationalRequirementDetail, type OperationalRequirementStatus, type OperationalRequirementSummary, type OperationalWorkItem, type OperationalWorkSourceCategory } from '@/lib/operations-api';
import { type PassengerGroup } from '@/lib/passenger-groups-api';
import { useTenantDateTimeFormatter } from '@/shared/regional/tenant-regional-provider';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { OperationalWorkSourceBadge } from '@/components/operations/operational-work-source-badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';

const SERVICES = [['LODGING', 'Hospedaje'], ['FLIGHT_TICKET', 'Boletos aéreos'], ['TRANSPORTATION', 'Transporte'], ['TOUR', 'Tours'], ['EVENT_TICKET', 'Boletos para eventos'], ['SEAT_SELECTION', 'Selección de asiento'], ['BAGGAGE', 'Equipaje'], ['INSURANCE', 'Seguro'], ['OTHER', 'Otros']] as const;
const statusLabels: Record<OperationalRequirementStatus, string> = { PENDING: 'Por gestionar', IN_PROGRESS: 'En gestión', FULFILLED: 'Completado', CANCELLED: 'Cancelado', NOT_APPLICABLE: 'No aplica' };
type RosterPassenger = { id: string; fullName: string };
type QueueNeed = OperationalWorkItem;

export function OperationalRequirementsWorkspace({ travelPackageId, refreshVersion, groups, passengerOptions, sourceCategory = 'ALL', onSourceCategoryChange, onManageFulfillments, onViewPassengers }: { travelPackageId: string; refreshVersion?: number; groups: PassengerGroup[]; passengerOptions: RosterPassenger[]; sourceCategory?: OperationalWorkSourceCategory; onSourceCategoryChange?: (value: OperationalWorkSourceCategory) => void; onManageFulfillments?: (requirement: OperationalRequirementSummary) => void; onViewPassengers?: () => void }) {
  const formatTenantDateTime = useTenantDateTimeFormatter();
  const [data, setData] = useState<{ items: QueueNeed[]; page: number; totalPages: number } | null>(null);
  const [page, setPage] = useState(1), [status, setStatus] = useState<OperationalRequirementStatus | ''>(''), [service, setService] = useState(''), [critical, setCritical] = useState(''), [searchDraft, setSearchDraft] = useState(''), [search, setSearch] = useState(''), [active, setActive] = useState(true), [deadlineState, setDeadlineState] = useState<'' | 'OVERDUE' | 'DUE_SOON' | 'FUTURE' | 'NONE'>(''), [groupId, setGroupId] = useState(''), [participantId, setParticipantId] = useState(''), [filterPassengerSearch, setFilterPassengerSearch] = useState('');
  const [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [detailTarget, setDetailTarget] = useState<OperationalRequirementDetail | null>(null);
  const loadedSourceCategory = useRef(sourceCategory);

  async function load() {
    setLoading(true); setError(null);
    try {
      const result = await listOperationalWorkItems(travelPackageId, { page, active, status: status || undefined, servicePurposeCode: service || undefined, passengerGroupId: groupId || undefined, participantId: participantId || undefined, critical: critical === '' ? undefined : critical === 'true', deadlineState: deadlineState || undefined, sourceCategory, search });
      setData(result);
    } catch (reason) { setError(operationsErrorMessage(reason, 'No se pudo cargar el trabajo operativo.')); } finally { setLoading(false); }
  }
  useEffect(() => { if (loadedSourceCategory.current !== sourceCategory) { loadedSourceCategory.current = sourceCategory; setPage(1); return; } void load(); }, [page, status, service, critical, search, active, deadlineState, groupId, participantId, sourceCategory, travelPackageId, refreshVersion]);
  const filterRoster = passengerOptions.filter((passenger) => passenger.fullName.toLowerCase().includes(filterPassengerSearch.toLowerCase()));
  function applyFilters(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPage(1); setSearch(searchDraft.trim()); }
  async function openDetail(item: OperationalRequirementSummary) { try { setDetailTarget(await getOperationalRequirement(travelPackageId, item.id)); } catch (reason) { setError(operationsErrorMessage(reason, 'No se pudo abrir el detalle de la necesidad.')); } }
  const needs = data?.items ?? [];
  const hasAppliedFilters = !active || sourceCategory !== 'ALL' || Boolean(status || service || critical || search || deadlineState || groupId || participantId);
  function clearFilters() { setPage(1); setActive(true); setStatus(''); setService(''); setGroupId(''); setParticipantId(''); setCritical(''); setDeadlineState(''); setSearchDraft(''); setSearch(''); onSourceCategoryChange?.('ALL'); }

  return <section className="space-y-4" aria-label="Trabajo operativo">
    <div><h2 className="text-xl font-semibold">Trabajo operativo</h2><p className="text-sm text-muted-foreground">Da seguimiento a los servicios aprobados que deben ejecutarse para este viaje.</p></div>
    <form className="space-y-2" onSubmit={applyFilters}>
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Input value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} placeholder="Buscar servicio o descripción" aria-label="Buscar trabajo operativo" /><Select value={active ? 'ACTIVE' : 'ALL'} onChange={(event) => { setPage(1); setActive(event.target.value === 'ACTIVE'); setStatus(''); }} aria-label="Vista de trabajo operativo"><option value="ACTIVE">Activos</option><option value="ALL">Todos</option></Select><Select value={service} onChange={(event) => { setPage(1); setService(event.target.value); }} aria-label="Filtrar por servicio"><option value="">Todos los servicios</option>{SERVICES.map(([code, label]) => <option key={code} value={code}>{label}</option>)}</Select><Select value={groupId} onChange={(event) => { setPage(1); setGroupId(event.target.value); }} aria-label="Filtrar por grupo"><option value="">Todos los grupos</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</Select></div>
      <details className="rounded-md border border-border px-3 py-2"><summary className="cursor-pointer text-sm font-medium">Más filtros</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Select value={status} onChange={(event) => { setPage(1); setActive(false); setStatus(event.target.value as OperationalRequirementStatus | ''); }} aria-label="Filtrar por estado"><option value="">Todos los estados</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select><div className="grid grid-cols-2 gap-2"><Input value={filterPassengerSearch} onChange={(event) => setFilterPassengerSearch(event.target.value)} placeholder="Buscar pasajero" aria-label="Buscar pasajero" /><Select value={participantId} onChange={(event) => { setPage(1); setParticipantId(event.target.value); }} aria-label="Filtrar por pasajero"><option value="">Todos los pasajeros</option>{filterRoster.map((passenger) => <option key={passenger.id} value={passenger.id}>{passenger.fullName}</option>)}</Select></div><Select value={critical} onChange={(event) => { setPage(1); setCritical(event.target.value); }} aria-label="Filtrar por criticidad"><option value="">Todas las prioridades</option><option value="true">Críticas</option><option value="false">No críticas</option></Select><Select value={deadlineState} onChange={(event) => { setPage(1); setDeadlineState(event.target.value as typeof deadlineState); }} aria-label="Filtrar por fecha límite"><option value="">Todas las fechas</option><option value="OVERDUE">Vencidas</option><option value="DUE_SOON">Próximas a vencer</option><option value="FUTURE">Futuras</option><option value="NONE">Sin fecha</option></Select></div></details>
      <div className="flex flex-wrap gap-2"><Button type="submit" variant="outline">Aplicar filtros</Button>{hasAppliedFilters ? <Button type="button" variant="ghost" onClick={clearFilters}>Limpiar filtros</Button> : null}</div>
    </form>
    {error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}
    {loading ? <Card><CardContent className="py-10 text-sm text-muted-foreground">Cargando trabajo operativo...</CardContent></Card> : needs.length === 0 ? <Card><CardContent className="py-12 text-center">{sourceCategory !== 'ALL' ? <><p className="font-medium">No hay trabajos de este origen para esta vista.</p><div className="mt-4"><Button type="button" variant="outline" onClick={clearFilters}>Limpiar filtros</Button></div></> : hasAppliedFilters ? <><p className="font-medium">No hay trabajo operativo que coincida con los filtros seleccionados.</p><div className="mt-4"><Button type="button" variant="outline" onClick={clearFilters}>Limpiar filtros</Button></div></> : <><p className="font-medium">No hay trabajo operativo pendiente.</p><p className="mt-1 text-sm text-muted-foreground">Los servicios aprobados desde Contratos, Servicios adicionales o Cotizaciones personalizadas aparecerán aquí para su gestión.</p><div className="mt-4"><Button type="button" variant="outline" onClick={onViewPassengers}>Ver pasajeros</Button></div></>}</CardContent></Card> : <div className="grid gap-3">{needs.map((item) => <NeedCard key={item.id} item={item} formatDateTime={formatTenantDateTime} onManage={onManageFulfillments ? () => onManageFulfillments(item as unknown as OperationalRequirementSummary) : undefined} onDetail={() => void openDetail(item as unknown as OperationalRequirementSummary)} />)}</div>}
    {data && data.totalPages > 1 ? <div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Página {data.page} de {data.totalPages}</span><div className="flex gap-2"><Button type="button" variant="outline" size="sm" disabled={loading || page <= 1} onClick={() => setPage((value) => value - 1)}><ChevronLeft aria-hidden="true" />Anterior</Button><Button type="button" variant="outline" size="sm" disabled={loading || page >= data.totalPages} onClick={() => setPage((value) => value + 1)}>Siguiente<ChevronRight aria-hidden="true" /></Button></div></div> : null}
    <Dialog open={detailTarget !== null} onOpenChange={(open) => !open && setDetailTarget(null)}><DialogContent><DialogHeader><DialogTitle>Necesidad operativa</DialogTitle><DialogDescription>{detailTarget?.servicePurposeName}</DialogDescription></DialogHeader>{detailTarget ? <dl className="grid gap-3 text-sm"><Detail label="Descripción" value={detailTarget.description} /><Detail label="Pasajeros" value={detailTarget.passengers.map((passenger) => passenger.fullName).join(', ')} /><Detail label="Estado" value={statusLabels[detailTarget.status]} /><Detail label="Cobertura" value={`${detailTarget.coverage.fulfilledPassengerCount}/${detailTarget.coverage.totalPassengerCount} confirmados`} /><Detail label="Prioridad" value={detailTarget.critical ? 'Crítico para el viaje' : 'Normal'} /><Detail label="Fecha límite" value={detailTarget.operationalDeadlineAt ? formatTenantDateTime(detailTarget.operationalDeadlineAt) : 'Sin fecha límite'} />{detailTarget.soldValue.scope === 'EXACT_SERVICE_LINE' && detailTarget.soldValue.amount && detailTarget.soldValue.currency ? <Detail label="Contexto comercial" value={`Vendido: ${detailTarget.soldValue.currency} ${detailTarget.soldValue.amount}`} /> : null}</dl> : null}<DialogFooter><Button type="button" onClick={() => setDetailTarget(null)}>Cerrar</Button></DialogFooter></DialogContent></Dialog>
  </section>;
}

function NeedCard({ item, formatDateTime, onManage, onDetail }: { item: QueueNeed; formatDateTime: (value: string) => string; onManage?: () => void; onDetail: () => void }) {
  const rollup = [item.management.fulfillmentCount ? `${item.management.fulfillmentCount} ${item.management.fulfillmentCount === 1 ? 'gestión' : 'gestiones'}` : null, item.management.purchaseCount ? `${item.management.purchaseCount} ${item.management.purchaseCount === 1 ? 'compra' : 'compras'}` : null, item.management.evidenceCount ? `${item.management.evidenceCount} ${item.management.evidenceCount === 1 ? 'documento' : 'documentos'}` : null].filter(Boolean).join(' · ');
  return <Card><CardContent className="space-y-3 py-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{item.servicePurposeName}</h3><div className="mt-1"><OperationalWorkSourceBadge sourceCategory={item.sourceCategory} /></div><p className="text-sm text-muted-foreground">{item.passengers.preview.map((passenger) => passenger.fullName).join(', ')}{item.passengers.total > item.passengers.preview.length ? ` +${item.passengers.total - item.passengers.preview.length}` : ''} · {item.passengers.total} pasajeros</p>{item.sourceGroup?.name ? <p className="mt-1 text-xs text-muted-foreground">Grupo origen: {item.sourceGroup.name}</p> : null}</div><Badge variant={item.status === 'FULFILLED' ? 'success' : item.status === 'CANCELLED' ? 'destructive' : item.status === 'IN_PROGRESS' ? 'info' : 'outline'}>{statusLabels[item.status]}</Badge></div><p className="text-sm">{item.description}</p><div className="flex flex-wrap gap-2 text-xs text-muted-foreground">{item.critical ? <span className="font-medium text-destructive">Crítico</span> : null}{item.operationalDeadlineAt ? <span>Vence: {formatDateTime(item.operationalDeadlineAt)}</span> : null}<span>Cobertura: {item.coverage.fulfilledPassengerCount}/{item.coverage.totalPassengerCount} confirmados</span>{rollup ? <span>{rollup}</span> : <span>Sin gestión iniciada</span>}<span>{item.finance.state === 'ELIGIBLE' ? 'Compra habilitada' : item.finance.state === 'BLOCKED' ? 'Compra bloqueada' : 'Información financiera no disponible'}</span></div>{item.soldContext.scope === 'EXACT_SERVICE_LINE' && item.soldContext.amount && item.soldContext.currency ? <p className="text-sm text-muted-foreground">Vendido: {item.soldContext.currency} {item.soldContext.amount}</p> : null}<div className="flex flex-wrap gap-2"><Button type="button" onClick={onManage}>Gestionar</Button><Button type="button" variant="outline" onClick={onDetail}>Ver detalle</Button></div></CardContent></Card>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd>{value || '—'}</dd></div>; }
