'use client';

import { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, CircleX, Info, RefreshCw, TriangleAlert } from 'lucide-react';
import { getOperationsPassengerMatrix, getOperationsReadiness, operationsErrorMessage, type OperationalHeatmapStatus, type OperationalPassengerMatrix, type OperationalReadiness } from '@/lib/operations-api';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

const readinessPresentation = {
  READY: { label: 'Listo', description: 'Todos los requerimientos críticos aplicables están cubiertos.', icon: CheckCircle2, variant: 'success' as const },
  AT_RISK: { label: 'En riesgo', description: 'Hay requerimientos críticos pendientes próximos a vencer o vencidos.', icon: TriangleAlert, variant: 'warning' as const },
  NOT_READY: { label: 'No listo', description: 'Hay requerimientos críticos pendientes.', icon: CircleX, variant: 'destructive' as const },
  NO_CRITICAL_REQUIREMENTS: { label: 'Sin críticos definidos', description: 'No hay requerimientos críticos definidos para este viaje.', icon: Info, variant: 'outline' as const },
};
const cellPresentation: Record<OperationalHeatmapStatus, { label: string; short: string; variant: 'success' | 'info' | 'warning' | 'secondary' | 'outline' }> = {
  FULFILLED: { label: 'Comprado', short: 'Comprado', variant: 'success' }, IN_PROGRESS: { label: 'En gestión', short: 'En gestión', variant: 'info' },
  PENDING: { label: 'Pendiente', short: 'Pendiente', variant: 'warning' }, NOT_APPLICABLE: { label: 'No aplica', short: 'No aplica', variant: 'secondary' }, NONE: { label: 'Sin requerimiento', short: 'Sin requerimiento', variant: 'outline' },
};

export function OperationalReadinessDashboard({ travelPackageId, refreshVersion, onViewPassengers }: { travelPackageId: string; refreshVersion?: number; onViewPassengers?: () => void }) {
  const [readiness, setReadiness] = useState<OperationalReadiness | null>(null);
  const [matrix, setMatrix] = useState<OperationalPassengerMatrix | null>(null);
  const [matrixPage, setMatrixPage] = useState(1);
  const [loadingReadiness, setLoadingReadiness] = useState(true), [loadingMatrix, setLoadingMatrix] = useState(true);
  const [readinessError, setReadinessError] = useState<string | null>(null), [matrixError, setMatrixError] = useState<string | null>(null);
  async function loadReadiness() { setLoadingReadiness(true); setReadinessError(null); try { setReadiness(await getOperationsReadiness(travelPackageId)); } catch (reason) { setReadinessError(errorMessage(reason, 'No se pudo cargar el resumen de preparación.')); } finally { setLoadingReadiness(false); } }
  async function loadMatrix() { setLoadingMatrix(true); setMatrixError(null); try { setMatrix(await getOperationsPassengerMatrix(travelPackageId, matrixPage)); } catch (reason) { setMatrixError(errorMessage(reason, 'No se pudo cargar la matriz de pasajeros.')); } finally { setLoadingMatrix(false); } }
  useEffect(() => { void loadReadiness(); }, [travelPackageId, refreshVersion]);
  useEffect(() => { void loadMatrix(); }, [travelPackageId, matrixPage, refreshVersion]);
  async function refresh() { await Promise.all([loadReadiness(), loadMatrix()]); }

  return <section className="space-y-5" aria-label="Resumen operativo"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">Resumen operativo</h1><p className="text-sm text-muted-foreground">Cobertura confirmada, riesgos críticos y preparación por pasajero.</p></div><Button type="button" variant="outline" onClick={() => void refresh()} disabled={loadingReadiness || loadingMatrix}><RefreshCw aria-hidden="true" className={loadingReadiness || loadingMatrix ? 'animate-spin' : ''} />Actualizar</Button></div>
    {readinessError ? <Alert variant="destructive"><AlertTitle>No se pudo cargar el resumen</AlertTitle><AlertDescription>{readinessError} <Button type="button" variant="link" className="h-auto px-1" onClick={() => void loadReadiness()}>Reintentar</Button></AlertDescription></Alert> : null}
    {loadingReadiness ? <Card><CardContent className="py-10 text-sm text-muted-foreground">Cargando preparación operativa...</CardContent></Card> : readiness ? <ReadinessSummary readiness={readiness} onViewPassengers={onViewPassengers} /> : null}
    <section className="space-y-3"><div><h2 className="text-xl font-semibold">Matriz de pasajeros</h2><p className="text-sm text-muted-foreground">Cada estado viene de la cobertura operativa confirmada por el backend.</p></div>{matrixError ? <Alert variant="destructive"><AlertTitle>No se pudo cargar la matriz</AlertTitle><AlertDescription>{matrixError} <Button type="button" variant="link" className="h-auto px-1" onClick={() => void loadMatrix()}>Reintentar</Button></AlertDescription></Alert> : null}{loadingMatrix ? <Card><CardContent className="py-10 text-sm text-muted-foreground">Cargando matriz de pasajeros...</CardContent></Card> : matrix ? <PassengerHeatmap matrix={matrix} onPage={setMatrixPage} /> : null}</section>
  </section>;
}

function ReadinessSummary({ readiness, onViewPassengers }: { readiness: OperationalReadiness; onViewPassengers?: () => void }) {
  const state = readinessPresentation[readiness.readinessState]; const StateIcon = state.icon; const overall = readiness.overall;
  return <div className="space-y-4">{overall.totalAssignments === 0 ? <Card><CardContent className="flex flex-col gap-4 py-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">No hay trabajo operativo pendiente.</p><p className="mt-1 text-sm text-muted-foreground">Los servicios aprobados desde Contratos, Servicios adicionales o Cotizaciones personalizadas aparecerán aquí para su gestión.</p></div><Button type="button" variant="outline" onClick={onViewPassengers}>Ver pasajeros</Button></CardContent></Card> : null}<Card><CardContent className="flex flex-col gap-4 py-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-3"><StateIcon aria-hidden="true" className="mt-0.5 text-primary" size={28} /><div><Badge variant={state.variant}>{state.label}</Badge><p className="mt-2 text-sm text-muted-foreground">{state.description}</p></div></div><div className="min-w-56"><p className="text-sm font-medium">Preparación operativa</p>{overall.progressPercent === null ? <p className="mt-1 text-sm text-muted-foreground">Sin necesidades operativas</p> : <><div className="mt-2 flex justify-between text-sm"><span>{overall.fulfilledAssignments}/{overall.totalAssignments} asignaciones</span><span className="font-semibold">{overall.progressPercent}%</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${overall.progressPercent}%` }} /></div></>}</div></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Pasajeros completos" value={`${overall.completePassengerCount} de ${overall.participantCountWithRequirements}`} detail="con requerimientos" /><Metric label="Total pasajeros" value={String(overall.totalRosterPassengerCount)} detail="en el roster" /><Metric label="Asignaciones pendientes" value={String(overall.pendingAssignments)} detail="aún sin cobertura confirmada" /><Metric label="Críticos pendientes" value={String(readiness.critical.pending)} detail={`${readiness.critical.dueSoon} próximos · ${readiness.critical.overdue} vencidos`} /></div>
    {readiness.inconsistency.fulfilledRequirementWithoutCoverageCount > 0 ? <Alert variant="warning"><AlertCircle aria-hidden="true" /><AlertTitle>Inconsistencia de cobertura</AlertTitle><AlertDescription>Se detectaron {readiness.inconsistency.fulfilledRequirementWithoutCoverageCount} requerimientos marcados como cumplidos cuya cobertura confirmada está incompleta.</AlertDescription></Alert> : null}
    <Card><CardHeader><CardTitle className="text-base">Avance por servicio</CardTitle></CardHeader><CardContent>{readiness.services.length ? <Table><TableHeader><TableRow><TableHead>Servicio</TableHead><TableHead>Avance</TableHead><TableHead>Completado</TableHead><TableHead>Pendiente</TableHead></TableRow></TableHeader><TableBody>{readiness.services.map((service) => <TableRow key={service.servicePurposeCode}><TableCell><div className="font-medium">{service.servicePurposeName}</div></TableCell><TableCell>{service.progressPercent === null ? 'Sin necesidades' : `${service.progressPercent}%`}</TableCell><TableCell>{service.fulfilledAssignments} / {service.totalAssignments}</TableCell><TableCell>{service.pendingAssignments}</TableCell></TableRow>)}</TableBody></Table> : <p className="py-4 text-sm text-muted-foreground">Este viaje aún no tiene trabajo operativo.</p>}</CardContent></Card>
  </div>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card><CardContent className="py-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></CardContent></Card>; }

function PassengerHeatmap({ matrix, onPage }: { matrix: OperationalPassengerMatrix; onPage: (page: number) => void }) {
  if (!matrix.items.length) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">No hay pasajeros registrados en este viaje.</CardContent></Card>;
  if (!matrix.serviceColumns.length) return <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Aún no hay servicios operativos que requieran seguimiento.</CardContent></Card>;
  const indexedParticipants = matrix.items.map((participant) => ({ participant, cellsByService: new Map(participant.serviceCells.map((cell) => [cell.servicePurposeCode, cell])) }));
  return <div className="space-y-3"><Card><CardContent className="max-h-[620px] overflow-auto p-0"><Table className="min-w-max"><TableHeader className="sticky top-0 z-20 bg-background"><TableRow><TableHead className="sticky left-0 z-30 min-w-56 bg-background">Pasajero</TableHead>{matrix.serviceColumns.map((column) => <TableHead key={column.servicePurposeCode} className="min-w-28 text-center"><span title={column.servicePurposeName}>{column.servicePurposeName}</span></TableHead>)}<TableHead className="min-w-28 text-center">Avance</TableHead></TableRow></TableHeader><TableBody>{indexedParticipants.map(({ participant, cellsByService }) => <TableRow key={participant.travelPackageParticipantId}><TableCell className="sticky left-0 z-10 bg-background"><div className="font-medium">{participant.fullName}</div><div className="text-xs text-muted-foreground">{participant.role}</div></TableCell>{matrix.serviceColumns.map((column) => { const cell = cellsByService.get(column.servicePurposeCode); const presentation = cellPresentation[cell?.status ?? 'NONE']; return <TableCell key={column.servicePurposeCode} className="text-center"><Badge variant={presentation.variant} aria-label={`${participant.fullName}: ${column.servicePurposeName}, ${presentation.label}`} title={presentation.label}>{presentation.short}<span className="sr-only"> {presentation.label}</span></Badge></TableCell>; })}<TableCell className="text-center">{participant.progressPercent === null ? <span className="text-xs text-muted-foreground">Sin requerimientos</span> : <span>{participant.fulfilledRequirementCount}/{participant.requirementCount} · {participant.progressPercent}%</span>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Página {matrix.page} de {matrix.totalPages || 1}</span><div className="flex gap-2"><Button type="button" size="sm" variant="outline" disabled={matrix.page <= 1} onClick={() => onPage(matrix.page - 1)}>Anterior</Button><Button type="button" size="sm" variant="outline" disabled={matrix.page >= matrix.totalPages} onClick={() => onPage(matrix.page + 1)}>Siguiente</Button></div></div></div>;
}

function errorMessage(reason: unknown, fallback: string) { return operationsErrorMessage(reason, fallback); }
