'use client';

import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ChevronDown } from 'lucide-react';
import { ConfirmModal } from '@/components/confirm-modal';
import { LoadingSpinner } from '@/components/loading-spinner';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { getHomeRouteForRole, getStoredSession } from '@/lib/auth-api';
import { createOrResumeBillingDraft, FiscalBillingApiError, fiscalBillingIssueMessage, getFiscalPreparation, requestBillingDocumentElectronicIssuance, type FiscalPreparation, type FiscalPreparationLine } from '@/lib/fiscal-billing-api';
import styles from '../../../fiscal-billing.module.css';

const RECEIVER_TYPES = [['01', 'Cédula física'], ['02', 'Cédula jurídica'], ['03', 'DIMEX'], ['04', 'NITE']] as const;
const PAYMENT_METHODS = [['01', 'Efectivo'], ['02', 'Tarjeta'], ['03', 'Cheque'], ['04', 'Transferencia/depósito bancario'], ['05', 'Recaudado por terceros'], ['06', 'SINPE Móvil'], ['07', 'Plataforma digital'], ['99', 'Otros']] as const;
type DocumentType = '01' | '04';
type ReceiverType = '01' | '02' | '03' | '04';
type Phase = 'IDLE' | 'SAVING' | 'ISSUING';

function decimal(value: string) { const [whole = '0', fraction] = value.split('.'); const sign = whole.startsWith('-') ? '-' : ''; const digits = sign ? whole.slice(1) : whole; return `${sign}${digits.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}.${(fraction ?? '').padEnd(2, '0').slice(0, 2)}`; }
function money(value: string, currency: string) { return `${currency} ${decimal(value)}`; }
function condition(p: FiscalPreparation) { const c = p.paymentCondition; if (c.type === 'CASH') return 'Contado'; if (c.type === 'CREDIT') { if (c.termValue && c.termUnit) { const unit = c.termUnit === 'DAYS' ? (c.termValue === 1 ? 'día' : 'días') : (c.termValue === 1 ? 'mes' : 'meses'); return `Crédito · ${c.termValue} ${unit}`; } return 'Crédito'; } return 'No especificada'; }

function Line({ line, currency }: { line: FiscalPreparationLine; currency: string }) {
  const profile = line.fiscalReadiness.profile;
  const label = { READY: 'Lista', MISSING: 'Faltante', INACTIVE: 'Inactiva', INVALID: 'Inválida' }[line.fiscalReadiness.status];
  return <article className={styles.line}><div className={styles.lineHeader}><div><h3>{line.serviceName}</h3><p>{line.serviceCode}</p></div><Badge className={line.fiscalReadiness.status === 'READY' ? styles.readyBadge : styles.errorBadge} variant="outline">{label}</Badge></div><div className={styles.profileGrid}><div><span>Subtotal</span><strong>{money(line.subtotal, currency)}</strong></div><div><span>IVA comercial</span><strong>{line.vatPercentage}% · {money(line.vatAmount, currency)}</strong></div><div><span>Total</span><strong>{money(line.total, currency)}</strong></div><div><span>CABYS</span><strong>{profile?.cabysCode ?? 'No disponible'}</strong></div><div><span>Unidad</span><strong>{profile?.unitOfMeasureCode ?? 'No disponible'}</strong></div></div>{line.commercialNotes && <p className={styles.notes}><strong>Notas:</strong> {line.commercialNotes}</p>}{line.fiscalReadiness.issues.length > 0 && <p className={styles.notes}>Validaciones: {line.fiscalReadiness.issues.map(fiscalBillingIssueMessage).join(' ')}</p>}</article>;
}

export default function FiscalPreparationPage() {
  const params = useParams<{ salesOrderId: string }>(); const router = useRouter();
  const [authorized, setAuthorized] = useState(false); const [preparation, setPreparation] = useState<FiscalPreparation | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<FiscalBillingApiError | null>(null); const [reload, setReload] = useState(0);
  const [issuerId, setIssuerId] = useState(''); const [documentType, setDocumentType] = useState<DocumentType>('01'); const [receiverType, setReceiverType] = useState<ReceiverType | ''>(''); const [receiverNumber, setReceiverNumber] = useState(''); const [paymentMethods, setPaymentMethods] = useState<string[]>(['04']);
  const [formError, setFormError] = useState(''); const [confirming, setConfirming] = useState(false); const [phase, setPhase] = useState<Phase>('IDLE'); const [recoveryDocumentId, setRecoveryDocumentId] = useState<string | null>(null);
  const submitGuard = useRef(false); const initializedSource = useRef<string | null>(null);

  useEffect(() => { const session = getStoredSession(); if (!session?.user?.id) { router.replace('/'); return; } const role = String(session.user.role ?? '').toUpperCase(); if (role !== 'ADMIN' && role !== 'FACTURACION_COBROS') { router.replace(getHomeRouteForRole(role)); return; } setAuthorized(true); }, [router]);
  useEffect(() => { if (!authorized) return; const controller = new AbortController(); void reload; void getFiscalPreparation(params.salesOrderId, controller.signal).then((result) => { setPreparation(result); setError(null); }).catch((requestError) => { if (!controller.signal.aborted) setError(requestError instanceof FiscalBillingApiError ? requestError : new FiscalBillingApiError('FISCAL_BILLING_REQUEST_FAILED', 'No se pudo cargar la información de facturación.')); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [authorized, params.salesOrderId, reload]);
  useEffect(() => { if (!preparation || initializedSource.current === preparation.source.id) return; initializedSource.current = preparation.source.id; if (preparation.issuerChoices.length === 1) setIssuerId(preparation.issuerChoices[0].id); const code = preparation.customer.receiverIdentificationTypeCode; setReceiverType(code ?? ''); setReceiverNumber(preparation.customer.receiverIdentificationNumber ?? ''); }, [preparation]);

  const setPaymentMethod = (code: string, checked: boolean) => setPaymentMethods((current) => !checked ? current.filter((value) => value !== code) : current.includes(code) || current.length >= 4 ? current : [...current, code]);
  const validate = () => { if (!issuerId) return 'Seleccione un emisor fiscal.'; if (!preparation?.documentTypeChoices.some((choice) => choice.code === documentType)) return 'Seleccione un tipo de documento admitido.'; const number = receiverNumber.trim(), hasType = receiverType !== '', hasNumber = number !== ''; if (documentType === '01' && (!hasType || !hasNumber)) return 'La factura electrónica requiere la identificación completa del receptor.'; if (documentType === '04' && hasType !== hasNumber) return 'Complete ambos campos de identificación o deje ambos vacíos.'; if (hasNumber && (!/^[0-9 -]+$/.test(number) || number.length > 30)) return 'Use únicamente dígitos, espacios o guiones en la identificación.'; if (paymentMethods.length < 1 || paymentMethods.length > 4 || new Set(paymentMethods).size !== paymentMethods.length) return 'Seleccione entre uno y cuatro métodos de pago sin duplicados.'; return ''; };
  const requestConfirmation = () => { const message = validate(); setFormError(message); if (!message) setConfirming(true); };
  const confirmAndIssue = async () => { if (submitGuard.current) return; const message = validate(); if (message) { setFormError(message); setConfirming(false); return; } submitGuard.current = true; setConfirming(false); setFormError(''); let documentId: string | null = null; try { setPhase('SAVING'); const identity = receiverType && receiverNumber.trim() ? { receiverIdentificationTypeCode: receiverType, receiverIdentificationNumber: receiverNumber.trim() } : {}; const workspace = await createOrResumeBillingDraft(params.salesOrderId, { fiscalIssuerId: issuerId, documentTypeCode: documentType, ...identity, paymentMethodCodes: paymentMethods }); documentId = workspace.id; setRecoveryDocumentId(workspace.id); setPhase('ISSUING'); await requestBillingDocumentElectronicIssuance(workspace.id); router.push(`/fiscal-billing/documents/${encodeURIComponent(workspace.id)}`); } catch (requestError) { setFormError(documentId ? 'La información fiscal quedó guardada, pero no se pudo solicitar la emisión. Intente nuevamente; se reutilizará el mismo documento.' : requestError instanceof FiscalBillingApiError ? requestError.message : 'No se pudo confirmar la facturación.'); } finally { submitGuard.current = false; setPhase('IDLE'); } };

  if (!authorized || loading) return <main className="app-shell"><div className={styles.state}><LoadingSpinner message="Cargando datos de facturación…" /></div></main>;
  if (error || !preparation) return <main className="app-shell"><div className={styles.state}><div><h1>No se pudo cargar la facturación</h1><p>{error?.message ?? 'La información no está disponible.'}</p>{error && <p className={styles.errorCode}>Código: {error.code}</p>}<Button variant="outline" onClick={() => { setLoading(true); setError(null); setReload((value) => value + 1); }}>Intentar nuevamente</Button>{' '}<Button asChild variant="outline"><Link href="/fiscal-billing/sales-orders">Volver</Link></Button></div></div></main>;

  const blocking = preparation.issues.filter((issue) => issue.blocking); const attention = !preparation.customer.receiverFiscalIdentityComplete && !(receiverType && receiverNumber.trim()); const labels = PAYMENT_METHODS.filter(([code]) => paymentMethods.includes(code)).map(([, label]) => label); const busy = phase !== 'IDLE';
  if (preparation.existingPrimaryDocument) return <main className="app-shell"><div className={styles.page}><Link className={styles.backLink} href="/fiscal-billing/sales-orders"><ArrowLeft />Volver a Órdenes por facturar</Link><header className={styles.header}><p className={styles.eyebrow}>Facturación fiscal</p><h1 className={styles.title}>{preparation.source.number}</h1></header><section className={`${styles.card} ${styles.section}`}><h2>Documento pendiente</h2><p className={styles.muted}>La información fiscal de esta orden ya fue guardada. Continúe desde el documento para confirmar la emisión sin reemplazar sus datos.</p><Button asChild className={styles.primaryAction}><Link href={`/fiscal-billing/documents/${encodeURIComponent(preparation.existingPrimaryDocument.id)}`}>Continuar facturación</Link></Button></section></div></main>;

  return <main className="app-shell"><div className={styles.page}>
    <Link className={styles.backLink} href="/fiscal-billing/sales-orders"><ArrowLeft />Volver a Órdenes por facturar</Link><header className={styles.header}><p className={styles.eyebrow}>Facturación fiscal</p><h1 className={styles.title}>{preparation.source.number}</h1><p className={styles.subtitle}>Revise los datos fiscales antes de confirmar la emisión.</p></header>
    <div className={styles.grid}><section className={`${styles.card} ${styles.section}`}><h2>Emisor fiscal</h2><div className={styles.formGrid}><label><span>Emisor</span><select value={issuerId} onChange={(event) => setIssuerId(event.target.value)} disabled={busy}><option value="">Seleccione…</option>{preparation.issuerChoices.map((issuer) => <option key={issuer.id} value={issuer.id}>{issuer.displayName} · {issuer.legalName}</option>)}</select></label></div></section><section className={`${styles.card} ${styles.section}`}><h2>Tipo de documento</h2><div className={styles.formGrid}><label><span>Documento fiscal</span><select value={documentType} onChange={(event) => { if (event.target.value === '01' || event.target.value === '04') setDocumentType(event.target.value); }} disabled={busy}>{preparation.documentTypeChoices.filter((choice) => choice.code === '01' || choice.code === '04').map((choice) => <option key={choice.code} value={choice.code}>{choice.code} · {choice.label}</option>)}</select></label></div></section></div>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Receptor</h2><dl className={styles.details}><div><dt>Nombre</dt><dd>{preparation.customer.name}</dd></div><div><dt>Correo</dt><dd>{preparation.customer.email ?? 'No registrado'}</dd></div></dl><div className={styles.formGrid}><label><span>Tipo de identificación</span><select value={receiverType} onChange={(event) => setReceiverType(event.target.value as ReceiverType | '')} disabled={busy}><option value="">Seleccione…</option>{RECEIVER_TYPES.map(([code, label]) => <option key={code} value={code}>{code} · {label}</option>)}</select></label><label><span>Número de identificación</span><input value={receiverNumber} onChange={(event) => setReceiverNumber(event.target.value)} placeholder="Dígitos, espacios o guiones" disabled={busy} /></label></div>{attention && preparation.customer.receiverFiscalIdentityStatus === 'UNSUPPORTED' && <div className={`${styles.issue} ${styles.issueBlocking}`} role="alert"><strong>La identificación registrada no corresponde a un tipo fiscal admitido.</strong><p>Seleccione un tipo compatible y confirme el número. El registro del cliente no será modificado.</p></div>}{attention && preparation.customer.receiverFiscalIdentityStatus === 'INCOMPLETE' && <div className={`${styles.issue} ${styles.issueBlocking}`} role="alert"><strong>La identificación fiscal del receptor está incompleta.</strong><p>Seleccione el tipo y complete el número antes de emitir.</p></div>}</section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Condición comercial</h2><dl className={styles.details}><div><dt>Condición</dt><dd>{condition(preparation)}</dd></div><div><dt>Moneda</dt><dd>{preparation.currency}</dd></div></dl></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Métodos de pago</h2><p className={styles.muted}>Seleccione entre uno y cuatro métodos fiscales. La condición comercial no cambia con esta selección.</p><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="outline" className={styles.secondaryAction} disabled={busy}>{labels.length === 1 ? labels[0] : `${labels.length} métodos seleccionados`}<ChevronDown /></Button></DropdownMenuTrigger><DropdownMenuContent align="start">{PAYMENT_METHODS.map(([code, label]) => <DropdownMenuCheckboxItem key={code} checked={paymentMethods.includes(code)} disabled={!paymentMethods.includes(code) && paymentMethods.length >= 4} onCheckedChange={(checked) => setPaymentMethod(code, checked === true)} onSelect={(event) => event.preventDefault()}>{code} · {label}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu><div className={styles.types}>{PAYMENT_METHODS.filter(([code]) => paymentMethods.includes(code)).map(([code, label]) => <Badge key={code} variant="outline" className={styles.paymentMethodBadge}>{code} · {label}</Badge>)}</div></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Detalle</h2><div className={styles.lineList}>{preparation.lines.map((line) => <Line key={line.id} line={line} currency={preparation.currency} />)}</div></section>
    <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Totales</h2><dl className={styles.details}><div><dt>Subtotal</dt><dd>{money(preparation.totals.calculatedSubtotal, preparation.currency)}</dd></div><div><dt>IVA</dt><dd>{money(preparation.totals.calculatedVat, preparation.currency)}</dd></div><div><dt>Total</dt><dd>{money(preparation.totals.calculatedTotal, preparation.currency)}</dd></div></dl></section>
    {blocking.length > 0 && <section className={`${styles.card} ${styles.section} ${styles.sectionGap}`}><h2>Información por revisar</h2><div className={styles.issueList}>{blocking.map((issue, index) => <div className={`${styles.issue} ${styles.issueBlocking}`} key={`${issue.code}-${index}`}><strong>{fiscalBillingIssueMessage(issue.code)}</strong><p>Debe resolver este punto antes de emitir.</p></div>)}</div></section>}{recoveryDocumentId && <div className={`${styles.statusAlert} ${styles.infoAlert}`}><strong>Documento guardado</strong><p>Puede volver a intentar; se reutilizará la información persistida.</p></div>}{formError && <div className={`${styles.issue} ${styles.issueBlocking}`} role="alert">{formError}</div>}<div className={styles.workspaceActions}><Button className={styles.primaryAction} disabled={busy || blocking.length > 0} onClick={requestConfirmation}>{phase === 'SAVING' ? 'Guardando información…' : phase === 'ISSUING' ? 'Solicitando emisión…' : 'Confirmar y emitir'}</Button></div>
  </div><ConfirmModal isOpen={confirming} title="Confirmar y emitir" confirmText="Confirmar y emitir" confirmVariant="warning" isLoading={busy} onCancel={() => { if (!busy) setConfirming(false); }} onConfirm={() => void confirmAndIssue()} message={<div><p>Se confirmarán los datos revisados y se solicitará la emisión electrónica.</p><p>La asignación fiscal no podrá revertirse desde esta pantalla.</p></div>} /></main>;
}
