import { HttpException } from "@nestjs/common";
import { readFileSync } from "node:fs";
import type { BillingDocumentSubmissionPreparationService, BillingDocumentSubmissionPreparationResult } from "./billing-document-submission-preparation.service";
import type { BillingDocumentSubmissionAttemptService, BillingDocumentSubmissionAttemptResult } from "./billing-document-submission-attempt.service";
import { BillingDocumentSubmissionExecutorService } from "./billing-document-submission-executor.service";
import { ElectronicDocumentSubmissionError, type ElectronicDocumentSubmissionProvider } from "./providers/electronic-document-submission.provider";

const HASH="a".repeat(64),ATTEMPT=new Date("2026-08-24T12:00:00.123Z");
describe("BillingDocumentSubmissionExecutorService",()=>{
  it("validates the exact job and executes preparation, claim, and one provider call in order",async()=>{const c=context();const result=await c.service.execute(job());expect(c.prepare).toHaveBeenCalledTimes(1);expect(c.prepare).toHaveBeenCalledWith("tenant-a","document-a");expect(c.claim).toHaveBeenCalledTimes(1);expect(c.claim).toHaveBeenCalledWith(c.prepared);expect(c.submit).toHaveBeenCalledTimes(1);expect(c.submit).toHaveBeenCalledWith(c.prepared.preparedSubmission);expect(c.order).toEqual(["prepare","claim","provider"]);expect(result).toEqual({classification:"ACKNOWLEDGED",attempt:{tenantId:"tenant-a",billingDocumentId:"document-a",requestHash:HASH,attemptedAt:ATTEMPT},acknowledgement:c.ack});});

  it.each([
    ["wrong name",{name:"other"}],["invalid id",{id:"wrong"}],["missing field",{payload:{tenantId:"tenant-a",eventVersion:1}}],
    ["extra field",{payload:{tenantId:"tenant-a",billingDocumentId:"document-a",eventVersion:1,extra:true}}],
    ["primitive payload",{payload:"raw"}],["array payload",{payload:[]}],["wrong version",{payload:{tenantId:"tenant-a",billingDocumentId:"document-a",eventVersion:2}}],
    ["tenant metadata mismatch",{metadata:{tenantId:"tenant-b"}}],["untrimmed tenant",{payload:{tenantId:" tenant-a",billingDocumentId:"document-a",eventVersion:1}}],
  ])("rejects %s before preparation",async(_label,override)=>{const c=context();const error=await capture(c.service.execute({...job(),...override}));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_JOB_INVALID"});expect(c.prepare).not.toHaveBeenCalled();expect(c.claim).not.toHaveBeenCalled();expect(c.submit).not.toHaveBeenCalled();});

  it("stops safely when preparation fails",async()=>{const c=context();c.prepare.mockRejectedValue(new HttpException({code:"BILLING_DOCUMENT_SUBMISSION_PREPARATION_FAILED"},422));const error=await capture(c.service.execute(job()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_PREPARATION_FAILED"});expect(c.claim).not.toHaveBeenCalled();expect(c.submit).not.toHaveBeenCalled();});

  it.each(["ALREADY_ACKNOWLEDGED","RECONCILIATION_REQUIRED","ALREADY_FAILED"] as const)("maps claim %s without provider call",async classification=>{const c=context({claim:{classification,tenantId:"tenant-a",billingDocumentId:"document-a"} as BillingDocumentSubmissionAttemptResult});const result=await c.service.execute(job());expect(c.submit).not.toHaveBeenCalled();if(classification==="RECONCILIATION_REQUIRED")expect(result).toEqual({classification:"RECONCILIATION_REQUIRED",reasonCode:"EXISTING_RECONCILIATION_REQUIRED",retryAfterSeconds:null,tenantId:"tenant-a",billingDocumentId:"document-a"});else expect(result).toEqual({classification,tenantId:"tenant-a",billingDocumentId:"document-a"});});

  it("rejects an unknown runtime claim without provider access",async()=>{const c=context({claim:{classification:"UNKNOWN",tenantId:"tenant-a",billingDocumentId:"document-a"} as never});const error=await capture(c.service.execute(job()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_CLAIM_CLASSIFICATION_INVALID"});expect(c.submit).not.toHaveBeenCalled();});

  it.each([
    ["ELECTRONIC_SUBMISSION_INVALID","DEFINITE_REJECTION"],["ELECTRONIC_SUBMISSION_AUTHENTICATION_FAILED","CONFIGURATION_FAILURE"],["ELECTRONIC_SUBMISSION_AUTHORIZATION_FAILED","CONFIGURATION_FAILURE"],
    ["ELECTRONIC_SUBMISSION_ISSUER_NOT_READY","DEFINITE_REJECTION"],["ELECTRONIC_SUBMISSION_PAYLOAD_TOO_LARGE","DEFINITE_REJECTION"],["ELECTRONIC_SUBMISSION_FISCAL_RULE_REJECTED","DEFINITE_REJECTION"],["ELECTRONIC_SUBMISSION_IDEMPOTENCY_CONFLICT","DEFINITE_REJECTION"],
  ] as const)("maps stable provider failure %s to definite failure",async(code,outcome)=>{const c=context({providerError:new ElectronicDocumentSubmissionError(code,outcome)});const result=await c.service.execute(job());expect(result).toEqual({classification:"DEFINITE_FAILURE",attempt:attempt(),errorCode:code});expect(c.submit).toHaveBeenCalledTimes(1);});

  it.each([
    ["ELECTRONIC_SUBMISSION_TIMEOUT","UNKNOWN_REQUIRES_RECONCILIATION",null],["ELECTRONIC_SUBMISSION_PROVIDER_UNAVAILABLE","UNKNOWN_REQUIRES_RECONCILIATION",null],
    ["ELECTRONIC_SUBMISSION_INVALID_PROVIDER_RESPONSE","UNKNOWN_REQUIRES_RECONCILIATION",null],["ELECTRONIC_SUBMISSION_IDEMPOTENCY_IN_PROGRESS","RETRY_SAME_REQUEST",30],
    ["ELECTRONIC_SUBMISSION_RATE_LIMITED","RETRY_SAME_REQUEST",60],
  ] as const)("maps stable provider condition %s to reconciliation",async(code,outcome,retry)=>{const c=context({providerError:new ElectronicDocumentSubmissionError(code,outcome,retry)});expect(await c.service.execute(job())).toEqual({classification:"RECONCILIATION_REQUIRED",attempt:attempt(),reasonCode:code,retryAfterSeconds:retry});expect(c.submit).toHaveBeenCalledTimes(1);});

  it("maps unexpected provider exceptions conservatively without leaking them or retrying",async()=>{const c=context({providerError:new Error("raw provider body secret-key consecutive identification")});const result=await c.service.execute(job());expect(result).toEqual({classification:"RECONCILIATION_REQUIRED",attempt:attempt(),reasonCode:"ELECTRONIC_SUBMISSION_UNEXPECTED_ERROR",retryAfterSeconds:null});expect(c.submit).toHaveBeenCalledTimes(1);const safe=JSON.stringify(result);for(const value of [c.prepared.preparedSubmission.canonicalBody,c.prepared.preparedSubmission.idempotencyKey,"raw provider","secret-key","00100001010000000042"])expect(safe).not.toContain(value);});

  it("has no persistence/transaction dependency and registers no BullMQ processor or Redis worker",()=>{const source=readFileSync(require.resolve("./billing-document-submission-executor.service"),"utf8");expect(source).not.toMatch(/Prisma|\$transaction|@Processor|bullmq|WorkerService|Redis/);const c=context();expect(Object.keys(c.service)).toEqual(expect.arrayContaining(["preparation","attempts","provider"]));});
});

function context(options:{claim?:BillingDocumentSubmissionAttemptResult;providerError?:Error}={}){const order:string[]=[],prepared=preparation(),ack={classification:"ACKNOWLEDGED_PROVIDER_SUBMISSION" as const,providerDocumentId:"provider-a",haciendaKey:"50624082600310167816600100001010000000042142351111",consecutive:"00100001010000000042",status:{providerStatus:"queued",final:false,accepted:false,rejected:false},providerEnvironment:"sandbox" as const,estimatedReadyAt:null};const prepare=jest.fn(async()=>{order.push("prepare");return prepared;}),claim=jest.fn(async()=>{order.push("claim");return options.claim??claimed();}),submit=jest.fn(async()=>{order.push("provider");if(options.providerError)throw options.providerError;return ack;});return{order,prepared,ack,prepare,claim,submit,service:new BillingDocumentSubmissionExecutorService({prepare} as unknown as BillingDocumentSubmissionPreparationService,{claim} as unknown as BillingDocumentSubmissionAttemptService,{submitElectronicDocument:submit} as ElectronicDocumentSubmissionProvider)};}
function job(){return{name:"billing-document-electronic-issuance-requested",id:"fiscal-issuance-outbox-a",payload:{tenantId:"tenant-a",billingDocumentId:"document-a",eventVersion:1},metadata:{tenantId:"tenant-a",correlationId:"safe"}};}
function preparation():BillingDocumentSubmissionPreparationResult{return{identity:{tenantId:"tenant-a",billingDocumentId:"document-a"},allocationIdentity:{billingDocumentNumberSequenceId:"sequence-a",allocatedSequenceNumber:"42"},recoveryIdentity:{fiscalNumber:"00100001010000000042",documentTypeCode:"01",issuanceIdempotencyKey:"billing-document:document-a:electronic-issuance:v1",fiscalEmissionAt:new Date("2026-08-24T06:00:00Z"),fiscalIssueDate:"2026-08-24",issuedAt:null},preparedSubmission:{endpoint:"/documents/factura",canonicalBody:'{"customer":"private"}',requestHash:HASH,idempotencyKey:"billing-document:document-a:electronic-issuance:v1",metadata:{billingDocumentId:"document-a",tenantId:"tenant-a",documentTypeCode:"01",fiscalNumber:"00100001010000000042",fiscalIssueDate:"2026-08-24"}},providerState:{billingMode:"ELECTRONIC_PROVIDER",lifecycleStatus:"CONFIRMED",providerStatus:"PENDING",taxAuthorityStatus:"NOT_SUBMITTED",providerDocumentId:null,providerEnvironment:null,providerRequestHash:null,providerLastAttemptAt:null,providerLastErrorCode:null,providerLastErrorAt:null,providerReconciliationRequired:false,haciendaKey:null,submittedAt:null}};}
function claimed():BillingDocumentSubmissionAttemptResult{return{classification:"CLAIMED",tenantId:"tenant-a",billingDocumentId:"document-a",requestHash:HASH,attemptedAt:ATTEMPT,issuanceIdempotencyKey:"billing-document:document-a:electronic-issuance:v1"};}
function attempt(){return{tenantId:"tenant-a",billingDocumentId:"document-a",requestHash:HASH,attemptedAt:ATTEMPT};}
async function capture(promise:Promise<unknown>){try{await promise;throw new Error("expected error");}catch(error){expect(error).toBeInstanceOf(HttpException);return error as HttpException;}}
