import { HttpException } from "@nestjs/common";
import type { PrismaService } from "../prisma/prisma.service";
import type { BillingDocumentSubmissionExecutorOutcome } from "./billing-document-submission-executor.service";
import { BillingDocumentSubmissionOutcomeService } from "./billing-document-submission-outcome.service";
import type { FiscalIssuanceClock } from "./fiscal-issuance.clock";

const HASH="a".repeat(64),ATTEMPT=new Date("2026-08-24T12:00:00.123Z"),EMISSION=new Date("2026-08-24T06:09:00.000Z"),ERROR_AT=new Date("2026-08-24T12:01:00.456Z");
const NUMBER="00100001010000000042",KEY=`506240826003101678166${NUMBER}142351111`;
describe("BillingDocumentSubmissionOutcomeService",()=>{
  it("persists a queued acknowledgement through tenant-scoped lock and exact CAS without clock",async()=>{const c=context(row());const result=await c.service.persist(acknowledged());expect(result).toEqual({classification:"PERSISTED",tenantId:"tenant-a",billingDocumentId:"document-a"});const [sql,id,tenant]=c.tx.$queryRaw.mock.calls[0];expect((sql as string[]).join("?")).toContain("FOR UPDATE");expect(id).toBe("document-a");expect(tenant).toBe("tenant-a");expect(c.tx.billingDocument.findUnique).toHaveBeenCalledWith(expect.objectContaining({where:{id_tenantId:{id:"document-a",tenantId:"tenant-a"}}}));const write=c.tx.billingDocument.updateMany.mock.calls[0][0];expect(write.where).toMatchObject({id:"document-a",tenantId:"tenant-a",providerRequestHash:HASH,providerLastAttemptAt:ATTEMPT,providerReconciliationRequired:true,providerDocumentId:null,haciendaKey:null});expect(write.data).toMatchObject({providerDocumentId:"provider-a",haciendaKey:KEY,providerEnvironment:"sandbox",providerStatus:"PROCESSED",taxAuthorityStatus:"PROCESSING",lifecycleStatus:"SUBMITTED",submittedAt:ATTEMPT,issuedAt:null,taxAuthorityFinalizedAt:null,providerReconciliationRequired:false,providerStatusCheckAttempts:0,providerLastStatusCheckAt:null,providerNextStatusCheckAt:new Date(ATTEMPT.getTime()+10_000),providerStatusCheckLockOwner:null,providerStatusCheckLeaseUntil:null});expect(write.data).not.toHaveProperty("providerRequestHash");expect(write.data).not.toHaveProperty("providerLastAttemptAt");expect(c.clock.now).not.toHaveBeenCalled();});

  it("persists direct acceptance with XML emission as issuedAt and one observed terminal timestamp",async()=>{const c=context(row()),outcome=acknowledged();outcome.acknowledgement.status={providerStatus:"accepted",final:true,accepted:true,rejected:false};await c.service.persist(outcome);const data=c.tx.billingDocument.updateMany.mock.calls[0][0].data;expect(data).toMatchObject({taxAuthorityStatus:"ACCEPTED",issuedAt:EMISSION,taxAuthorityFinalizedAt:ERROR_AT});expect(data.issuedAt).not.toBe(ERROR_AT);expect(c.clock.now).toHaveBeenCalledTimes(1);});
  it("persists direct rejection with no issuedAt and one observed terminal timestamp",async()=>{const c=context(row()),outcome=acknowledged();outcome.acknowledgement.status={providerStatus:"rejected",final:true,accepted:false,rejected:true};await c.service.persist(outcome);const data=c.tx.billingDocument.updateMany.mock.calls[0][0].data;expect(data).toMatchObject({taxAuthorityStatus:"REJECTED",issuedAt:null,taxAuthorityFinalizedAt:ERROR_AT});expect(c.clock.now).toHaveBeenCalledTimes(1);});

  it("persists an immediate rejected acknowledgement detail exactly",async()=>{const detail=`Fiscal ${"R".repeat(1200)}`,outcome=acknowledged();outcome.acknowledgement.status={providerStatus:"rejected",final:true,accepted:false,rejected:true};outcome.acknowledgement.rejectionDetail=detail;const c=context(row());await c.service.persist(outcome);const data=c.tx.billingDocument.updateMany.mock.calls[0][0].data;expect(data).toMatchObject({taxAuthorityStatus:"REJECTED",haciendaRejectionDetail:detail,issuedAt:null,taxAuthorityFinalizedAt:ERROR_AT});expect(data.providerLastErrorCode).toBeNull();});

  it("keeps immediate rejected null detail explicit and clears it for non-rejected outcomes",async()=>{let outcome=acknowledged();outcome.acknowledgement.status={providerStatus:"rejected",final:true,accepted:false,rejected:true};let c=context(row());await c.service.persist(outcome);expect(c.tx.billingDocument.updateMany.mock.calls[0][0].data.haciendaRejectionDetail).toBeNull();outcome=acknowledged();c=context(row());await c.service.persist(outcome);expect(c.tx.billingDocument.updateMany.mock.calls[0][0].data.haciendaRejectionDetail).toBeNull();});

  it.each([
    ["consecutive",{consecutive:"00100001010000000043"}],["embedded consecutive",{haciendaKey:KEY.slice(0,21)+"00100001010000000043"+KEY.slice(41)}],
    ["key date",{haciendaKey:KEY.replace("240826","230826")}],["environment",{providerEnvironment:"other"}],
  ])("rejects acknowledgement %s mismatch without write or clock",async(_label,override)=>{const c=context(row());const outcome=acknowledged();Object.assign(outcome.acknowledgement,override);const error=await capture(c.service.persist(outcome));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_ACKNOWLEDGEMENT_MISMATCH"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it.each([["hash",{providerRequestHash:"b".repeat(64)}],["timestamp",{providerLastAttemptAt:new Date("2026-08-24T12:00:01Z")}]] as const)("rejects stale %s",async(_label,override)=>{const c=context(row(override));const error=await capture(c.service.persist(acknowledged()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_STALE_ATTEMPT"});expect(c.clock.now).not.toHaveBeenCalled();});

  it.each([{providerDocumentId:"partial"},{providerLastErrorCode:"PARTIAL"},{providerReconciliationRequired:false},{billingDocumentNumberSequenceId:null}])("rejects corrupt claimed state: %o",async override=>{const c=context(row(override));const error=await capture(c.service.persist(acknowledged()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_STATE_CORRUPT"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it("persists definite failure with one safe error clock reading and preserves allocation/attempt",async()=>{const c=context(row());await c.service.persist(definite());const write=c.tx.billingDocument.updateMany.mock.calls[0][0];expect(write.data).toMatchObject({providerLastErrorCode:"ELECTRONIC_SUBMISSION_INVALID",providerLastErrorAt:ERROR_AT,providerReconciliationRequired:false,providerStatus:"FAILED",providerStatusCheckAttempts:0,providerNextStatusCheckAt:null});expect(write.where).toMatchObject({billingDocumentNumberSequenceId:"sequence-a",allocatedSequenceNumber:42n,providerRequestHash:HASH,providerLastAttemptAt:ATTEMPT});expect(write.data).not.toHaveProperty("fiscalNumber");expect(write.data).not.toHaveProperty("allocatedSequenceNumber");expect(c.clock.now).toHaveBeenCalledTimes(1);});

  it("persists uncertain outcome while preserving reconciliation, lifecycle, and acceptance state",async()=>{const c=context(row());await c.service.persist(reconciliation());const write=c.tx.billingDocument.updateMany.mock.calls[0][0];expect(write.data).toMatchObject({providerLastErrorCode:"ELECTRONIC_SUBMISSION_TIMEOUT",providerLastErrorAt:ERROR_AT,providerReconciliationRequired:true,providerStatusCheckAttempts:0,providerNextStatusCheckAt:null});expect(write.data).not.toHaveProperty("lifecycleStatus");expect(write.data).not.toHaveProperty("taxAuthorityStatus");expect(write.data).not.toHaveProperty("issuedAt");expect(c.clock.now).toHaveBeenCalledTimes(1);});

  it("validates already-acknowledged and already-failed outcomes idempotently without write or clock",async()=>{let c=context(ackRow());await expect(c.service.persist({classification:"ALREADY_ACKNOWLEDGED",tenantId:"tenant-a",billingDocumentId:"document-a"})).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();c=context(failedRow());await expect(c.service.persist({classification:"ALREADY_FAILED",tenantId:"tenant-a",billingDocumentId:"document-a"})).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it.each([{lifecycleStatus:"SUBMITTED"},{taxAuthorityStatus:"ACCEPTED"},{taxAuthorityStatus:"REJECTED"},{submittedAt:ATTEMPT},{issuedAt:ATTEMPT}])("rejects contradictory already-failed state: %o",async override=>{const c=context(failedRow(overridesToRecord(override)));const error=await capture(c.service.persist({classification:"ALREADY_FAILED",tenantId:"tenant-a",billingDocumentId:"document-a"}));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_STATE_CORRUPT"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it("keeps a complete existing reconciliation state idempotent",async()=>{const c=context(row({providerLastErrorCode:"ELECTRONIC_SUBMISSION_TIMEOUT",providerLastErrorAt:ERROR_AT}));await expect(c.service.persist(existingReconciliation())).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it.each([{lifecycleStatus:"SUBMITTED"},{providerStatus:"PROCESSED"},{providerStatus:"FAILED"},{taxAuthorityStatus:"PROCESSING"},{taxAuthorityStatus:"ACCEPTED"},{taxAuthorityStatus:"REJECTED"},{submittedAt:ATTEMPT},{issuedAt:ATTEMPT}])("rejects contradictory existing reconciliation state: %o",async override=>{const c=context(row(overridesToRecord(override)));const error=await capture(c.service.persist(existingReconciliation()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_STATE_CORRUPT"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it("returns duplicate identical acknowledgement idempotently and rejects a different winner",async()=>{let c=context(ackRow());await expect(c.service.persist(acknowledged())).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();c=context(ackRow({providerDocumentId:"other-provider"}));const error=await capture(c.service.persist(acknowledged()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT"});expect(c.clock.now).not.toHaveBeenCalled();});

  it("preserves the original direct terminal timestamp on an accepted acknowledgement retry",async()=>{const outcome=acknowledged();outcome.acknowledgement.status={providerStatus:"accepted",final:true,accepted:true,rejected:false};const originalFinalizedAt=new Date("2026-08-24T12:00:30.000Z"),c=context(ackRow({taxAuthorityStatus:"ACCEPTED",providerNextStatusCheckAt:null,issuedAt:EMISSION,taxAuthorityFinalizedAt:originalFinalizedAt}));await expect(c.service.persist(outcome)).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();expect(c.clock.now).not.toHaveBeenCalled();});

  it("requires exact immediate rejected detail identity for retries and P2002 winners",async()=>{const detail="Normalized Hacienda rejection",outcome=acknowledged();outcome.acknowledgement.status={providerStatus:"rejected",final:true,accepted:false,rejected:true};outcome.acknowledgement.rejectionDetail=detail;let c=context(ackRow({taxAuthorityStatus:"REJECTED",providerNextStatusCheckAt:null,haciendaRejectionDetail:detail,issuedAt:null,taxAuthorityFinalizedAt:ERROR_AT}));await expect(c.service.persist(outcome)).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.tx.billingDocument.updateMany).not.toHaveBeenCalled();for(const persisted of [ackRow({taxAuthorityStatus:"REJECTED",providerNextStatusCheckAt:null,haciendaRejectionDetail:"different",issuedAt:null,taxAuthorityFinalizedAt:ERROR_AT}),ackRow({taxAuthorityStatus:"REJECTED",providerNextStatusCheckAt:null,haciendaRejectionDetail:null,issuedAt:null,taxAuthorityFinalizedAt:ERROR_AT})]){c=context(row(),{transactionError:{code:"P2002"},winner:persisted});const error=await capture(c.service.persist(outcome));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT"});}});

  it("requires compare-and-set count exactly one",async()=>{const c=context(row(),{count:0});const error=await capture(c.service.persist(acknowledged()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT"});});

  it("recovers only an exact tenant-scoped P2002 acknowledgement winner",async()=>{let c=context(row(),{transactionError:{code:"P2002"},winner:ackRow()});await expect(c.service.persist(acknowledged())).resolves.toMatchObject({classification:"ALREADY_PERSISTED"});expect(c.rootFind).toHaveBeenCalledWith(expect.objectContaining({where:{id_tenantId:{id:"document-a",tenantId:"tenant-a"}}}));c=context(row(),{transactionError:{code:"P2002",meta:"private"},winner:ackRow({providerDocumentId:"other"})});const error=await capture(c.service.persist(acknowledged()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT"});expect(JSON.stringify(error.getResponse())).not.toContain("private");});

  it.each([["different submittedAt",ackRow({submittedAt:new Date("2026-08-24T12:00:01Z")})],["different initial schedule",ackRow({providerNextStatusCheckAt:new Date(ATTEMPT.getTime()+10_001)})],["null submittedAt",ackRow({submittedAt:null})],["partial winner",ackRow({providerEnvironment:null})],["foreign tenant",ackRow({tenantId:"tenant-b"})]] as const)("rejects P2002 %s",async(_label,winner)=>{const c=context(row(),{transactionError:{code:"P2002"},winner});const error=await capture(c.service.persist(acknowledged()));expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT"});expect(c.clock.now).not.toHaveBeenCalled();});

  it.each(["missing","foreign"])("makes %s documents indistinguishable",async()=>{const c=context(null,{locked:[]});const error=await capture(c.service.persist(acknowledged()));expect(error.getStatus()).toBe(404);expect(error.getResponse()).toMatchObject({code:"BILLING_DOCUMENT_NOT_FOUND"});});

  it("uses no provider, Redis, BCCR, Hacienda, builder, queue, or external dependency",async()=>{const c=context(row());await c.service.persist(reconciliation());expect(Object.keys(c.tx).sort()).toEqual(["$queryRaw","billingDocument"]);expect(Object.keys(c.tx.billingDocument).sort()).toEqual(["findUnique","updateMany"]);});

  it("safe errors expose no fiscal/provider/customer secrets",async()=>{const c=context(row({providerRequestHash:"b".repeat(64)}));const error=await capture(c.service.persist(acknowledged()));const safe=JSON.stringify(error.getResponse());for(const secret of [KEY,NUMBER,HASH,ATTEMPT.toISOString(),"billing-document:","provider-a","customer","credential"])expect(safe).not.toContain(secret);});
});

function context(persisted:ReturnType<typeof row>|null,options:{locked?:Array<{id:string}>;count?:number;transactionError?:unknown;winner?:ReturnType<typeof row>|null}={}){const tx={$queryRaw:jest.fn().mockResolvedValue(options.locked??[{id:"document-a"}]),billingDocument:{findUnique:jest.fn().mockResolvedValue(persisted),updateMany:jest.fn().mockResolvedValue({count:options.count??1})}};const rootFind=jest.fn().mockResolvedValue(options.winner??null);const prisma={$transaction:jest.fn(async(callback:(txValue:typeof tx)=>unknown)=>{if(options.transactionError)throw options.transactionError;return callback(tx);}),billingDocument:{findUnique:rootFind}};const clock={now:jest.fn(()=>ERROR_AT)};return{tx,rootFind,clock,service:new BillingDocumentSubmissionOutcomeService(prisma as unknown as PrismaService,clock as unknown as FiscalIssuanceClock)};}
function row(overrides:Record<string,unknown>={}){return{id:"document-a",tenantId:"tenant-a",billingMode:"ELECTRONIC_PROVIDER",lifecycleStatus:"CONFIRMED",providerStatus:"PENDING",taxAuthorityStatus:"NOT_SUBMITTED",billingDocumentNumberSequenceId:"sequence-a",allocatedSequenceNumber:42n,fiscalNumber:NUMBER,issuanceIdempotencyKey:"billing-document:document-a:electronic-issuance:v1",fiscalEmissionAt:EMISSION,fiscalIssueDate:new Date("2026-08-24T00:00:00Z"),providerRequestHash:HASH,providerLastAttemptAt:ATTEMPT,providerLastErrorCode:null,providerLastErrorAt:null,providerReconciliationRequired:true,providerDocumentId:null,haciendaKey:null,haciendaRejectionDetail:null,providerEnvironment:null,submittedAt:null,issuedAt:null,taxAuthorityFinalizedAt:null,providerStatusCheckAttempts:0,providerLastStatusCheckAt:null,providerNextStatusCheckAt:null,providerStatusCheckLockOwner:null,providerStatusCheckLeaseUntil:null,...overrides};}
function ackRow(overrides:Record<string,unknown>={}){return row({lifecycleStatus:"SUBMITTED",providerStatus:"PROCESSED",taxAuthorityStatus:"PROCESSING",providerReconciliationRequired:false,providerDocumentId:"provider-a",haciendaKey:KEY,providerEnvironment:"sandbox",submittedAt:ATTEMPT,providerNextStatusCheckAt:new Date(ATTEMPT.getTime()+10_000),...overrides});}
function failedRow(overrides:Record<string,unknown>={}){return row({providerStatus:"FAILED",providerReconciliationRequired:false,providerLastErrorCode:"ELECTRONIC_SUBMISSION_INVALID",providerLastErrorAt:ERROR_AT,...overrides});}
function attempt(){return{tenantId:"tenant-a",billingDocumentId:"document-a",requestHash:HASH,attemptedAt:ATTEMPT};}
function acknowledged():Extract<BillingDocumentSubmissionExecutorOutcome,{classification:"ACKNOWLEDGED"}>{return{classification:"ACKNOWLEDGED",attempt:attempt(),acknowledgement:{classification:"ACKNOWLEDGED_PROVIDER_SUBMISSION",providerDocumentId:"provider-a",haciendaKey:KEY,consecutive:NUMBER,status:{providerStatus:"queued",final:false,accepted:false,rejected:false},providerEnvironment:"sandbox",estimatedReadyAt:null,rejectionDetail:null}};}
function definite():Extract<BillingDocumentSubmissionExecutorOutcome,{classification:"DEFINITE_FAILURE"}>{return{classification:"DEFINITE_FAILURE",attempt:attempt(),errorCode:"ELECTRONIC_SUBMISSION_INVALID"};}
function reconciliation():Extract<BillingDocumentSubmissionExecutorOutcome,{classification:"RECONCILIATION_REQUIRED"}>{return{classification:"RECONCILIATION_REQUIRED",attempt:attempt(),reasonCode:"ELECTRONIC_SUBMISSION_TIMEOUT",retryAfterSeconds:null};}
function existingReconciliation():Extract<BillingDocumentSubmissionExecutorOutcome,{classification:"RECONCILIATION_REQUIRED"}>{return{classification:"RECONCILIATION_REQUIRED",reasonCode:"EXISTING_RECONCILIATION_REQUIRED",retryAfterSeconds:null,tenantId:"tenant-a",billingDocumentId:"document-a"};}
async function capture(promise:Promise<unknown>){try{await promise;throw new Error("expected error");}catch(error){expect(error).toBeInstanceOf(HttpException);return error as HttpException;}}
function overridesToRecord(value:object):Record<string,unknown>{return value as Record<string,unknown>;}
