import { HttpException, HttpStatus } from "@nestjs/common";

export type FiscalBillingErrorCode =
  | "SALES_ORDER_NOT_FOUND"
  | "SALES_ORDER_SOURCE_NOT_ELIGIBLE"
  | "SALES_ORDER_STATUS_NOT_ELIGIBLE"
  | "SALES_ORDER_HAS_NO_LINES"
  | "SALES_ORDER_LINE_SOURCE_IDENTITY_MISSING"
  | "SALES_ORDER_LINE_FISCAL_PROFILE_MISSING"
  | "SALES_ORDER_LINE_FISCAL_PROFILE_INACTIVE"
  | "SALES_ORDER_LINE_FISCAL_PROFILE_INVALID"
  | "SALES_ORDER_LINE_TAX_MISMATCH"
  | "SALES_ORDER_TOTALS_MISMATCH"
  | "BILLING_CONFIGURATION_NOT_FOUND"
  | "BILLING_NOT_ENABLED"
  | "FISCAL_ISSUER_NOT_FOUND"
  | "FISCAL_ISSUER_NOT_ACTIVE"
  | "FISCAL_ISSUER_ECONOMIC_ACTIVITY_NOT_CONFIGURED"
  | "BILLING_DOCUMENT_TYPE_INVALID"
  | "BILLING_RECEIVER_IDENTIFICATION_INVALID"
  | "BILLING_PAYMENT_METHOD_INVALID"
  | "BILLING_COMMERCIAL_CREDIT_TERM_INVALID"
  | "BILLING_INTERNAL_NUMBER_INVALID"
  | "BILLING_DRAFT_CONFLICT"
  | "BILLING_DRAFT_ALREADY_ADVANCED"
  | "BILLING_DOCUMENT_NOT_FOUND"
  | "BILLING_DOCUMENT_NOT_ELIGIBLE_FOR_ISSUANCE"
  | "BILLING_DOCUMENT_FISCAL_READINESS_FAILED"
  | "BILLING_DOCUMENT_UNSUPPORTED_FISCAL_CURRENCY"
  | "BILLING_DOCUMENT_OFFICIAL_RATE_MISMATCH"
  | "BILLING_DOCUMENT_FISCAL_EMISSION_CONFLICT"
  | "BILLING_DOCUMENT_SEQUENCE_NOT_CONFIGURED"
  | "BILLING_DOCUMENT_SEQUENCE_EXHAUSTED"
  | "BILLING_DOCUMENT_ALLOCATION_STATE_CONFLICT"
  | "BILLING_DOCUMENT_CONCURRENT_ALLOCATION_CONFLICT"
  | "BILLING_DOCUMENT_OUTBOX_CONFLICT"
  | "BILLING_DOCUMENT_SUBMISSION_SNAPSHOT_INVALID"
  | "BILLING_DOCUMENT_SUBMISSION_PREPARATION_FAILED"
  | "BILLING_DOCUMENT_SUBMISSION_READ_FAILED"
  | "BILLING_DOCUMENT_PROVIDER_ATTEMPT_IDENTITY_CONFLICT"
  | "BILLING_DOCUMENT_PROVIDER_REQUEST_HASH_CONFLICT"
  | "BILLING_DOCUMENT_PROVIDER_ATTEMPT_STATE_CORRUPT"
  | "BILLING_DOCUMENT_PROVIDER_ATTEMPT_CONCURRENT_CONFLICT"
  | "BILLING_DOCUMENT_PROVIDER_ATTEMPT_PERSISTENCE_FAILED"
  | "BILLING_DOCUMENT_SUBMISSION_JOB_INVALID"
  | "BILLING_DOCUMENT_SUBMISSION_EXECUTION_PREPARATION_FAILED"
  | "BILLING_DOCUMENT_SUBMISSION_EXECUTION_CLAIM_FAILED"
  | "BILLING_DOCUMENT_SUBMISSION_CLAIM_CLASSIFICATION_INVALID"
  | "BILLING_DOCUMENT_SUBMISSION_OUTCOME_STALE_ATTEMPT"
  | "BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT"
  | "BILLING_DOCUMENT_SUBMISSION_OUTCOME_STATE_CORRUPT"
  | "BILLING_DOCUMENT_SUBMISSION_ACKNOWLEDGEMENT_MISMATCH"
  | "BILLING_DOCUMENT_SUBMISSION_OUTCOME_PERSISTENCE_FAILED"
  | "BILLING_DOCUMENT_STATUS_LOOKUP_INELIGIBLE"
  | "BILLING_DOCUMENT_STATUS_SNAPSHOT_INVALID"
  | "BILLING_DOCUMENT_STATUS_LOOKUP_FAILED"
  | "BILLING_DOCUMENT_STATUS_STALE"
  | "BILLING_DOCUMENT_STATUS_CONFLICT"
  | "BILLING_DOCUMENT_STATUS_STATE_CORRUPT"
  | "BILLING_DOCUMENT_STATUS_PERSISTENCE_FAILED"
  | "BILLING_DOCUMENT_RECOVERY_INELIGIBLE"
  | "BILLING_DOCUMENT_RECOVERY_IDENTITY_MISMATCH"
  | "BILLING_DOCUMENT_RECOVERY_PREPARATION_FAILED"
  | "BILLING_DOCUMENT_RECOVERY_STALE"
  | "BILLING_DOCUMENT_RECOVERY_CONFLICT"
  | "BILLING_DOCUMENT_RECOVERY_STATE_CORRUPT"
  | "BILLING_DOCUMENT_RECOVERY_CLAIM_FAILED";

const STATUS_BY_CODE: Record<FiscalBillingErrorCode, HttpStatus> = {
  SALES_ORDER_NOT_FOUND: HttpStatus.NOT_FOUND,
  SALES_ORDER_SOURCE_NOT_ELIGIBLE: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_STATUS_NOT_ELIGIBLE: HttpStatus.CONFLICT,
  SALES_ORDER_HAS_NO_LINES: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_LINE_SOURCE_IDENTITY_MISSING: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_LINE_FISCAL_PROFILE_MISSING: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_LINE_FISCAL_PROFILE_INACTIVE: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_LINE_FISCAL_PROFILE_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_LINE_TAX_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  SALES_ORDER_TOTALS_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_CONFIGURATION_NOT_FOUND: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_NOT_ENABLED: HttpStatus.UNPROCESSABLE_ENTITY,
  FISCAL_ISSUER_NOT_FOUND: HttpStatus.NOT_FOUND,
  FISCAL_ISSUER_NOT_ACTIVE: HttpStatus.UNPROCESSABLE_ENTITY,
  FISCAL_ISSUER_ECONOMIC_ACTIVITY_NOT_CONFIGURED:
    HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_TYPE_INVALID: HttpStatus.BAD_REQUEST,
  BILLING_RECEIVER_IDENTIFICATION_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_PAYMENT_METHOD_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_COMMERCIAL_CREDIT_TERM_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_INTERNAL_NUMBER_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DRAFT_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DRAFT_ALREADY_ADVANCED: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_NOT_FOUND: HttpStatus.NOT_FOUND,
  BILLING_DOCUMENT_NOT_ELIGIBLE_FOR_ISSUANCE: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_FISCAL_READINESS_FAILED: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_UNSUPPORTED_FISCAL_CURRENCY:
    HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_OFFICIAL_RATE_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_FISCAL_EMISSION_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_SEQUENCE_NOT_CONFIGURED: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_SEQUENCE_EXHAUSTED: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_ALLOCATION_STATE_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_CONCURRENT_ALLOCATION_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_OUTBOX_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_SUBMISSION_SNAPSHOT_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_SUBMISSION_PREPARATION_FAILED: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_SUBMISSION_READ_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_PROVIDER_ATTEMPT_IDENTITY_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_PROVIDER_REQUEST_HASH_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_PROVIDER_ATTEMPT_STATE_CORRUPT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_PROVIDER_ATTEMPT_CONCURRENT_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_PROVIDER_ATTEMPT_PERSISTENCE_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_SUBMISSION_JOB_INVALID: HttpStatus.BAD_REQUEST,
  BILLING_DOCUMENT_SUBMISSION_EXECUTION_PREPARATION_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_SUBMISSION_EXECUTION_CLAIM_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_SUBMISSION_CLAIM_CLASSIFICATION_INVALID: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_SUBMISSION_OUTCOME_STALE_ATTEMPT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_SUBMISSION_OUTCOME_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_SUBMISSION_OUTCOME_STATE_CORRUPT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_SUBMISSION_ACKNOWLEDGEMENT_MISMATCH: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_SUBMISSION_OUTCOME_PERSISTENCE_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_STATUS_LOOKUP_INELIGIBLE: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_STATUS_SNAPSHOT_INVALID: HttpStatus.UNPROCESSABLE_ENTITY,
  BILLING_DOCUMENT_STATUS_LOOKUP_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_STATUS_STALE: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_STATUS_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_STATUS_STATE_CORRUPT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_STATUS_PERSISTENCE_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_RECOVERY_INELIGIBLE: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_RECOVERY_IDENTITY_MISMATCH: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_RECOVERY_PREPARATION_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
  BILLING_DOCUMENT_RECOVERY_STALE: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_RECOVERY_CONFLICT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_RECOVERY_STATE_CORRUPT: HttpStatus.CONFLICT,
  BILLING_DOCUMENT_RECOVERY_CLAIM_FAILED: HttpStatus.SERVICE_UNAVAILABLE,
};

export function fiscalBillingError(
  code: FiscalBillingErrorCode,
  details?: Record<string, unknown>,
): HttpException {
  const status = STATUS_BY_CODE[code];
  return new HttpException(
    { statusCode: status, error: code, code, ...(details ? { details } : {}) },
    status,
  );
}
