import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import test from 'node:test';
const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8'); const source = () => read('../src/components/operations/operational-fulfillments-workspace.tsx'); const drawer = () => read('../src/components/operations/operational-purchase-drawer.tsx');
test('Service management remains need-scoped and operationally executable', () => { const text = source(); for (const label of ['Gestión del servicio', 'No hay reservas o gestiones creadas para esta necesidad operativa.', 'Nueva gestión', 'Confirmado']) assert.match(text, new RegExp(label)); assert.match(text, /getOperationalRequirement\(travelPackageId, requirementId\)/); assert.match(text, /listOperationalFulfillments\(travelPackageId, requirementId, page\)/); });
test('Fulfillment creation remains Requirement-scoped without a management-row passenger mutation action', () => { const text = source(); assert.match(text, /passengers=\{requirement\?\.passengers/); assert.match(text, /Seleccione al menos un pasajero/); assert.doesNotMatch(text, /addOperationalFulfillmentPassengers|removeOperationalFulfillmentPassengers|Guardar pasajeros|Pasajeros de la gestión/); assert.doesNotMatch(text, /status:\s*['"]DRAFT['"]/); });
test('Fulfillment UI has no Operations assignee control or assignee mutation', () => { const text = source(); assert.doesNotMatch(text, /Responsable|assignedToUserId|listTenantUsers|assignedTo\?\./); });
test('Management shows scoped passenger names and purchase-aware row actions', () => { const text = source(); for (const label of ['Pasajeros', 'Reservar', 'Registrar compra', 'Confirmar', '¿Cancelar gestión?', 'solo este intento de reserva o proveedor', 'compra registrada']) assert.match(text, new RegExp(label)); assert.match(text, /passengerNames\(item\.passengerPreview, item\.passengerCount\)/); assert.match(text, /passengerNames\(requirement\.passengers\.map/); assert.match(text, /Grupo: \{requirement\.source\.passengerGroup\.name\}/); assert.match(text, /item\.purchaseCount === 0/); assert.match(text, /item\.status === 'DRAFT' \|\| item\.status === 'RESERVED'/); assert.match(text, /const purchased = item\.status === 'PURCHASED'/); assert.match(text, /variant=\{purchased \? 'default' : 'outline'\}/); assert.match(text, /OperationalPurchaseDrawer/); assert.match(text, /onRegisterPurchase=\{\(\) => openDirectPurchase\(item\)\}/); assert.match(text, /fulfillmentId=\{directPurchaseTarget\.id\}/); assert.match(text, /await load\(\)/); assert.doesNotMatch(text, /openPurchaseOnLoad|openPurchaseDirect|setPurchasesFulfillment\(detail\).*Registrar compra/); assert.doesNotMatch(text, />Comprado</); assert.doesNotMatch(text, /createOperationalPurchase|createOperationalEvidence|uploadEvidence/); assert.match(drawer(), /onOpenChange\(false\);[\s\S]*await onCreated/); });

test('Management keeps multiple Purchase creation in Ver while terminal rows expose no spend action', () => { const text = source(); assert.match(text, /onPurchases=\{\(\) => setPurchasesFulfillment\(item\)\}/); assert.match(text, />Ver</); assert.doesNotMatch(text, /Ver compras y documentos|>Pasajeros<\/Button>|onPassengers|passengerTarget/); assert.match(text, /item\.status !== 'CONFIRMED' && item\.status !== 'CANCELLED'/); assert.match(text, /item\.status === 'RESERVED' \|\| purchased/); });
test('Management row opens Purchases/Documents directly without a repeated detail modal or extra fetch', () => { const text = source(); assert.match(text, /onPurchases=\{\(\) => setPurchasesFulfillment\(item\)\}/); assert.match(text, /if \(purchasesFulfillment\) return <OperationalPurchasesEvidenceWorkspace/); assert.match(text, /onBack=\{\(\) => setPurchasesFulfillment\(null\)\}/); assert.doesNotMatch(text, /Ver detalle|Detalle de gestión|detailTarget|onDetail/); assert.doesNotMatch(text, /getOperationalFulfillment\(travelPackageId, requirementId, item\.id\)\.then\(setPurchasesFulfillment\)/); });
test('Fully covered work closes ordinary management while partial coverage preselects only uncovered passengers', () => { const text = source(); assert.match(text, /completeCoverage\(requirement\.coverage\)/); assert.match(text, /!requirement\.confirmedPassengerIds\.includes/); assert.match(text, /\{!executionComplete \? <Button[^>]*>.*Nueva gestión/); assert.match(text, /!terminalRequirement\(requirement\) && !executionComplete/); });
test('Confirmation and cancellation notify mounted read models, while terminal rows retain only Ver', () => { const text = source(); assert.match(text, /if \(target === 'CONFIRMED' \|\| target === 'CANCELLED'\) onCoverageChanged\?\.\(\)/); assert.match(text, /const mutable = item\.status !== 'CONFIRMED' && item\.status !== 'CANCELLED'/); assert.match(text, /item\.status === 'RESERVED' \|\| purchased/); assert.match(text, /purchased \? <Button[^>]*>Ver<\/Button>/); assert.match(text, /!purchased \? <Button[^>]*>Ver<\/Button>/); });
